src/utils/generators/generateImports.ts
The reduce didn't add the `...} from '...';` if only 1 element inside `imports`.
Additionally, I rewrote the other line to make it cleaner (`reduce` should in general be avoided, for lack of clarity)
=> fix(generator): pathOnly generation with only 1 element in imports

src/core/generators/imports.ts
**READY**
When an output file doesn't require imports, it sometimes breaks due to an extra comma leading to a syntax error. Solution is to not generate the imports if the array is empty.
=> fix(imports): return empty string when no imports needed.

src/core/writers/tagsMode.ts
**READY**
- Interface name was not properly pascal cased (the tag part was lowercase due to being concatenated before going into `pascal()` function)
- The tags mode didn't generate any output for operations that had no tag. This is changed by adding the `"default"` tag on such operations.
=> fixes for tags mode

src/core/getters/scalar.ts
READY
A schema can sometimes be a valid array schema by just defining the 'items' prop. In such a scenario, the generated type was 'unknown'. This fixes it by applying the correct array logic to such definitions. (NestJS swagger plugin generates swagger-json with 'type' not always set for arrays)
=> fix(scalar): default 'type' to array when 'items' is defined on a schema

src/core/importers/specs.ts
**READY**
add content-type text/yaml as supported content-type to import
https://github.com/anymaniax/orval/discussions/108
branch | PR
`headers['content-type']` comparison for `text/yaml`, `text/plain` and `application/json` now all in the same way (with `includes())`. Because for instance for `application/json` the actual content-type could be `application/json; charset=utf-8`.
=> add content-type text/yaml as supported content-type to import

src/core/generators/mutator.ts, src/core/writers/singleMode.ts, src/core/writers/splitMode.ts, src/core/writers/tagsMode.ts, src/utils/path.ts
**READY**
Resolves #120 By introducing a new function named `relativeSafe` and resolve the import path using it. `relativeSafe` is the `path.relative` doppelganger that respects the meaningful leading "./"
=> fix: implement & use relativeSafe to keep leading ./ in import paths

samples/angular-app/package.json, samples/basic/package.json, samples/react-app-with-react-query/package.json, samples/react-app/package.json, samples/svelte-query/package.json
**READY**
Fix the orval bin path in sample projects
They have been left behind when the orval bin has moved from `/lib` to `/dist`
=> fix: fix the orval bin path in sample projects

src/core/generators/react-query.ts
**READY**
Fixes little bug here: https://github.com/anymaniax/orval/issues/132#issuecomment-846464157
> this line produces incorrect code if definition is undefined
https://github.com/anymaniax/orval/blob/master/src/core/generators/react-query.ts#L82
=> Fix of undefined case of definition in react-query.ts

src/core/getters/object.ts
**READY**
Setting each property of an object with `additionalProperties: true` to have `object` type is wrong. It enforces all other properties to have the object type.   
I've changed it to `any`.
```ts
{
type: 'object'
properties: {
foo: string;
}
additionalProperties: true;
}
```
For the above schema output would be.
```ts
interface ObjectWithAdditionalProps {
foo: string; // typescript error: Property 'foo' of type 'string' is not assignable to string index type 'object'
[key: string]: object;
}
```
I used any as there is no way to predict what types would a user use in their additional properties.
```ts
interface ObjectWithAdditionalProps {
foo: string;
[key: string]: any;
}
```
@anymaniax
=> fix: additional properties of the objects should have any type

src/core/generators/formData.ts
All falsey values are skipped from being appended to the formData due to check that isn't strict enough. We just need to generate code that checks for undefined instead. So the code generated goes from:
```
if (filePostBodyBody.compress) {
formData.append('compress', filePostBodyBody.compress.toString());
}
```
to 
```
if (filePostBodyBody.compress === undefined) {
formData.append('compress', filePostBodyBody.compress.toString());
}
```
branch | PR
```bash
```
1.
=> Fix falsey formData values being skipped

docs/src/pages/guides/angular.md, docs/src/pages/overview.md
This fixes the link to configuration on Guides/Angular page. The current link leads to a 404 page.
=> Fix the link to configuration

src/core/getters/enum.ts
**READY**
Deduplicate enum values by using a `Set`.
I'm not sure if this PR is OK since the problem is also because the OpenAPI schema is not "right".
=> fix: deduplicate enum values

src/types/index.ts
**READY**
- It would be nice to expose the types for the transformer function, so we get proper type-checking if your transformer file is written in TypeScript.
```ts
// transformers/add-version.ts
import type { InputTransformerFn } from "orval";
const addVersion: InputTransformerFn = (inputSchema) => ...
export default addVersion;
```
=> feat(types): Export transformer function type

src/core/writers/specs.ts
**READY**
When using `workspaces` and `tags-split` mode, discovered that the generated `index.ts` file was constantly being modified by prettier husky hooks - remove/add a newline at EOF.
Discovered that `index.ts` wasn't included to be fixed by `prettier`.
From [67e583](https://github.com/anymaniax/orval/commit/67e583e9eee1593d866f5740cd11169e7fb02f2e) with the following config.
```
'test-api': {
input: {
target: './src/api/test-api.spec.json',
},
output: {
mode: 'tags-split',
workspace: 'src/api/test-api',
target: './test-api.ts',
prettier: true,
},
}
```
=> fix(writers): include workspace index.ts to be formatted using prettier

docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/output.md, src/bin/orval.ts, src/core/generators/interface.ts, src/core/importers/openApi.ts, src/index.ts, src/types/index.ts, src/utils/options.ts, tests/configs/default.config.ts, tests/specifications/petstore.yaml
**READY**
Specify `tslint` (deprecated) as linter instead of default `eslint` to manage typescript.
Empty interface is the only linter entrypoint at the moment but it has a real impact regarding some externally written API definitions.
- `--tslint` cli option
- `tslint: true` in global configuration
- `output.tslint: true` in specific configuration
Cf. tests/specifications/petstore.yaml
=> feat(linter) ESlint as default linter w/ TSlint as optional switch

src/core/generators/query.ts, tests/configs/react-query.config.ts
**READY**
When generating React Hooks containing forms data, the generated file wouldn't compile.
1.
```bash
> git fetch --all
> git checkout fix-use-custom-instance-with-form
> yarn; yarn build
> cd tests
> yarn; yarn generate
```
2. Check `tests/generated/react-query/formDataWithHook/endpoints.ts`
=> fix(generators): fixed generation when using hooks and forms

src/core/getters/params.ts, tests/configs/default.config.ts, tests/specifications/parameters.yaml
**READY**
Default string values were rendered without quotes.
Before:
```typescript
export const listPetsByCountry = <TData = AxiosResponse<Pets>>(
params?: ListPetsByCountryParams,
country = UY, // <---
options?: AxiosRequestConfig,
): Promise<TData> => {
return axios.get(`/pets-by-country/${country}`, {
params,
...options,
});
};
```
After:
```typescript
export const listPetsByCountry = <TData = AxiosResponse<Pets>>(
params?: ListPetsByCountryParams,
country = 'UY', // <---
options?: AxiosRequestConfig,
): Promise<TData> => {
return axios.get(`/pets-by-country/${country}`, {
params,
...options,
});
};
```
I implemented it in a separate function so that it can be expanded if other types need special formatting.
The tests cover strings (as enums) and integers and use a separate …
=> fix(core): path parameters default values

src/utils/string.ts, tests/configs/default.config.ts, tests/specifications/translation.yaml
**READY**
The goal is to allow the dot character in paths. For example when loading a file
```bash
yarn build && cd tests/ && yarn generate:default && cd ..
```
=> fix(sanitize): allow `.` character in paths

src/constants/index.ts, src/core/generators/axios.ts, src/core/getters/parameters.ts, src/utils/async-reduce.ts, src/utils/debug.ts
=> fix(types): remove generic from axios query function generator

samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, src/core/generators/axios.ts
Ooops, the opening bracket were lost in `src/core/generators/axios.ts` file. Fix this.
=> fix(types): remove generic from axios query function generator (#284)

src/core/getters/enum.ts, src/utils/string.ts, tests/specifications/petstore.yaml
**READY**
This PR fixes generated TS code when an enum contains a dash. Example of usage will be query param `sort`: 
```yaml
paths:
/pets:
get:
summary: List all pets
operationId: listPets
tags:
- pets
parameters:
- name: limit
in: query
description: How many items to return at one time (max 100)
required: false
schema:
type: string
- name: sort
in: query
description: |
Which property to sort by?
Example: name sorts ASC while -name sorts DESC.
required: false
schema:
type: string
enum:
- name
- -name
- email
- -email
```
```ts
export const ListPetsSort = {
name: 'name' as ListPetsSort,
name: '-name' as ListPetsSort, // Note the duplicated key
email: 'email' as ListPetsSort,
email: '-email' as ListPetsSort, // Note the duplicated key
};
```
```ts
export const ListPetsSort = {
name: 'name' …
```
=> fix(getters): enum can contain dashes

src/core/generators/swr.ts
**READY**
Fixes an issue where swr generated code was incompatible with this eslint config:
```js
{
parser: '@typescript-eslint/parser',
extends: ['plugin:@typescript-eslint/recommended', 'plugin:prettier/recommended', 'prettier'],
rules: {
semi: ['error', 'never'],
},
}
```
We where using eslint 8.7.0 which produced the following error when running eslint on code:
```
/driftiCoreAPI.ts
152:37  error  Parsing error: '>' expected
✖ 1 problem (1 error, 0 warnings)
```
If I removed `semi: ['error', 'never'],` it worked fine 🤔 
Generated code which eslint complained about was:
```ts
export const useGetAccount = <TError = GetAccount422 | GetAccount4xx | GetAccount5xx>(
options?: { swr?:SWRConfiguration<AsyncReturnType<typeof getAccount>, TError> & {swrKey: Key}, request?: …
```
=> fix(generators): swr compatible with eslint "semi: error" rule

src/core/generators/verbsOptions.ts, src/core/getters/body.ts, src/core/getters/response.ts
**READY**
Close  #311 since that  was actually a bug with `operationName` config.
=> fix(config): fix operationName bug not changing models naming

src/core/generators/verbsOptions.ts, src/types/esutils.d.ts
**READY**
Fixes any ES5 keyword that may be an operationName like `delete` becomes `_delete`
=> fix(server): fix operation names using ES5 keywords

src/core/getters/object.ts
**READY**
When passing `additionalProperties` along with `properties`, the first is not taken into account due to an early return for `properties`
So, using a schema like
```json
{
"type": "object",
"additionalProperties": false,
"required": ["data"],
"properties": {
"data": {
"type": "object",
"additionalProperties": {
"type": "array",
"items": {
"type": "string"
}
},
"properties": {
"base": {
"type": "array",
"items": {
"type": "string"
}
}
}
}
}
}
```
is currently resulting to the type:
```ts
export type DemoTypeData = {
base?: string[]
}
export type DemoType = {
data: DemoTypeData
}
```
instead of 
```ts
export type DemoTypeData = {
base?: string[]
} & { [key: string]: string[] }
export type DemoType = {
data: DemoTypeData
}
```
This PR fixes that issue.
=> fix(getters): allow object additional properties along with properties

src/core/generators/schemaDefinition.ts
**READY**
Fix #321 
Instead of generating an empty type like...
```ts
export type Health200 = {};
```
it generates it as an ANY
```ts
export type Health200 = any;
```
@CPatchane @anymaniax Can you review this it looks to me like the first `if` and the last `else` were doing the exact same thing so I simplified the logic "I think".
=> fix(schema): generate 'any' instead of '{}'

src/core/generators/angular.ts, src/core/generators/axios.ts, src/core/generators/client.ts, src/core/generators/query.ts, src/core/generators/swr.ts, src/core/writers/target.ts, src/core/writers/targetTags.ts, src/types/generator.ts
**READY**
When dealing with hooks generated using `react-query`, it's currently difficult to get the actual return types from the queries (not those from the schemas).
In a case where we process the data from the API (changing the case for example) using a custom client, we can't directly rely on the schemas types that have been generated, we have to get the response type from the queries generated instead.
This PR exported those new types for each functions in order to use them in components that used data from those, looking like:
```typescript
export type GetDemoQueryResult = NonNullable<AsyncReturnType<typeof getDemo>>
export type GetDemoQueryError = ErrorType<GetDemo400>
// Then we can use like
type MyComponentPropsType = {
foo: GetDemoQueryResult["foo"]
bar: …
```
=> feat(query): generate query return type along with hooks

samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, src/core/generators/query.ts
**READY**
The mutation body type definition using `BodyType` wasn't working correctly due to a miss for `*MutationBody` types and a wrong replacement.
=> fix(query): fix the mutation body using BodyType wrongly replaced

docs/src/pages/reference/configuration/output.md
Update documentation related to Angular-specific configuration option: `provideIn`.
I noticed that the documentation related to `provideInRoot` was a bit outdated, here's my first attempt to fix that.
=> docs(configuration): update

src/core/generators/axios.ts, src/core/generators/client.ts, src/core/writers/target.ts, src/core/writers/targetTags.ts, src/types/generator.ts
**READY**
If a custom mutator function returns a non-promise, `AsyncReturnType` breaks.
This removes `AsyncReturnType` and just uses `Awaited<ReturnType<>>` in its place which:
- Doesn't break with sync functions
- Relies on internal Typescript functionality, and thus should be more stable
Additionally the footer generation function no longer needs `hasMutator` so it has been removed.
This was built off of v6.7.1 so I could test locally as `master` had issues with generating my output.
=> Replace AsyncReturnType with Awaited<ReturnType<>>

src/core/generators/msw.ts, src/core/getters/combine.mock.ts, src/core/getters/object.mock.ts, src/core/getters/scalar.mock.ts, src/core/resolvers/value.mock.ts
**READY**
This PR introduces two commits:
- replace the now-deprecated `faker.helpers.randomize` (which logs an error when used) with `faker.random.arrayElement`
- simplify the logic for lists of enums using `faker.random.arrayElements` (see here: https://fakerjs.dev/api/random.html#arrayElements)
These changes do not introduce any new logic so existing tests should be sufficient.
Note: I deliberately did not update the samples and readme to use faker.random.arrayElement but can do so as well.
=> Simplify generated code for MSW

src/index.ts
**READY**
When defining `orval.config.ts`, it's possible to pass `OutputClientFunc` for the `output.client`.
However, defining a client as a function doesn't bring any value to the user-developer as of now.
- since `orval` doesn't expose `core` functions, the user-developer is required to rewrite all core functions of `orval` to customize parts of it
We probably should expose all of the core API for the user, but in this PR, I'm exposing only the parts that are necessary to customize `axios` and `axios-functions` clients.
This PR's changes would allow to create a custom `generateAxiosImplementation` and `generateAxios` (and possibly generators for other clients), which in turn would let to have a customization for the user.
For my personal use-case, I would be able to then modify …
=> feat: expose api necessary to create `generators`' overrides

docs/src/pages/guides/custom-axios.md
Specify the usage of adding second `options` argument in custom axios instance. See https://github.com/anymaniax/orval/issues/282 and https://github.com/anymaniax/orval/issues/379
**READY**
Update docs
fix #379
=> docs: update custom-axios.md

src/core/getters/scalar.mock.ts
**READY**
This addresses the 2nd part in #342. The first issue in #342 was already addressed by #366.
"2nd part" refers to this:
```
{ values: [], enums: Object.values(name) }, // javascript error
```
=> fix(mocks): fix array enum mock generation when enum is NOT a $ref

src/core/resolvers/ref.ts
**READY**
resolveRef expect as input one of the following options:
```js
{ '$ref': '#/components/schemas/Error' }
```
```js
{ type: 'array', items: { '$ref': '#/components/schemas/Pet' } }
```
```js
{
type: 'object',
required: [ 'id', 'name' ],
properties: {
'@id': { type: 'string', format: 'iri-reference' },
id: { type: 'integer', format: 'int64' },
name: { type: 'string' },
tag: { type: 'string' },
email: { type: 'string', format: 'email' },
callingCode: { type: 'string', enum: [Array] },
country: { type: 'string', enum: [Array] }
}
}
```
But it's possible for a schema to reference another schema (alias)
```js
{
name: 'fileType',
in: 'path',
description: 'the file type of verifications Identity.',
required: …
```
=> fix(resolvers): fix generating schema for alias object

src/core/generators/axios.ts
**READY**
When using a custom Axios client that has a 2nd argument, there is a missing comma that breaks the generated code. See screenshot below. This bug was introduced with PR #357.
This PR updates the axios generator with the missing comma, matching this similar line in the query generator: https://github.com/anymaniax/orval/blob/d63d4c313202aa0d3442d899b17d36907c11747a/src/core/generators/query.ts#L211
branch | PR
[feature/add-query-cancellation](https://github.com/anymaniax/orval/tree/feature/add-query-cancellation) | [link](https://github.com/anymaniax/orval/pull/357)
=> fix(generator): fix missing comma in axios generator when mutator has 2nd arg

docs/src/pages/reference/configuration/output.md, src/core/generators/interface.ts, src/types/index.ts
**READY**
The goal of this PR is to allow types to be used instead of interfaces when generating objects.
=> feat(config): allow types to be used instead of interfaces

src/core/resolvers/value.mock.ts, tests/configs/react-query.config.ts, tests/specifications/import-from-subdirectory/petstore.yaml, tests/specifications/import-from-subdirectory/subdirectory/petstore.yaml
**READY**
When running Orval with:
- react-query
- mocks
- referencing a schema in a subdirectory in a `oneOf`
the generation would break, since if would create a `specKey` with the wrong path. The `specKey` would reference the subdirectory twice (eg: `..path/directory/directory/file.yaml` instead of `..path/directory/file.yaml`).
I copied how `getRefInfo` was called in other places in the code, this solved the issue.
Also added a minimal test (which breaks on master and passes on this branch) to explain the issue.
In order to run the failing test:
```bash
> git checkout fix/correctly-resolve-paths-when-generating-mocks^1
> yarn build
> cd tests
> yarn
> yarn generate
```
=> Fix: correctly resolve paths when generating mocks with oneOf

src/core/getters/scalar.mock.ts
READY 
When creating an array over `[...Array(N)].map()` sometimes nothing is returned. See here for details: https://stackoverflow.com/a/35086350/178980
The gist of it is the array needs to be filled with something first.
```bash
```
1.
=> Fill in array values

src/core/getters/scalar.mock.ts
Problem: When a user specifies a minimum and/or maximum value for a property of type `number` or `integer`, these values are not passed to the faker function that generates the number in the mock api files, and thus the mock returns values that are not wanted.
This change addresses that issue.
Example:
This specification in the swagger doc:
Will lead to this in the mock api file:
If no minimum or maximum is provided, those values will be passed as `undefined` in the faker function
[which will lead to the same default behavior before this change, of returning a random number between 0 and 99999.](https://fakerjs.dev/api/datatype.html#number)
=> added min and max so user can specifiy from swagger doc

src/core/generators/msw.ts, src/types/index.ts
**READY**
Change from logical or to the nullish coalescing operator, in order that 0 is a valid value.
`undefined || 1000` -> `1000`
`0 || 1000` -> `1000`
`undefined ?? 1000` -> `1000`
`0 ?? 1000` -> `0`
=> fix: msw mock delay time

docs/src/pages/reference/configuration/output.md
**READY**
Currently the word should is misspelt [here](https://orval.dev/reference/configuration/output#transformer)
Just removing an extra `e` from the word `shouled`
1. it's pretty straight forward, the diff should explain itself
=> docs: fix typo

src/core/getters/combine.mock.ts, tests/configs/react-query.config.ts, tests/specifications/polymorphic.yaml
**READY**
(Sorry, didn't mean to pollute your repo, I've never really played around with the fork/pr flow and I managed to break things)
Fixes #555 - When a response contains a polymorphic type, the generated mock object code was missing curly braces. This error was introduced in https://github.com/anymaniax/orval/commit/899a8cbd4c93190bd01ebd5e36be81d750b7608f.
Previously, when calling `resolveMockValue` within a `oneOf`, the `combine` option was undefined. The change resulted in the option being defined, resulting in a failing check for object boundaries.
This fix adds a check for `(combine.separator === 'oneOf' && separator === 'allOf')` when determining object boundaries.
I've also run all the tests, and to be sure I also diffed the tests before and after the fix and can confirm that …
=> fix(msw): generated mocks for polymorphic type

src/core/getters/array.ts, tests/configs/default.config.ts, tests/regressions/arrays.ts, tests/specifications/regressions.yaml, tests/tsconfig.json
**READY**
The code generator for arrays outputs ambiguous types, and breaks for nullable array items. 
Currently, the generated code looks like: `string | null[]`
This is interpreted as "string or an array of null", which is incorrect.
With this fix, the generated code is: `(string | null)[]`
This change wraps _all_ array types in parenthesis (`()`). This is not necessarily needed for a single type, but it causes no harm, avoids any ambiguity, and avoids the need for more complex changes to the code generator.
I also added a regression test that fails to compile without this fix. I didn't see an existing pattern for regression tests so I came up with something. Let me know if you'd prefer a different approach.
n/a
> **Note** See tests for complete example.
1. Create a schema like:
```yaml …
```
=> fix(code): generated code for arrays with nullable items

docs/src/pages/reference/configuration/output.md
Currently there is no delay options in Orval.dev docs
Just a docs update so it's pretty staightforward
=> docs: add delay options

src/core/getters/object.ts, src/core/getters/scalar.ts, tests/configs/default.config.ts, tests/specifications/null-type.yaml, yarn.lock
READY
In OpenAPI 3.1, the `nullable` keyword has been removed, and nullability is handled by `oneOf`, `anyOf` or type arrays: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
Currently, Orval does not support this, with nullable types ending up as `unknown` (for type arrays) or e.g. `string | unknown` (for oneOf/anyOf).
This PR adds support both for `oneOf`, `anyOf` and type arrays:
```yaml
components:
schemas:
NullableObject:
type: object
properties:
name:
type:
- 'string'
- 'null'
age:
anyOf:
- type: 'integer'
- type: 'null'
address:
oneOf:
- type: 'string'
- type: 'null'
```
Resulting in:
```ts
export interface NullableObject {
name?: NullableObjectName
age?: NullableObjectAge
address?: NullableObjectAddress
}
export type NullableObjectAddress = string | …
```
=> fix(getters): handle OpenAPI 3.1 nullability

docs/package.json, docs/src/pages/reference/configuration/output.md
**READY**
There is error that starting docs is not working when node version is over 16. 
https://github.com/webpack/webpack/issues/15900
It could be resolved by updating librarys in docs folder, but it would be too large and may not be the way all contributor wants.  So just update package.json file.
Mock options has same depth as mock itself so it is hard to recognize that it is property of mock without looking at example. So fixed it according to https://github.com/anymaniax/orval/blob/68f84a8b49a78e19b45c4623b2f659b2f2d0481d/packages/core/src/types.ts#L59
AS_IS
TO_BE
check deployed docs.
=> docs: fix position of mock options

packages/core/src/getters/query-params.test.ts, packages/core/src/getters/query-params.ts
**READY**
Use parameter descriptions to document the types
https://github.com/anymaniax/orval/blob/ba7ee988557a63c392c6d9bee50bbd7eddfe3b86/samples/react-app/petstore.yaml#L16-L22
```diff
- export type ListPetsParams = { limit?: string };
+ export type ListPetsParams = {
+ /**
+  * How many items to return at one time (max 100)
+  */
+ limit?: string;
+ };
```
=> fix(jsdoc): add jsDoc to query parameters

packages/msw/src/getters/combine.ts, packages/msw/src/getters/object.ts, packages/msw/src/getters/scalar.ts
**READY**
This PR aims to fix the msw package by handling properly "anyOf" types (see the related issue: #755). 
Try to generate msw with an object with the following property type :
```json
"propertyAnyOf":{
"type":"array",
"items":{
"type":"object",
"properties":{
"id":{
"type":"string",
"transform":["trim"]
},
"value":{"anyOf":[{"type":"array","items":{"type":"string","transform":["trim"]}},{"type":"object","properties":{},"additionalProperties":true},{"type":"boolean"},{"type":"number"},{"type":"string","transform":["trim"]},{"type":"null"}]}
```
2 problems occured before :
* Brackets were always added leading to types such :
```typescript
faker.helpers.arrayElement([ { Array.from(....) } ])
```
instead of :
```typescript
faker.helpers.arrayElement([ { Array.from(....) } ])
```
* …
=> 🐛 Fix anyOf mocks generation (msw)

docs/src/pages/reference/configuration/input.md, packages/core/src/generators/verbs-options.ts, packages/core/src/types.ts, packages/orval/src/api.ts, packages/orval/src/import-open-api.ts, packages/orval/src/utils/options.ts
In the case orval is run on a system with a lot of endpoints, it can be useful to limit which endpoints are actually generated.
**READY**
In the case orval is run on a system with a lot of endpoints, 
it can be useful to limit which endpoints are actually generated.
See: #739 
1. Add a tag that should be filtered out to a orval.config for instance as follows:
```
output: {
filterTags: ["pets"]
},
```
2. Only end points that contain tag "pets" will be generated.
=> feat(packages): add option to filter generated endpoints

packages/query/src/index.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
Add a new exported function for query and mutator options for each operator.
With it, you can easily use them to do something like the following code for example
```ts
const queryClient = useQueryClient();
queryClient.prefetchQuery(getOperationNameQueryOptions(Args))
```
=> feat(query): generate query and mutation options functions

packages/core/src/getters/scalar.ts
**READY**
There are two types of integers supported in OpenAPI spec: `int32` and `int64`. The current version of `orval`, however, converts all those integers to js `number` and doesn't consider `int64` types as `bigint`.
Check the type of the integer and use `bigint` instead of `number` if it is an `int64`.
Closes #824.
=> fix(core): use `bigint` for `int64` types

packages/core/src/getters/scalar.ts, packages/core/src/types.ts
**READY**
The recent change from to add support for bigints caused issues in frontend code, as commented [here](https://github.com/anymaniax/orval/issues/824)
So, in this PR, I just added an optional field called `useNumberTypeForBigInt` that when true, forces the typing to always be number, instead of bigint.
=> feat(core): add optional flag to force number type instead of bigint

packages/zod/src/index.ts
**READY**
Orval's zod generator will output `optional` even if `nullable: true` is set.
I fixed it to output `nullable` or `nullish` by the conditions.
| feature_client_zod | [link](https://github.com/anymaniax/orval/pull/785) |
=> feat(zod): Add nullable & nullish to zod output

packages/core/src/getters/response.ts, tests/configs/default.config.ts, tests/specifications/default-status.yaml
**READY**
As an open API specification, we can utilize the default key as the key for the Responses Object. This serves as a fallback response for any uncovered HTTP status codes.
I have made modifications to consider the specified default response: if there are no success/error responses, the generator will treat the default response as a success/error response.
This behavior aligns with that of the @openapitools/openapi-generator-cli.
No related PR.
I added new testcase: `default-status.yaml`.
Please run `cd test && yarn generate` and check `tests/generated/default/default-status/endpoints.ts`.
=> fix(core): use default response object as success/error response

docs/src/pages/reference/configuration/output.md
**READY**
Corrected link to VerbOptions in the output transformer in the configuration documentation.
```bash
```
1.
=> fix(page): replaced VerbOptions's link

packages/zod/src/index.ts
**READY**
The build on master seems to be failing
```
Error: Cannot find module '@orval/core/src'
Require stack:
- /home/runner/work/orval/orval/packages/zod/dist/index.js
- /home/runner/work/orval/orval/packages/orval/dist/chunk-RRNAJ36V.js
- /home/runner/work/orval/orval/packages/orval/dist/bin/orval.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
at Function.Module._load (node:internal/modules/cjs/loader:873:27)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/home/runner/work/orval/orval/packages/zod/dist/index.js:1:313)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
at …
```
=> fix: correct `jsStringEscape` import

packages/core/src/getters/scalar.ts, tests/specifications/null-type.yaml
**READY**
Following the [specification](https://swagger.io/docs/specification/data-models/enums/), a nullable enum needs to have `nullable: true` **and** `null` in its values.
When it's the case, Orval generates a bad TS enum. For instance:
```ts
export const NullEnum = {
null: 'null',
null: null,
} as const;
```
This PR fixes it.
=> fix: filter null from enum values

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/msw/src/index.ts
**READY**
This adds the possibility to override MSW mocks with a dynamic delay using a function that returns a number, making API calls more similar to real-world ones, where responses can potentially come back at different times:
```js
{
// ... other options ...
override: {
mock: {
delay: () => { ... }
}
}
}
```
This change is backwards compatible and the previous default value has been maintained.
=> feat(msw): allow mock delay override via function

packages/zod/src/index.ts
**WIP**
* Fix array of objects (consts were not added to output)
* Fix date validation (should allow YYYY-MM-DD according to OpenAPI spec)
* Don't create const for string min length 1 (this is commonly used to require non-empty strings and generates excessive code)
N/A
TODO: Adding tests
=> fix(zod): better handling for arrays, dates, min

packages/core/src/utils/case.test.ts, packages/core/src/utils/case.ts
Fixes #948. Simply replacing the `pascal` function because it is a bottleneck.
I added some test cases to make sure we don't break anything, do not hesitate to tell me if I missed something.
Don't take my word for it, here's a demo:
https://www.loom.com/share/0f822963b55542d8998077ce75252068
https://github.com/anymaniax/orval/assets/46993939/c4472624-77b8-485d-932a-8b85e79a9c28
=> 2x faster code generation

docs/src/pages/reference/configuration/output.md, packages/msw/src/resolvers/value.ts
**READY**
Resolves #938.
Allows path regex comparison for mock properties, making it possible for nested properties to be overriden across multiple endpoints.
This could previously be achieved by overriding the parent property, but that required manually mocking all of the parent's properties. Another possibility was to override the child property directly, but this could cause issues if the value had to be different depending on it's parents.
=> feat(msw): allow regex for entire paths instead of only property names

docs/src/pages/guides/set-base-url.md, packages/core/src/types.ts, packages/orval/src/api.ts, packages/orval/src/utils/options.ts
**READY**
Resolves #865.
Allows `baseUrl` configuration directly via Orval. Previous configuration methods still work, so no breaking changes.
`baseUrl` can be defined under `output` for each OpenAPI specification, allowing urls to be different without the need for multiple custom client instances.
=> feat(orval): allow custom baseUrl for each OpenAPI specification

packages/core/src/generators/verbs-options.ts, packages/core/src/getters/props.ts
**READY**
This feature was using `operationId` to construct the `PathParameters` name. For consistency, it would be better to use `operationName` as it can be mapped to something by users.
```bash
```
1.
=> fix(useNamedParameters): use operationName instead of operationId

packages/core/src/getters/object.ts, tests/configs/default.config.ts, tests/specifications/null-type-v3-0.yaml
Fix #981
**READY**
`| null` was missing for nullable objects without properties
```yaml
NullableAnyObject:
type: object
nullable: true
```
got translated to
```ts
export type NullableAnyObject = { [key: string]: any }; // <<-- missing ` | null`
```
I added new test specification with described case - `null-type-v3-0.yaml`
=> fix: Nullable Object type

docs/src/pages/reference/configuration/output.md, packages/angular/src/index.ts, packages/axios/src/index.ts, packages/core/src/generators/options.ts, packages/core/src/generators/verbs-options.ts, packages/core/src/types.ts, packages/core/src/writers/single-mode.ts, packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts, packages/core/src/writers/target-tags.ts, packages/core/src/writers/target.ts, packages/orval/src/client.ts, packages/orval/src/utils/options.ts, packages/query/src/index.ts, packages/swr/src/index.ts
**READY**
Resolves #296 .
Adds support for axios' `paramsSerializer`. This can be used to adapt the format of arrays and other properties to the API's requirements.
Adds a `paramsSerializer` property, which behaves as other mutators, allowing for any custom params serializer. Also adds a `paramsSerializerOptions`, to use `qs` directly, where users only have to define the `options` that will be passed.
=> feat: support params serializer

docs/src/pages/reference/configuration/output.md, packages/core/src/getters/array.ts, packages/core/src/getters/combine.ts, packages/core/src/getters/object.ts, packages/core/src/getters/res-req-types.ts, packages/core/src/getters/scalar.ts, packages/core/src/resolvers/ref.ts, packages/core/src/types.ts, packages/msw/src/getters/scalar.ts, packages/msw/src/mocks.ts
**READY**
Resolves #922.
Adds support for OpenAPI's example and examples fields to be used as MSW values. Handles example refs, as well as every variation of the example/examples fields described in [the docs](https://swagger.io/docs/specification/adding-examples/).
=> feat(msw): support using OpenAPI example/examples fields as MSW values

docs/src/pages/reference/configuration/full-example.md, docs/src/pages/reference/configuration/output.md, packages/msw/src/getters/scalar.ts, samples/angular-app/orval.config.ts, samples/angular-app/src/api/endpoints/pets/pets.msw.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/basic/orval.config.ts, samples/nx-fastify-react/apps/api/src/main.ts, samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app/orval.config.ts, samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/svelte-query/orval.config.ts, samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
**READY**
Faker v8 has [deprecated a few methods](https://fakerjs.dev/guide/upgrading.html#deprecations-and-other-changes). Most of them were already updated in #978 , but arrays were still using `faker.datatype.number`. This PR fixes that, as well as deprecated uses found in the documentation and samples.
=> feat(faker): update deprecated methods

packages/angular/package.json, packages/axios/package.json, packages/core/package.json, packages/msw/package.json, packages/orval/package.json, packages/query/package.json, packages/swr/package.json, packages/zod/package.json
**READY**
Resolves #964 
There's no need to minify the code, since Orval is only used as a dev dependency and never at runtime. I've also disabled `splitting` as it generates extra files that constantly change between versions, which can make debugging harder.
=> feat: disable minification

packages/core/src/getters/discriminators.ts
**READY**
When Orval is configured to use a suffix in schemas, like
```
output: {
override: {
components: {
schemas: {
suffix: 'Schema'
}
}
}
}
```
discriminators are not well resolved.
The reason is that discriminators are resolved before renaming the schemas, but using `getRefInfo` will return a name that includes the suffix. As a consequence, the schema will not be found in `transformedSchemas` and the generated code will not include the property name for the discriminator.
=> Don't use name with suffix when resolving discriminators

packages/core/src/utils/assertion.ts
**READY**
In this [commit](https://github.com/anymaniax/orval/commit/11e5dc96901f7a17634f1abc7ae0bafe0407dd0b), `require_tld` usage was removed in favor of a regex. I'm not sure why, but it creates issue with URLs like this one: `http://my-docker-service/docs.json`, which are not recognized.
List related PRs against other branches: N/A
N/A
=> fix: use require_tld instead of regex

packages/msw/src/getters/object.ts
**READY**
Fixed the faker object keys for generation to not be wrapped in quotes anymore. 
#980
=> fix(msw): faker object keys no longer in quotes

packages/msw/src/getters/object.ts, packages/msw/src/getters/scalar.ts
**READY**
When a non-ref (non-importable) enum exists for the MSW generators, we now add an `as const` to enforce constant type handling here. Also added comments explaining this logic.
Fixes #960
=> Fix(MSW):non ref enum const

packages/msw/src/getters/combine.ts, packages/msw/src/getters/object.ts, packages/msw/src/getters/scalar.ts, packages/msw/src/mocks.ts, packages/msw/src/resolvers/value.ts
**READY**
Fix #910
Fix #764 
Added an explicit `existingRecursiveProperties` flag to account for if the recursive property has been accounted for already - to prevent infinite looping (which is what the old fix did, but had this bug as well).
This openapi schema will generate this MSW now.
```yaml
openapi: "3.0.0"
info:
version: 1.0.0
title: Swagger Petstore
license:
name: MIT
servers:
- url: http://petstore.swagger.io/v1
paths:
/pets/{petId}:
get:
summary: Info for a specific pet
operationId: showPetById
parameters:
- name: petId
in: path
required: true
description: The id of the pet to retrieve
schema:
type: string
responses:
"200":
description: Expected response to a valid request
content:
schema:
$ref: "#/components/schemas/Pet"
components:
schemas:
Pet:
type: object …
```
=> fix(MSW): accounted for properties with the same name

packages/core/src/generators/options.ts, packages/core/src/utils/assertion.ts, tests/mutators/custom-client.ts
Fix #888 
Bare minimum change and least invasive to uppercase the Axios method like...
```js
method: 'GET'
```
=> fix: uppercase method verbs

packages/core/package.json, packages/core/src/utils/assertion.test.ts, packages/core/src/utils/assertion.ts
Improves on #920 and adds unit tests
Ensures that new scenario and old scenarios are still all working so we don't keep breaking this.
according to Snyk this is the correct way to detect a URL: https://snyk.io/blog/secure-javascript-url-validation/
=> fix: improve isurl regex

packages/core/src/generators/mutator.ts, packages/core/src/utils/assertion.ts
**READY*
Strips comments out of mutator file before processing.
Fix #673 
Regex101: https://regex101.com/r/P77HnT/1
=> fix(axios): ignore commented out lines

packages/core/package.json, packages/zod/package.json, packages/zod/src/index.ts, tests/configs/zod.config.ts, tests/specifications/arrays.yaml
**READY**
This should fix #1027. The zod function that concatenated consts while parsing the properties of schemas was able to handle multiple properties (eg. `min:2, max:5`) only on objects, but not arrays. This code checks if there are multiple consts and concatenates them intelligently depending on it being either a single string or an array of strings.
```bash
> cd tests
> yarn run generate:zod
```
1. Look at the file `tests/generated/zod/nestedArrays.ts
2. The file should not contain any extra commas that cause a typescript parsing error.
=> fix[zod]: enable multiple properties of array consts

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/zod/package.json, packages/zod/src/index.ts, packages/zod/src/zod.test.ts, tests/configs/zod-parameters.config.ts, tests/package.json, tests/specifications/parameters.yaml
**READY**
Fix #961 I expressed a desire to make the generated zod schema for endpoint query parameters more useful for parsing and validating `URLSearchParams` by making use of zod's type-coercion. It turns out that part of this problem isn't easily solvable within this library's generated code (more on that below), but the part that is ended up being relatively simple to add.
This PR is one possible (relatively naive) approach to how that might work.
- adds a new `override.coerceTypes` boolean flag to the output config
- when enabled, the zod codegen will emit e.g. `zod.coerce.string()` instead of `zod.string()`
- this only applies only to coerce-able types (string, number, boolean, bigint, date)
- this _will_ apply to nested schemas, and I'm not sure that's _always_ the correct thing to …
=> Add option to enable Zod type coercion for query params

packages/zod/src/index.ts, tests/specifications/circular.yaml
Fix #933
This YAML
```yaml
/list:
post:
summary: Add list
operationId: add-list
responses:
'200':
description: OK
requestBody:
content:
schema:
type: object
properties:
list:
type: array
minItems: 1
maxItems: 10
items:
type: number
minimum: 1
maximum: 10
required:
- list
```
gets generated properly as this
```js
export const addListBodyListMax2 = 10;
export const addListBodyListMax1 = 10;
export const addListBody = zod.object({
"list": zod.array(zod.number().min(1).max(addListBodyListMax1)).min(1).max(addListBodyListMax2)
})
```
=> fix(zod): array min max issues

docs/src/pages/reference/configuration/output.md, packages/core/src/generators/schema-definition.ts, packages/core/src/getters/enum.ts, packages/core/src/getters/query-params.ts, packages/core/src/resolvers/object.ts, packages/core/src/types.ts, packages/orval/src/utils/options.ts
**READY**
Fix #907
As requested in issue #907 this PR adds a new optional configuration parameter to generate native Typescript enums.
The new parameter `useNativeEnums` is set in the `output.override` configuration block and when set to `true` (defaults to `false`) Orval will generate a native Typescript `enum` instead of the `type` and `const` combo.
=> feat: add optional configuration parameter to generate native Typescript enums

.vscode/settings.json, packages/query/src/index.ts, samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/vue-query/src/components/pet.vue, samples/vue-query/src/components/tests/path-parameter-reactivity-pet.spec.ts, samples/vue-query/src/components/tests/path-parameter-reactivity-pet.vue, samples/vue-query/src/components/tests/query-enabled-reactivity-pet-id.spec.ts, samples/vue-query/src/components/tests/query-enabled-reactivity-pet-id.vue, samples/vue-query/src/components/tests/query-enabled-reactivity-version.spec.ts, samples/vue-query/src/components/tests/query-enabled-reactivity-version.vue
**READY**
Ensures that query `enabled` option is reactive (disabled when parameters are falsy).
Will fix #943 
Based on https://github.com/anymaniax/orval/pull/944, @bengane my colleague agreed for me to take it over.
Test included, to rebuild all and run all tests use this:
```
yarn && yarn build && yarn update-samples && yarn format && yarn test:ci && cd tests && yarn && yarn generate && yarn build && cd ..
```
=> fix(query): enabled reactivity fix (new)

packages/core/src/utils/string.ts, tests/configs/default.config.ts, tests/specifications/null-type-v3-0.yaml
Ready
Fix #1082 
Enum can be optional within openAPI 3.0.0. This PR adds support for optional enum and mocks. [https://swagger.io/docs/specification/data-models/enums/](https://swagger.io/docs/specification/data-models/enums/).
I added a mock option within the default configuration and included it with the used URL's. This PR contains a fix for the same problem.
=> fix: enum string escape can be nullable

packages/core/src/resolvers/object.ts, tests/configs/default.config.ts, tests/specifications/deeply-nested-refs.yaml
**READY**
Fix #967 
Fix #868
This may help to resolve the issue in #967.
The current implementation cannot process files with deep $ref nesting.
This PR contains changes to address deeply nested $refs.
- schema with many $refs call [combineSchemas](https://github.com/anymaniax/orval/blob/82b3b79ad67c1103fd60f2f16bcfae74555c0b71/packages/core/src/getters/combine.ts#L60) many times via [getObject](https://github.com/anymaniax/orval/blob/82b3b79ad67c1103fd60f2f16bcfae74555c0b71/packages/core/src/getters/object.ts#L14)
- [combineSchemas calls resolveObject in a loop](https://github.com/anymaniax/orval/blob/82b3b79ad67c1103fd60f2f16bcfae74555c0b71/packages/core/src/getters/combine.ts#L82-L87)
- Very many calls to resolveObject causes orval freeze
Changed to cache the result of resolveObject. …
=> fix: freeze problem when $ref is deeply nested

packages/query/src/index.ts
**READY**
Fix #1098
There was a bug that didn't allow the generation of strictly the Suspense query variants. i.e. it wouldn't generate anything if `useQuery: false` was passed
```js
module.exports = {
api: {
input: '../docs/swagger.json',
output: {
target: 'api.ts',
mode: 'split',
client: 'react-query',
override: {
query: {
useQuery: false,
useInfinite: false,
useSuspenseQuery: true,
useSuspenseInfiniteQuery: true,
},
},
workspace: 'src/api',
},
},
};
```
- Verified strictly `useSuspenseQuery` and `useSuspenseInfiniteQuery` hooks were generated
=> fix(query): suspense query generation

packages/core/src/writers/split-tags-mode.ts
**READY**
Fixes bad code generation when using `indexFiles: false`.
N/A
Run orval with a configuration like:
```js
{
mode: "tags-split",
target: "src/gen/endpoints/api.ts",
schemas: "src/gen/model",
indexFiles: false,
}
```
=> fix(core): use non-barrel schema file imports when using split-tags mode

packages/core/src/getters/combine.ts, samples/react-query/basic/src/api/model/dog.ts, samples/react-query/basic/src/api/model/pet.ts
closes #935
**READY**
Fixes TypeScript error when accessing a property from a union of objects with different schema.
Please refer to the provided example error in #935
Run locally to observe the generated types changed (now have missing properties declared as `missingProperty?: never` in:
- `samples/react-query/basic/src/api/model/dog.ts`
- `samples/react-query/basic/src/api/model/pet.ts`
<details>
<summary>Screenshots of the changes</summary>
</details>
=> fix(core): add missing properties in subschemas to fix TS error

docs/src/pages/reference/configuration/output.md
**READY**
I made two updates in the `output.client` description.
1. Add `swr` to valid values
`swr` can be specified for `output.client`. But the documentation didn't include it so I added it.
In addition, the options have been rearranged alphabetically.
See: https://github.com/anymaniax/orval/blob/master/packages/core/src/types.ts#L196-L205
1. Updated custom client generator description
Updated to fix broken links and change name of type.
none
PR is just document updates
=> docs: Update `output.client` description

packages/core/src/writers/split-tags-mode.ts
**READY**
Due to the changes in [this PR](https://github.com/anymaniax/orval/pull/1110), `barrel` is no longer used for `import` of `schema` files when the following conditions are met:
- `tags-split` is specified for `mode`
- specified `schemas`
It looks like you are expecting `barrel` to not be used for `import` of `schema` if `indexFiles` is `false`.
But, as a result, `barrel` is no longer used for `import` of `schema` files even if the value of `indexFiles` is `true`. Incidentally, by default the value of `indexFiles` is `true`.
I made a small change because if `indexFiles` is `true`, I want to use `barrel` for `import` as before.
1. Specify `false` for `indexFiles` in `orval.config.js` as shown below:
```json:orval.config.js
module.exports = {
'petstore-file': {
input: {
target: …
```
=> fix(core): Fixed condition for using `barrel` import in `split-tags` mode

docs/src/pages/reference/configuration/output.md
**READY**
I made the following changes to the `output.mode` document.
- Fixed some of the generated files that were different from the actual ones.
- Changed to specify the `mock` option in the input value so that the `mock` file is output.
- The `definition` file has been removed from the sample code as it does not produce any output.
none
PR is just document updates.
=> docs: Updated sample code for `output.mode`

docs/src/pages/reference/configuration/input.md
**READY**
The link to `OpenAPIObject` was broken so I fixed it.
https://github.com/metadevpro/openapi3-ts/blob/master/src/model/openapi30.ts#L12
none
none
=> docs: fix broken link to `OpenAPIObject`

docs/src/pages/reference/configuration/output.md
**READY**
It looked like the `VerbOptions` type no longer existed and had been changed to `GeneratorVerbOptions` so I updated the name of the type and the URL of the link
none
none
=> docs: fix url for `GeneratorVerbOptions` type

packages/swr/src/index.ts
**READY**
fix https://github.com/anymaniax/orval/issues/800
When using `query` for an API parameter defined in `OpenAPI`, the name of the argument in the automatically generated function and the name of the argument within the function collide.
In that case, we changed the variable name `query` to `_query`.
Variables other than `query` are not considered because they are rarely used as parameters.
Similar problems occur with `client` other than `swr`, so we will deal with them in order once this PR is merged.
none
1. Specify `query` in the parameter name as below:
```yaml
openapi: '3.0.0'
info:
version: 1.0.0
title: Swagger
license:
name: MIT
paths:
/pets/{query}:
get:
summary: Info for a specific pet
operationId: showPetById
tags:
- pets
parameters:
- name: query
in: path
required: true …
```
=> fix: avoid duplicate variable name in `swr` function

packages/query/src/index.ts
**READY**
follow up https://github.com/anymaniax/orval/pull/1130
> When using query for an API parameter defined in OpenAPI, the name of the argument in the automatically generated function and the name of the argument within the function collide.
In that case, we changed the variable name query to _query.
Variables other than query are not considered because they are rarely used as parameters.
I also supported `react-query`, `vue-query`,  and `svelte-query` with this PR
https://github.com/anymaniax/orval/pull/1130
1. Specify `query` in the parameter name as below:
```yaml
openapi: '3.0.0'
info:
version: 1.0.0
title: Swagger
license:
name: MIT
paths:
/pets/{query}:
get:
summary: Info for a specific pet
operationId: showPetById
tags:
- pets
parameters:
- name: query
in: path
required: true …
```
=> fix: avoid duplicate variable name in genrated function for query clients

packages/core/src/types.ts, packages/swr/src/index.ts
**READY/**
this PR is small refactoring. We expect to add properties that can be specified with `output.override.swr` in future improvements, so we defined the `swr` option as type. For example https://github.com/anymaniax/orval/issues/796
none
none
=> chore: define options type for `swr`

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/swr/src/index.ts
**READY**
I squash commits if necessary when all reviews are complete.
fix https://github.com/anymaniax/orval/issues/796
I enabled the `swr` client to define functions using [`useSWRInfinite`](https://swr.vercel.app/docs/pagination#useswrinfinite). These are generated by specifying them in the configuration file using the `override` option as shown below:
```javascript
output: {
client: 'swr',
target: 'src/gen/endpoints',
schemas: 'src/gen/model',
override: {
swr: {
useInfinite: true,
},
},
},
```
Along with this, we are also making some refactorings:
- Most of the implementations were combined in one string definition, but I decided to separate them as variables and combine them in the end.
- The `isEnabled` judgment process and the `key` definition have been separated.
none
1. Please …
=> feat: possible to generate a function using `useSWRInfinite` on the `swr` client.

packages/core/src/generators/imports.ts
**READY**
fix https://github.com/anymaniax/orval/issues/1145
>The current judgment logic uses a simple condition of whether the string exists.
Therefore, for example, if the variable useKey is used, Key will be imported, but this may be an unnecessary import.
I achieved this by using regular expressions to determine.
none
1. prepare OpenAPI definition for pet store
```
orval
```
3. We have confirmed that the existing generation process is not destroyed using the pet store.
=> fix: strictly check dependencies import judgment using regular expressions

.lintstagedrc.json, package.json, yarn.lock
**READY**
fix https://github.com/anymaniax/orval/issues/1140
When I checked about pretty-quick, it appeared that this library was no longer maintained. [issue](https://github.com/azz/pretty-quick/issues/164) has also been raised. Therefore, i have migrated my packages to [lint-staged](https://github.com/lint-staged/lint-staged), where they can still be managed with `package.json`.
https://github.com/anymaniax/orval/pull/1136
1. Please commit the source code that violates the format
2. execute `git commit`
3. The format check works as before.
=> chore: change `pretty-quick` in format library to `lint-stage`

packages/swr/src/index.ts
**READY**
fix https://github.com/anymaniax/orval/issues/1013
Originally, in `generateSwrHook`, if `verb` was other than `Verbs.GET`, processing was skipped, but we implemented a function to generate a function using [`useSWRMutation`](https://swr.vercel.app/docs/mutation#useswrmutation). 
Since the processing required for `mutation` is different from `query`, we have newly added `generateSwrMutationImplementation`, which is a function for generating the string of the function itself, and `generateSwrMutationArguments`, which generates arguments.
Also, since `useSWRMutation` requires a dedicated `Fetcher` as the second argument, I reused it by wrapping the http function. This allows reuse of `mock` and customization of http client using global mutator.
none
1. Prepare an `OpenAPI` …
=> feat: implement function generation using `useSWRMutation`

packages/axios/src/index.ts, packages/query/src/index.ts, packages/swr/src/index.ts
**READY**
Fixes the poorly typed SecondParameter utility type.
=> fix: adjust SecondParameter utility type

packages/core/src/utils/case.test.ts, packages/core/src/utils/case.ts
**READY**
Solves #1156 
```bash
> git checkout fix-handle-nordic-characters
> yarn build
> yarn test
```
1. Use below schema to generate:
```yaml
openapi: '3.0.0'
info:
version: 1.0.0
title: Swagger ÆrligØnskeÅpen
license:
name: MIT
paths:
/ærligØnskeÅpen:
get:
summary: List all ærlig-ønske-åpen
operationId: listÆrligØnskeÅpen
responses:
'200':
description: A paged array of ærlig-ønske-åpen
content:
schema:
$ref: '#/components/schemas/ÆrligØnskeåpen'
components:
schemas:
ÆrligØnskeåpen:
type: object
required:
- ærlig
- ønske
- åpen
properties:
ærlig:
type: string
ønske:
type: string
åpen:
type: string
```
2. Check that the output respects nordic characters.
=> fix: handle nordic characters

package.json, yarn.lock
**READY**
`prettier` includes `@types-prettier` from v3, so i removed this due to dependencies.
Ref: https://www.npmjs.com/package/@types/prettier
https://github.com/prettier/prettier/pull/14212
none
=> chore: remove `@types-prettier` package

packages/core/src/utils/logger.ts, packages/orval/src/bin/orval.ts, packages/orval/src/generate.ts, packages/orval/src/index.ts, packages/orval/src/utils/executeHook.ts, packages/orval/src/utils/watcher.ts
**READY**
Shows stack traces for internal errors. e.g.:
```
🛑 myproject -  Error: All arrays must have an `items` key define
at getArray (/Users/eric/Source/orval/packages/core/dist/index.js:41318:11)
at getScalar (/Users/eric/Source/orval/packages/core/dist/index.js:41841:34)
at resolveValue (/Users/eric/Source/orval/packages/core/dist/index.js:41200:18)
at resolveObjectOriginal (/Users/eric/Source/orval/packages/core/dist/index.js:41215:25)
at resolveObject (/Users/eric/Source/orval/packages/core/dist/index.js:41284:18)
at items.reduce.values (/Users/eric/Source/orval/packages/core/dist/index.js:41969:30)
at Array.reduce (<anonymous>)
at combineSchemas (/Users/eric/Source/orval/packages/core/dist/index.js:41963:30)
at getObject …
```
=> feat: show error stack traces

packages/mock/src/faker/getters/scalar.ts
**READY**
If `null` exists in `enum`, the generated `enum` type will not include `null` or the empty string `''`.
For example bellow generated by https://github.com/anymaniax/orval/blob/master/tests/specifications/null-type-v3-0.yaml#L91
```typescript
export type NullableStringEnum = typeof NullableStringEnum[keyof typeof NullableStringEnum] | null;
export const NullableStringEnum = {
ONE: 'ONE',
TWO: 'TWO',
THREE: 'THREE',
} as const;
```
Therefore, they are unnecessary, including the value patterns generated by mock. In fact, specifying the type causes an error.
```typescript
export const getFetchNullableEnumsMock = () => (
faker.helpers.arrayElement([faker.helpers.arrayElement(['ONE','TWO','THREE', ''] as const), null])
)
const mock: NullableStringEnum = getFetchNullableEnumsMock()
// …
```
=> fix(mock): `null` is excluded instead of being converted to an empty string `''`

packages/core/src/getters/array.ts, tests/configs/default.config.ts, tests/specifications/example-v3-1.yaml
**READY**
Support for OpenAPI 3.1 prefixItems (tuple types).
https://json-schema.org/understanding-json-schema/reference/array#tupleValidation
Fixes #890
=> feat: support for prefixItems

packages/orval/src/import-specs.ts
**READY**
Sort schemas after reading input files and before generating output.
Fixes #1159
Extract the workspace from [reproduce.tar.gz](https://github.com/anymaniax/orval/files/14030695/reproduce.tar.gz)
```bash
> python3 gen.py
> npx orval
> cp gen/reproduce.ts gen/reproduce-one.ts
> npx orval
> diff gen/reproduce-one.ts gen/reproduce.ts
```
The two output files should be identical.
=> fix: reproducible typescript output (#1159)

packages/core/src/generators/verbs-options.ts
**READY**
Don't generate a `formData` mutator if the operation body does not accept formData.
Fixes #1173
1. Fetch the full/expanded petstore chema from [here](https://petstore.swagger.io/v2/swagger.json).
2. Specify mode as `tags` or `tags-split`
3. Run `orval`
4. Generated files (with mode `tags-split`):
(user/user.ts)
```ts
import type { LoginUserParams, User, UserArrayBody } from '.././models';
import { customInstance } from '.././custom-instance';
```
(pet/pet.ts)
```ts
import type {
ApiResponse,
FindPetsByStatusParams,
FindPetsByTagsParams,
Pet,
PetBody,
UpdatePetWithFormBody,
UploadFileBody,
} from '.././models';
import { customInstance } from '.././custom-instance';
import { customFormData } from '.././custom-form-data';
```
=> feat: Only import formData override if it is used in file

packages/core/src/types.ts, packages/core/src/writers/target-tags.ts, packages/core/src/writers/target.ts, packages/mock/src/msw/index.ts, packages/orval/src/client.ts
**READY**
Fix #822
I separate mock handler functions and aggregate functions. That way you can just use separate handlers. This will result in more reusable mocks.
```typescript
export const getPetsMock = () => [
http.get('*/pets', async () => {
await delay(1000);
return new HttpResponse(JSON.stringify(getListPetsMock()),
{ 
status: 200,
headers: {
'Content-Type': 'application/json',
}
}
)
}),
http.post('*/pets', async () => {
await delay(1000);
return new HttpResponse(null,
{ 
status: 200,
headers: {
'Content-Type': 'application/json',
}
}
)
}),
http.get('*/pets/:petId', async () => {
await delay(1000);
return new HttpResponse(JSON.stringify(getShowPetByIdMock()),
{ 
status: 200,
headers: {
'Content-Type': 'application/json',
}
}
)
})
]
```
```typescript
// Individual handler
export …
```
=> feat(msw): separated mock handler and made it reusable

packages/mock/src/faker/getters/object.ts, packages/mock/src/msw/index.ts
**READY**
I responded to part of https://github.com/anymaniax/orval/issues/822
If there is only one response case and the type is `object`, the returned value can be overwritten externally by specifying `overrideResponse` as an argument.
In order to handle the case where it is an `array` of `object` such as `Pets`, after calculating the return value, we determine whether overwriting is possible based on whether `overrideResponse` is included in it.
1. Specify basic pet schema as input
```
orval
```
3. generated mock function bellow: 
```typescript
export const getListPetsMock = (overrideResponse?: any) => (Array.from({
length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
id: faker.number.int({min: undefined, max: undefined}),
name: …
```
=> feat(msw): possible to overwrite value when creating an `object` with `msw` mock

packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts, packages/mock/src/msw/index.ts
**READY**
Define the return value type in the `msw` mock function.
Since the type of the model is used as the type to return, in `split`, `split-tag`, and `tags` modes, the list of imports required by the mock is similar to the http client.
none
```bash
```
1. Specify basic pet schema as input
2. execute orval
```
orval
```
3. generated mock function bellow:
The return type is specified.
```typescript
export const getListPetsMock = (overrideResponse?: any): Pets =>
Array.from(
{ length: faker.number.int({ min: 1, max: 10 }) },
(_, i) => i + 1,
).map(() => ({
id: faker.number.int({ min: undefined, max: undefined }),
name: faker.word.sample(),
tag: …
```
=> feat(msw): define the return value type in the `msw` mock function.

packages/mock/src/msw/index.ts
**READY**
fix https://github.com/anymaniax/orval/pull/1165#discussion_r1468472063
Error occurs when`eslint` if tries spread `undefined` so, i fix it.
I received a comment at https://github.com/anymaniax/orval/pull/1165
1. execute `orval`
2. check for `overrideResponse: any = {}`  in generated `msw` mock
=> fix: define default value for `msw` mock orverride

packages/core/src/writers/target-tags.ts, packages/core/src/writers/target.ts, packages/mock/src/msw/index.ts
**READY**
I made the value of the mock handler function overridable. This makes the handler even more reusable.
1. Specify basic pet schema as input
```
orval
```
3. generated mock function bellow: 
```typescript
export const getListPetsMockHandler = (overrideResponse?: Pets) => {
return http.get('*/pets', async () => {
await delay(1000);
return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getListPetsMock()),
{
status: 200,
headers: {
'Content-Type': 'application/json',
}
}
)
})
}
export const getShowPetByIdMockHandler = (overrideResponse?: Pet) => {
return http.get('*/pets/:petId', async () => {
await delay(1000);
return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getShowPetByIdMock()),
{
status: 200,
headers: { …
```
=> feat(msw): possible to value of the mock handler function overridable

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/orval/src/utils/options.ts, packages/query/src/index.ts, packages/query/src/utils.ts
**HOLD**
When client is set as react-query, 3 different functions are generated for each  query/mutation. For example:
```ts
export const useCreateUserHook = () => {
... 
};
export const useCreateUserMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(...): ... => {
...
};
export const useCreateUser = <TError = ErrorType<unknown>, TContext = unknown>(...) => {
....
};
```
**GOAL**: I don't want to export `useCreateUserHook`. This causes confusion for my team and I on which function to use: `useCreateUserHook`, or `useCreateUser`? Ideally we always use the react-query version (`useCreateUser`), but it's easier if we just don't export it at all, so no one can make the mistake
(I arguably don't want `useCreateUserMutationOptions` exported either, but that one is less …
=> RFC: feat(query): add shouldExportMutatorHooks option

tests/package.json, tests/yarn.lock
**READY**
bump `Angular` packages to v17 in `tests`
none
none
=> chore: bump `Angular` packages to v17 in `tests`

packages/core/src/getters/scalar.ts
**READY**
If we specify `nullable: true` in `OpenAPI`, `| null`" is added to the parameter type, but [`httpParams`](https://angular.jp/api/common/http/HttpParams) type in `Angular` doesn't support the `null` type.
As a result, the following type error will occur.
```typescript
Type 'number | null' is not assignable to type 'string | number | boolean | readonly (string | number | boolean)[]'.
```
See also https://github.com/angular/angular/issues/20564
So I fixed it so that it doesn't add the `nullable` type when the client is `angular`.
1. Specify `nullable: true` for the parameter
```yaml
paths:
/pets:
get:
summary: List all pets
operationId: listPets
tags:
- pets
parameters:
- name: limit
in: query
description: How many items to return …
```
=> fix(angular): avoid `Angular` type error when `nullable`

packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts
**READY**
fix #1204 
Fix #1201
I wanted to import types same to custom hooks in mocks in #1171, so I made changes to the import handling. However, this contained some issues, so I fixed them.
For example, imports used only in mocks such as enum types were lost, so we included them in the import target.
Similarly, imports used only in mocks such as enum types were lost, so we included them in the import target.
In addition, in `tags` mode, custom hooks and mocks are stored in the same file, so the import used by custom hooks was being imported twice, so this has been fixed.
this bug made by https://github.com/anymaniax/orval/pull/1171
1. Prepare definition including enum
```yaml
openapi: 3.1.0
info:
title: Missing import
paths:
/dog:
get:
responses:
200:
content:
schema: …
```
=> fix(msw): fixed imports of `split-tags`, `tags`, and `split` mode

tests/configs/angular.config.ts, tests/configs/axios.config.ts, tests/configs/react-query.config.ts, tests/configs/svelte-query.config.ts, tests/configs/swr.config.ts, tests/configs/vue-query.config.ts
**READY**
There are some problems that can be prevented by testing each mode using the petstore definition. For example https://github.com/anymaniax/orval/pull/1205
So, I added test case.
Make sure there are no errors
```
cd tests
yarn generate
yarn build
```
=> chore: added plain tests for each mode

packages/query/src/index.ts
@anymaniax this is the same fix as for `useMutation` but for `useQuery` here https://github.com/anymaniax/orval/pull/1209
The evaluation of the override was not correct
fix #730
=> fix: useQuery improve override logic

packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/mock/src/msw/index.ts
**READY**
In `split` and `split-tags` modes, a hooks import is included to import the return type into `mock`.
However, we can get around that by getting the return type from `response.imports` and including it in the `mock` import, so we fixed it.
none
pass test
=> fix(msw): refactor to include duplication of mock imports in mocks in `split` and `split-tags` modes

tests/configs/zod.config.ts
**READY**
I wanted to add a test to `zod` in #1211, but the definition of `zod` does not include response types like `Pet` or `Pets`, so `zod` and `mock` Mock was not working with this combination.
This issue was fixed in #1214, so we added tests for each mode of the petstore to `zod`
pass test
=> chore(zod): add petstore tests for each mode to `zod`

packages/mock/src/msw/index.ts
**READY**
fix #1106
This issue is occur when the path name and `operationId` are the same. So a rare case because `operationId` is usually used like `addXX` or `getXXX`, but i will fix it because it causes unintended problems for users.
`orval` gets the mock name from `title`, which is the same naming convention as the response mock.
```
`get${pascal(operationId)}Mock`;
```
```
`get${pascal(title)}Mock`,
```
Ref: https://github.com/anymaniax/orval/blob/master/packages/orval/src/client.ts#L172 
Therefore, I changed the response mock function name.
It's a breaking change, but out of all my ideas, I decided to do this because it has the least impact.
1. specify `mock: true` in `orval.config.js`
3. check the name change in the generated mock function
=> fix(msw): changed naming convention for response mock functions to avoid function name conflicts

packages/core/src/getters/object.ts
**READY/**
fix #1207
If the definition schema is blank object and `output.override.use TypeOver Interfaces` is `false`, the generated definition is incorrect.
I fixed it to create `{}` when using `interface`.
```typescript
export interface DbNotificationID unknown
```
```typescript
export interface DbNotificationID = {}
```
none
1. prepared openapi woth blank object 
```yaml
openapi: 3.0.3
info:
description: test
title: test
version: test
paths:
/ping:
get:
summary: test
responses:
'200':
description: ok
components:
schemas:
DbNotificationID: {}
```
3. check generated definition is valid
=> fix(core): implement `{}` insterd of `unknown` for blank schema interface

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/swr/src/index.ts, tests/configs/swr.config.ts
**READY**
As of `v6.24.0`, the 'swr' client now generates 'useSWRInfinite' and 'useSWRMutation' hooks. Therefore, since `output.override.swr.options` cannot be used in common for each hook, we will separate the options for each hook. First, this PR adds an option.to extend only `useSwr`.
- https://github.com/anymaniax/orval/pull/1148
- https://github.com/anymaniax/orval/pull/1138
1. check generated hooks in tests
tests/generated/swr/petstore-override-swr/endpoints.ts:
```typescript
/**
* @summary Info for a specific pet
*/
export const useShowPetById = <TError = AxiosError<Error>>(
petId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof showPetById>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
const {swr: swrOptions, axios: …
```
=> feat(swr): add `swrOptions` property to `output.override.swr`

packages/orval/src/index.ts
**READY**
I happened to find an unused `chalk` import, so I removed it.
none
=> chore(orval): remove unused `chalk` import

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/swr/src/index.ts, tests/configs/swr.config.ts
**READY**
This PR is a follow up to https://github.com/anymaniax/orval/pull/1223
I added a property `swrMutationOptions` to `output.override.swr` that extends only the options of `useSWRMutation`.
https://github.com/anymaniax/orval/pull/1223
1. check generated hooks in tests
tests/generated/swr/petstore-override-swr/endpoints.ts:
```typescript
/**
* @summary Create a pet
*/
export const useCreatePets = <TError = AxiosError<Error>>(
params: CreatePetsParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createPets>>, TError, string, Arguments, Awaited<ReturnType<typeof createPets>>> & { swrKey?: string }, axios?: AxiosRequestConfig }
) => {
const {swr: swrOptions, axios: axiosOptions} = options ?? {}
const swrKey = …
```
=> feat(swr): add `swrMutationOptions` property to `output.override.swr`

packages/core/src/utils/doc.ts, samples/basic/api/endpoints/petstoreFromFileSpec.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/basic/api/model/pet.ts, samples/basic/api/model/pets.ts, samples/basic/petstore.yaml
READY
Added support to generate block tags to JSDoc comments for some of the common Schema object properties. Did some simple refactoring in the `jsDoc` function to avoid duplication of code.
Here is the OpenAPI documentation for the properties [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#properties)
They are not official JSDoc tags, but VSCode picks them up as if they were in Intellisense, which was my goal.
I added all the new supported tags in `sample/basic/petstore.yaml`, which is where I tested that it worked. I looked through the other samples, but none of them used any of these properties, so no need to update them.
Add any of the following properties to a schema object:
- minLength
- maxLength
- minimum
- maximum
- exclusiveMinimum
- …
=> feat: jsdoc block tags

packages/query/src/index.ts
**READY**
Make sure we only generate prefetch calls for `QUERY` and `INFINITE` types, as it isn't possible to prefetch any other types.
Fixes #1234
```ts
client: {
input: '...',
output: {
client: 'react-query',
override: {
query: {
usePrefetch: true,
useQuery: true,
useSuspenseQuery: true,
},
},
...output,
},
},
});
```
Verified strictly `await queryClient.prefetchQuery(queryOptions)` calls were generated
=> fix(query): usePrefetch should only work for Query/Infinite types

packages/core/src/writers/types.ts, samples/angular-app/src/api/endpoints/pets/pets.msw.ts, samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
**READY**
Fixes https://github.com/anymaniax/orval/issues/1236
Improves the `NonReadonly<T>` type so it actually works now. Note: this implementation was taken from ts-essentials' DeepWritable<T>, which seem to have the most accurate type as of now
=> fix(core): improve NonReadonly type

packages/core/src/generators/interface.ts, packages/core/src/getters/object.ts, tests/specifications/regressions.yaml
**READY**
fix https://github.com/anymaniax/orval/issues/1227
When I responded to #1219, it caused unintended destruction, so I revert #1219.
This issue occurs when the doesn't have `type` like a bellow:
```yaml
NotDifinedType:
properties:
id:
description: not defined type schema
```
And, the issue where the interface definition results in an error when interface is an blank schema is resolved by replacing the value only in the case of interfaces.
- https://github.com/anymaniax/orval/pull/1219
1. prepared openapi woth blank object 
```yaml
openapi: 3.0.3
info:
description: test
title: test
version: test
components:
schemas:
DbNotificationID: {}
```
3. check generated definition is valid
=> fix(core): distinguish the value when it is blank only in `interface`

docs/src/pages/guides/angular.md, docs/src/pages/guides/basics.md, docs/src/pages/guides/react-query.md, docs/src/pages/guides/svelte-query.md, docs/src/pages/guides/swr.md, docs/src/pages/guides/vue-query.md, docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/input.md, docs/src/pages/reference/configuration/output.md
**READY**
Update inconsistent  from  "OpenApi" to "OpenAPI"  on the document.
none
none
=> docs: unify spelling to OpenAPI

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/swr/src/index.ts, tests/configs/swr.config.ts
**READY**
This PR is a follow up to #1223 and #1225
I added a property `swrInfiniteOptions` to `output.override.swr` that extends only the options of `useSWRInfinite`.
- #1223
- #1225
1. check generated hooks in tests
tests/generated/swr/petstore-override-swr/endpoints.ts:
```typescript
/**
* @summary Info for a specific pet
*/
export const useShowPetByIdInfinite = <TError = AxiosError<Error>>(
petId: string, options?: { swr?:SWRInfiniteConfiguration<Awaited<ReturnType<typeof showPetById>>, TError> & { swrKeyLoader?: SWRInfiniteKeyLoader, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
const {swr: swrOptions, axios: axiosOptions} = options ?? {}
const isEnabled = swrOptions?.enabled !== false && !!(petId)
const swrKeyLoader = …
```
=> feat(swr): add `swrInfiniteOptions` property to `output.override.swr`

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/swr/src/index.ts
**READY**
This PR is a sequel to #1223, #1225, and #1245.
Since the `swr` option is different for each query function, i fixed it to separate the options in #1223, #1225, and #1245.
Therefore, "output.override.swr.options" is no longer needed, so remove it.
- #1223
- #1225
- #1245
1. Check the options defined in each query function in the tests generated hook
tests/generated/swr/petstore-override-swr/endpoints.ts:
=> feat(swr): remove `output.orverride.swr.options` property

packages/query/src/index.ts
**READY**
Fix https://github.com/anymaniax/orval/issues/1247
As described in https://github.com/anymaniax/orval/issues/1247 hooks for queries with a verb other than `GET` did not get generated even though an operation override was present.
Seems like the `isQuery` variable was changed in https://github.com/anymaniax/orval/pull/1212 but the `queries` list containing which queries to generate hooks for still used the old condition.
```bash
```
1. Described in issue https://github.com/anymaniax/orval/issues/1247
=> fix: overridden non-GET queries not generating hooks

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
**READY**
* Fixes #1253 by removing resolver for `null` type. `zod.null()` is a valid method.
* Changes test case to contain `null` type.
N/A
N/A
=> fix(zod): fixes #1253 removing resolver for `null` type

packages/swr/src/index.ts, tests/specifications/petstore.yaml
**READY**
Fixes #1261 by naming the parameter __ when it is not used in the function
N/A
1. yarn build
2. cd tests
3. yarn generate:swr
4. generated code should contain a `getDeletePetByIdMutationFetcher` function containing `__: { arg: Arguments }` and a `getCreatePetsMutationFetcher` function containing `{ arg }: { arg: Arguments }`
=> fix: swr mutation fetcher - name param __ in case of no body arg

packages/mock/src/faker/constants.ts, tests/configs/swr.config.ts, tests/specifications/blob-file.yaml
**WIP**
Fix https://github.com/anymaniax/orval/issues/1259
Mock blobs, as proposed in my comment of issue #1259 
yarn build
cd tests
yarn generate:swr
check generated/swr/blob-file `export const getGetBinaryBlobResponseMock`
=> fix(msw): mock blobs as blobs instead of strings

packages/swr/src/index.ts, tests/configs/swr.config.ts
**READY**
Fixes #1270 
1. Build and then generate swr
2. Check tests\generated\swr\nested-arrays\endpoints.ts for errors
=> fix(swr): make sure to not include comma when not valid while generating swrMutationFetcher

packages/mock/src/faker/getters/scalar.ts, tests/configs/swr.config.ts, tests/specifications/enums.yaml
**READY**
Fix https://github.com/anymaniax/orval/issues/1262
Proposed fix for issue #1262 
Other ideas, should the map method be typed? E.g.
```ts
export const getGetApiDogResponseMock = (overrideResponse: any = {}): Dog => ({
petsRequested: faker.helpers.arrayElement([
Array.from(
{ length: faker.number.int({ min: 1, max: 10 }) },
(_, i) => i + 1,
).map<Bulldog>(() => ({
//     ^ change here
colour: faker.helpers.arrayElement([
faker.helpers.arrayElement(['BLACK', 'BROWN'] as const),
undefined,
]),
...overrideResponse,
})),
undefined,
]),
...overrideResponse,
});
```
1. yarn build
2. cd tests
3. yarn generate:swr
4. check in generated/swr/enums/endpoints, mocks of Cat should be `("BLACK" | "BROWN" | "WHITE" | "GREY")[] | undefined` or `("BLACK" | "BROWN" | "WHITE" | "GREY")[]`, while …
=> fix(msw): return mock as array of enums if array is the correct type

docs/src/pages/reference/configuration/output.md, packages/mock/src/msw/index.ts
**READY**
Fixes #1273 
Mock tried to import the error type, which caused the non-mock implementation to not try and import it. The mock code then filtered out all imports that weren't used in the mock, thus leaving out the error type.
1. cd tests
2. yarn generate:swr
3. go to generated/swr/petstore/endpoints.ts
4. see that the Error type is the generated Error model, and not the default js Error
```ts
export type ListPetsQueryError = AxiosError<Error>
//                                            ^ Go to definition leads to generated Error model
```
5. compare to previous version, where go to definition leads you to default js Error type.
=> fix(msw): make sure to not try to include error type in mock implementation

packages/core/src/getters/res-req-types.ts, packages/core/src/getters/response.ts, tests/configs/swr.config.ts, tests/specifications/errors.yaml
**READY**
Fixes #1256 
Problem was that the error type was getting filtered out as it was equal to the success type, resulting in error being unknown.
1. cd tests
2. yarn generate:swr
3. check generated/swr/errors/endpoints.ts
4. `export type CreateItemsQueryError = AxiosError<Item>`
5. compared to previous build, where it would be `export type CreateItemsQueryError = AxiosError<unknown>`
=> fix(swr): error type is correct even when it's the same type as success type

packages/core/src/getters/body.ts, packages/core/src/getters/props.ts, packages/core/src/types.ts, tests/configs/swr.config.ts, tests/specifications/optional-request-body.yaml
**READY**
~~Fixes #1111~~
Takes the required property of request bodies into account. We till make it required by default, but setting it to required: false will make it optional.
1. yarn generate:swr
2. check tests/generated/swr/optional-request-body/endpoints.ts. Endpoints without a required property has the request body required. Endpoints with a required: false property has the request body as optional.
=> fix: request bodies should take required property into account

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/mock/src/delay.ts, packages/mock/src/msw/index.ts, tests/configs/default.config.ts
**READY**
Add support for generating mock delay times at runtime.
Fixes: #1279
1. In root run `yarn build`.
2. cd samples/react-query/basic.
3. Open orval.config.ts and replace `mock: true,` with:
```typescript
mock: {
type: 'msw',
delay: () => (process.env.NODE_ENV === 'test' ? 10 : 1000),
delayCalcRuntime: true,
},
```
4. Run `yarn generate-api`.
5. Open `src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts`.
6. See that the delays are now `await delay((() => (process.env.NODE_ENV === 'test' ? 10 : 1e3))());`
=> feat: support runtime delay functions

packages/core/src/getters/res-req-types.ts
READY
Added support for schema type `integer` to have the same behavior as `number` when generating form data code. 
[Source](https://swagger.io/docs/specification/data-models/data-types/#numbers)
=> fix: schema type integer

docs/src/manifests/manifest.json
**READY**
I added the `msw` guide route. Because I created a guide on how to use `msw` in [this PR](https://github.com/anymaniax/orval/pull/1250), but I forgot to add the route. so, the guide was not showing up on the documentation site.
#1250
1. this PR merge
2. I'll check to document site
=> chore(msw): add `msw` guide route

docs/src/pages/guides/msw.md
**READY**
I fixed `Markdown` syntax in guide for `msw`
- https://github.com/anymaniax/orval/pull/1250
- https://github.com/anymaniax/orval/pull/1296
none
=> docs: fix markdown syntax in guide for `msw`

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/hono/src/index.ts, packages/orval/src/utils/options.ts, packages/zod/src/index.ts, tests/configs/zod.config.ts
**READY**
Add option coerce to zod client
=> feat(zod): add option coerce

packages/mock/src/msw/index.ts
READY
If you pass the value `false` to a mock handler to override response with that value, it would fallback to the default response. This PR should fix this, and it will now accept any value that isn't `undefined`.
=> fix(mock/msw): override response if it's false as well

docs/src/pages/reference/configuration/output.md
**READY**
Corrects the doc that link to the default faker mock formats.
Corrects the heading level of delayFunctionLazyExecute and generateEachHttpStatus
=> chore(docs): correct link for faker mock formats, correct nesting level

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/core/src/writers/single-mode.ts, packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts, packages/orval/src/utils/options.ts
**READY**
I added `output.fileExtension` option to possible specifying the extension of the generated file. So, are able to change the automatically generated client code extension to like a `pets.gen.ts`. The default is still `.ts`.
Furthermore, by configuring the following settings, you will be able to generate code with both `client` and `zod`.
`orval.config.js`:
```
import { defineConfig } from "orval";
petstore: {
input: {
},
output: {
client: 'swr',
mode: 'tags-split',
target: 'src/gen/endpoints',
schemas: 'src/gen/model',
mock: true
},
},
petstoreZod: {
input: {
},
output: {
client: 'zod',
mode: 'tags-split',
target: 'src/gen/endpoints',
schemas: 'src/gen/model',
fileExtension: '.zod.ts',
},
},
}); …
```
=> feat: added `output.fileExtension` option to possible specifying the extension for the generated file.

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/orval/src/bin/orval.ts, packages/orval/src/utils/options.ts, packages/orval/src/write-specs.ts
**READY**
fix https://github.com/anymaniax/orval/issues/1298
I Added option to apply `Biome` to automatically generated files.
`Biome` also has a command that runs only `format`, but will be `orval` supports the `check --apply` command that runs both `format` and `lint`. Because, if you only want to apply either `format` or `lint`, you can control it with the `Biome` configuration file.
none
1. execute `orval` cli command with `--biome` option and make sure `biome` executes together.
```bash
orval --biome
```
1. you define `biome` to `true` in `orval.config.js` like a bellow, then execute `orval` and make sure `biome` executes together.
```javascript
petstoreFile: {
input: {
},
output: {
client: …
```
=> feat(core): add option to apply `biome` to generated files

packages/core/src/types.ts, packages/orval/src/utils/options.ts, packages/query/src/index.ts, packages/query/src/utils.ts
**READY**
**Feature**
New overrides for react-query:
- shouldExportQueryKey - flag enabling/disabling QueryKey export
- shouldExportHttpClient - flag enabling/disabling "raw" Axios client export
**Bugfix**
seems like react-query/overrides did not work - they were defaulting to "true" :)
=> orval/query - override shouldExportHttpClient / shouldExportQueryKey flags introduced

packages/core/src/getters/combine.ts, tests/configs/default.config.ts, tests/specifications/any-of.yaml
**READY**
Fix https://github.com/anymaniax/orval/issues/884.
Tests were also added. I'm not familiar enough with the orval codebase (for now haha), but I think this fix is enough. Also tested on our production codebase and can confirm the problem was fixed.
=> fix: valid syntax when anyOf is present on querystring

packages/core/src/writers/types.ts, samples/angular-app/src/api/endpoints/pets/pets.msw.ts, samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
This reverts commit 5b76e3b61261bc8563f656e1f847b67c4ac833a8.
Fixes #1348
**READY**
Readonly properties should be excluded from request parameters
=> Revert "fix(core): improve NonReadonly type (#1237)"

packages/core/src/getters/array.ts, packages/core/src/getters/object.ts, packages/core/src/types.ts, packages/orval/src/utils/options.ts
**READY**
Fixes https://github.com/anymaniax/orval/issues/1348
`suppressReadonlyModifier` override option to stop usage of readonly modifier in models
=> feat: 'suppressReadonlyModifier' override option introduced

packages/core/src/types.ts, packages/mock/src/msw/index.ts, packages/orval/src/client.ts
`ClientMockBuilder` is old and not working, so i fixed it. And i sepalated types. And I removed the unnecessary `@ts-expect-error` comment
none
That all tests pass
=> chore: mock generator builer type to strict

packages/mock/src/faker/getters/object.ts, packages/mock/src/msw/mocks.ts
**READY**
Fixes #1347 
Running generate on the attached api definition resulted in an error, where `getGetNextResponseMock = (): number` returned a string. Also fixed this, unsure why it hasn't been an issue before?
Follow the steps in the issue
=> fix(msw): make sure to early out when detecting loop in additionalproperties

packages/mock/src/msw/index.ts
**READY**
Fixes #1329 
Adds the ability to pass a function into mock handlers as override
yarn generate with a config that has mock: true
check mock handlers, the override parameter should be able to be a function as well
=> feat: allow override for mock handlers to be a function

packages/mock/src/faker/getters/object.ts, packages/mock/src/faker/getters/scalar.ts, tests/configs/mock.config.ts
**READY**
Support for `type: [X, null]` into mocks. This PR is almost identical to the original one: https://github.com/anymaniax/orval/pull/645/files. 
I reused the #645 spec to create this test.
It previously generated the following:
```ts
export const getFetchNullableResponseMock = (): FetchNullable200 => ({})
```
Now its working as intended
```ts
export const getFetchNullableResponseMock = (): FetchNullable200 =>
faker.helpers.arrayElement([faker.word.sample(), null]);
```
=> fix(mocks): handle OpenAPI 3.1 nullability

packages/core/src/constants.ts, packages/core/src/getters/route.ts, packages/query/src/utils.ts
**READY**
Fixes #1084
This PR moves `TEMPLATE_TAG_REGEX` into core constants and updates it to be `/\${(.+?)}/g` as described in #1084.
It also imports this variable in `wrapRouteParameters` to reduce code duplication.
#895
=> feat: use better regex for route parameters

packages/core/src/generators/verbs-options.ts, packages/core/src/utils/merge-deep.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
Currently when you provide operation or tag options it completely override the global one. This will solve the problem with a deep merge
=> fix(override): add deep merge with operations and tag options

packages/core/src/getters/discriminators.ts
WIP, fixes: https://github.com/anymaniax/orval/issues/1385
=> fix: correct-enum-handling

packages/mock/src/faker/getters/scalar.ts, tests/configs/swr.config.ts, tests/specifications/pattern.yaml
**READY**
Fixes #1396. String properties has an optional field 'pattern', which contains a regex pattern: [OpenAPI Spec](https://swagger.io/docs/specification/data-models/data-types/#string)
Faker has support for generating random strings based on a regex: faker.helpers.fromRegExp
yarn generate:swr
check tests/generated/swr/pattern/enpoints.ts -> getGetVversionExampleResponseMock
=> feat(msw): take string pattern property into account when generating mocks

packages/mock/src/msw/index.ts
**READY**
Currently, the http status code of the response in the `handler` function is fixed to `200`. So I fixed it to use the first success response.
When using the following `OpenaAPI`
```yaml
paths:
/pets:
post:
summary: Create a pet
operationId: createPets
tags:
- pets
requestBody:
description: post body
required: true
content:
schema:
$ref: '#/components/schemas/Pet'
responses:
'201':
description: Null response
```
`status` fixed `200` in `msw` definition.
```
export const getCreatePetsMockHandler = () => {
return http.post('*/pets', async () => {
await delay(1000);
return new HttpResponse(null,
{
status: 200,
headers: {
'Content-Type': 'application/json',
}
}
)
})
}
```
use `201` from `OpenAPI` definition.
```
export const getCreatePetsMockHandler = () => {
return …
```
=> fix(msw): fix response http status code in handler function

packages/swr/src/index.ts, tests/configs/swr.config.ts
**READY**
Ran into this issue in my project and noticed there was an issue describing it:
Fixes #1233 
1. Use the changed swr config (without the changed code) and run generate:swr
2. Notice mutation fetchers are missing the options parameter
3. Build with changed code
4. Run generate:swr
5. Notice mutation fetchers are now correctly taking an options parameter and passing it on to the api call
=> fix(swr): correct second mutator parameter when using custom mutator

packages/core/package.json, packages/query/package.json, packages/zod/package.json
**READY**
I updated using `run` command in test each package.
The `vitest` runs the test in watch mode by default, so when you run `yarn test`, the prompt will not end and will wait.
This causes a problem where the `git commit` hook won't proceed and i can't `commit`, so I updated it to use the `run` command.
Maybe https://github.com/anymaniax/orval/pull/1404 ?
none
=> chore: update using `run` command in `vitest` each package

docs/src/pages/reference/configuration/input.md, packages/core/src/generators/schema-definition.ts, packages/core/src/types.ts, packages/orval/src/import-open-api.ts, tests/configs/default.config.ts
**READY**
i added `input.fliters.schemas` option. Because even if i use `input.fliters.tags` to filter endpoint generation, schema objects are not filtered, resulting in unnecessary files being generated. I can avoid that by using `input.fliters.schemas` together.
none
Using the test case I added, we can check.
=> feat: add `input.filters.schemas` option

packages/mock/src/faker/getters/scalar.ts
**READY**
Fixes #1395 
Implemented similarly to how string enums work
=> fix(msw): correctly generate integer enum mocks

packages/core/src/getters/res-req-types.ts, tests/configs/swr.config.ts, tests/specifications/form-data-optional-request.yaml
**READY**
Fixes #1392 
This makes sure to check for undefined in case the request body is optional. This also contains changes to not cast to `any` when handling subtypes.
Before:
```ts
export const createPets = (
pet?: Pet,
version: number = 1,
options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
const formData = new FormData();
if ((pet as any).name !== undefined) {
formData.append('name', (pet as any).name);
}
if ((pet as any).tag !== undefined) {
formData.append('tag', (pet as any).tag);
}
if ((pet as any).id !== undefined) {
formData.append('id', (pet as any).id.toString());
}
if ((pet as any).name !== undefined) {
formData.append('name', (pet as any).name);
}
if ((pet as any).tag !== undefined) {
formData.append('tag', (pet as any).tag);
}
if (pet['@id'] !== undefined) …
```
=> fix: take optional request body into account when creating form data

packages/mock/src/msw/index.ts
=> fix(msw): make sure method is async even when delay=false

packages/core/src/types.ts, packages/orval/src/utils/options.ts, packages/zod/src/index.ts
**READY**
This PR fixes an issues introduced in #1380 that used the mock `generateEachHttpStatus` option to determine whether to generate more reposopnes than just `200` this resolves this by adding that option to zod.
=> fix: generate each http status is now zod specific

packages/zod/src/index.ts, packages/zod/src/zod.test.ts, tests/configs/zod.config.ts
**READY**
`additionalProperties: true` isn't treated the right way during schema parsing, which results in runtime error during generation. Since #972 is stalled, decided to dig into it myself.
Previous attempt to fix this:
| [CxGarcia:fix/zod-additional-properties](https://github.com/CxGarcia/orval/tree/fix/zod-additional-properties) | [link](https://github.com/anymaniax/orval/pull/972) |
=> fix(zod): treat `additionalProperties` keyword 

packages/mock/src/faker/getters/scalar.ts, tests/configs/mock.config.ts, tests/specifications/enum-refs.yaml
**READY**
Fixes #1455 
Based on the example added in #1455, I was able to confirm that the import statement for the enum was being added correctly, and that there were no TS errors.
=> fix(msw): correctly add imports for enum references

packages/mock/src/msw/mocks.ts, tests/configs/swr.config.ts, tests/specifications/examples.yaml
**READY**
Fixes #1458.
yarn build
yarn generate:swr
check generated/examples/endpoints -> `getGetUsersResponseMock` and `getGetUsers2ResponseMock` should be `["userD","userE","userF"]` and `["userA","userB","userC"]`
=> fix(msw): correctly generate ref'd examples

samples/next-app-with-fetch/orval.config.ts, tests/configs/fetch.config.ts, tests/mutators/custom-fetch.ts
**READY**
follow up #1457
I have prepared basic tests for the `fetch` client.
I added one, because I needed to add only tests that use custom mutators.
none
none
=> chore(fetch): add mutator test for `fetch` client

packages/core/src/getters/object.ts
READY
Fixes https://github.com/anymaniax/orval/issues/1464
The generated type for objects with `additionalProperties: true` becomes `[key: string]: unknown` instead of `[key: string]: any` for better type safety.
```bash
```
1.
=> fix: use unknown instead of any for additional properties

docs/src/pages/reference/configuration/output.md
**READY**
Fixes: https://github.com/anymaniax/orval/issues/1469
Update the documentation page for output options, namely correcting that `suppressReadonlyModifier` needs to be within the override object.
=> docs: suppressReadonlyModifier

packages/fetch/src/index.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/next-app-with-fetch/app/pets.tsx, samples/next-app-with-fetch/custom-fetch.ts
**READY**
fix #1465
I updated the 'fetch' client to include the status code in the response, as below:
```typescript
export type listPetsResponse = {
status: number;
data: Pets;
};
export const listPets = async (
params?: ListPetsParams,
options?: RequestInit,
): Promise<listPetsResponse> => {
const res = await fetch(getListPetsUrl(params), {
...options,
method: 'GET',
});
const data = await res.json();
return { status: res.status, data: data };
};
```
none
none
=> feat(fetch): include status code in `fetch` client response

docs/src/pages/reference/configuration/output.md
**READY**
I encountered format error in docs so, i fixed it.
https://github.com/anymaniax/orval/pull/1468
none
=> docs: fix format for `suppressReadonlyModifier`

packages/core/src/writers/schemas.ts, packages/orval/src/write-specs.ts
Closes [https://github.com/anymaniax/orval/issues/1462](https://github.com/anymaniax/orval/issues/1462)
=> fix: applies fileExtension to schemas generated files

docs/src/manifests/manifest.json, docs/src/pages/guides/fetch.md
I add guide for `fetch` client.
none
none
=> docs(fetch): add guide for `fetch` client

package.json, yarn.lock
**READY**
Orval indirectly depends on [`node-fetch`](https://github.com/node-fetch/node-fetch), a shim for the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). 
To handle URLs in a standards-compliant way, it depends on [`whatwg-url`](https://github.com/jsdom/whatwg-url), a Node.js polyfill for the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). 
The version of `whatwg-url` that Orval depends on uses [`punycode`](https://nodejs.org/api/punycode.html) - a built-in (kinda) module that is deprecated in modern versions of Node.js.
Because it is deprecated, users of Orval will be given the following error message:
```
(node:95791) [DEP0040] DeprecationWarning: The 'punycode' module is deprecated. Please use a userland alternative instead.
```
This …
=> fix: punycode deprecation warning

packages/mock/src/msw/index.ts, samples/angular-app/src/api/endpoints/pets/pets.msw.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/next-app-with-fetch/app/gen/pets/pets.msw.ts, samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, tests/specifications/any-of.yaml
**READY**
In some cases we do want to assert received request even for empty response mock
for that UI tests can add assertions in MSW mock override function
this PR allows us to do such assertion even for empty response mock:
```ts
server.use(
getPetsControllerBulkUpdateMockHandler(
async ({ request, params }) => {
const body = await request.json();
expect(params.id).toBe('2');
expect(body).toEqual({
cats: [],
});
},
),
);
```
=> feat: add override function to empty response mocks

packages/swr/src/client.ts, packages/swr/src/index.ts
**READY**
I plan to allow the `swr` client to select an `http fetcher`.
Therefore, I extracted the http request processing to a file to be able to branch flexibly.
none
none
=> chore(swr): extract http client in `swr`

packages/mock/src/faker/getters/scalar.ts, tests/configs/mock.config.ts, tests/specifications/typelessEnum.yaml
**READY**
Fixes #1490 by infering type of enum if all enum values have same type and they are string or number
```bash
> cd tests
> yarn generate:mock
```
1. Should generate a file at `tests/generated/mock/typelessEnum/typelessEnums.ts` with the following variable 
```ts
export const getGetApiColorsResponseMock = (overrideResponse: Partial< ColorObject > = {}): ColorObject => ({color: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(Colors1)),faker.helpers.arrayElement(Object.values(Colors2))]), undefined]), ...overrideResponse})
```
formatted
```ts
export const getGetApiColorsResponseMock = (
overrideResponse: Partial<ColorObject> = {},
): ColorObject => ({
color: faker.helpers.arrayElement([
faker.helpers.arrayElement([ …
```
=> feat(mock): infer type from enum values for string and number

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/fetch/src/index.ts, packages/orval/src/client.ts, packages/orval/src/utils/options.ts, packages/swr/package.json, packages/swr/src/client.ts, packages/swr/src/index.ts, tests/configs/swr.config.ts, tests/mutators/custom-fetch.ts, yarn.lock
**READY**
I added `output.httpClient` option.
And able to using `fetch` API with `swr` client. custom mutators also available.
Since `@orval/fetch` doesn't have a any deps, i specified `@orval/fetch` as a dependency of `@orval/swr`. This allows the automatically generated functions of the http client to be shared, improving maintainability.
none
You can check generated code in the test
```bash
cd tests
yarn generate
```
I added test case is bellow:
- `generated/swr/http-client-fetch`
- `generated/swr/http-client-fetch`
=> feat(swr): support for using `fetch` for http clients with `swr`

docs/src/pages/reference/configuration/output.md
**READY**
I made a small miss so fixed it.
added by https://github.com/anymaniax/orval/pull/1498
none
=> docs: fix `output.httpClient` title

packages/core/src/getters/combine.ts, tests/configs/default.config.ts, tests/specifications/combined-enum.yaml
**READY**
Fix #1419 
Fixes Referencing combined enums results in a duplicate schema name error #1419
```bash
> cd tests
> yarn generate:default
```
You should see 
> 🎉 combined-enum - Your OpenAPI spec has been converted into ready to use orval!
Should generate the following file at `tests/generated/default/combine-enum/schemas/colors.ts`
```typescript
import { Colors1 } from './colors1';
import { Colors2 } from './colors2';
export type Colors = typeof Colors[keyof typeof Colors] 
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Colors = {...Colors1,...Colors2,} as const;
```
=> fix(core): Referencing combined enums results in a duplicate schema name error

packages/core/src/generators/schema-definition.ts, packages/core/src/getters/combine.ts
**READY**
This pr fixes the regression of #1341, that was created by pr #1488, which was attempting to fix issue #1419
This fixes both the regression and #1419 
#1341
#1419
#1488
```bash
> yarn build
> cd tests
> yarn generate
> yarn build
```
1. The above steps should complete successfully
=> merge duplicate child schemas into one

packages/mock/src/faker/resolvers/value.ts
Use original name of referenced schema in ref resolution
fix #1500
**READY**
- Resolves an issue where the maximum call stack is exceed when using circular dependencies in schema. 
- The mock scalar function uses the `existingReferencedProperties` variable to maintain a list of visited schema items.
- The name provided from the `resolveValue` function uses the ref's value as pascalCase instead of the original name.
- This would cause an infinite loop as the visited ref object isn't recognised as being visited.
- Fixed by using the original name in schema ref resolution.
1. Generate mocks from a schema that includes a ref to a component with a lower case name.
2. Check it doesn't fail.
=> fix(mocks): use original name of ref schema in ref resolution

packages/query/src/client.ts, packages/query/src/index.ts, packages/swr/src/client.ts
**READY**
follow up: #1387 
Since I want `query` to be able to use `featch` as an http client, i first extract the functions related to the http client in `query`.
none
You can check that the test is successful
=> chore(query): extracting functions related to http client in `query`

packages/query/package.json, packages/query/src/client.ts, packages/query/src/index.ts, yarn.lock
**READY**
I made the `query` client to be able to use `fetch` as an http client.
I gonna add those sample apps ans tests with other PR.
none
You can check by setting  `fetch` to `httpClient` along with query clients.
```ts
petstoreFile: {
input: {
},
output: {
mode: 'tags-split',
client: 'react-query',
httpClient: 'fetch',
target: 'src/gen/endpoints',
schemas: 'src/gen/model',
baseUrl: 'http://localhost:8000',
},
},
});
```
=> feat(query): query clients can use `fetch` as an http client

packages/query/src/client.ts, packages/query/src/index.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts
**READY**
The `fetch` doesn't use `MaybeRef` in arguments so using `unref` to http function prop when `fetch` with `vue`.
none
You can check this by setting `vue-query` to `client` and `fetch` to `httpClient` in `orval.config`
=> fix: using `unref` to http function prop when `fetch` with `vue`

packages/fetch/src/index.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/react-query/form-data-mutator/endpoints.ts, samples/react-query/form-data/endpoints.ts, samples/react-query/form-url-encoded-mutator/endpoints.ts, samples/react-query/form-url-encoded/endpoints.ts, samples/react-query/hook-mutator/endpoints.ts, samples/svelte-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts, samples/vue-query/vue-query-basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
I extracted from #1504 what removes the unnecessary question mark in the "fetch" query parameter
#1504 
I test in the `next-app-with-fetch` sample app.
```ts
import { listPets } from './gen/pets/pets';
export default async function Pets() {
// input blank object
const { data: pets, status } = await listPets({});
```
request to `http://localhost:3000/pets?`
request to `http://localhost:3000/pets`
=> fix(fetch): remove unnecessary question mark in `fetch` query params

packages/core/src/getters/object.ts, packages/core/src/getters/scalar.ts, packages/core/src/types.ts, tests/configs/default.config.ts, tests/specifications/const.yaml
**READY**
Allows for the generation of literal types for booleans and numbers. Fixes #1509.
```bash
> git clone https://github.com/RinseV/orval.git
```
1. Install dependencies & build the package
2. Generate the default specification in the `tests` folder: `yarn generate:default`
3. The generated models will have the correct literal types
I didn't want to break the current functionality from #1326 where not specifying a `type` will generate it as a string literal. So, having only `const` without a `type` will still generate as a string. The same is true for a `type` of `string`. But if the `type` is either `number`, `integer` or `boolean`, the type will be generated as the literal value of `const`. This can result in invalid code (like …
=> feat: generate literal types for booleans and numbers

docs/src/manifests/manifest.json, docs/src/pages/guides/custom-client.md, docs/src/pages/guides/fetch-client.md, docs/src/pages/guides/fetch.md, docs/src/pages/guides/set-base-url.md, docs/src/pages/overview.md
**READY**
I added docs for using `fetch` as an http client.
none
none
=> docs: added using `fetch` as an http client

packages/fetch/src/index.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts, tests/configs/fetch.config.ts
**READY**
fix #1525 
I made the `fetch` client support cases other than `application/json`, such as `multipart/form-data` and `application/x-www-form-urlencoded`. And, if input `OpenAPI` have `content-type`, add `Content-Type` header to fetch request options.
none
You can check from the test case I added
=> feat(fetch): support form data and form url encoded request

packages/swr/src/index.ts, samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
fix #1487
the `useMutation` key should use same key as `useSWR`.
https://github.com/vercel/swr/blob/1585a3e37d90ad0df8097b099db38f1afb43c95d/src/mutation/types.ts#L236-L241
So, i fixed the get key function to return Array and hooks use Array as key for `useMutation`.
And, and, update the using url type in http fetcher from `string` to `Key`
none
none
=> fix(swr): fix to use Array as  key for `useMutation`

packages/fetch/src/index.ts
**READY**
Excludes form data content header in fetch client. 
Fix #1531
https://github.com/orval-labs/orval/pull/1529
Generate fetch client using multipart/form-data openapi spec
=> Exclude content type header if multipart/form-data in fetch client

packages/core/src/types.ts, packages/query/src/index.ts
=> fix(query): check for peer dependencies

packages/mock/src/msw/index.ts, tests/configs/react-query.config.ts
**READY**
Fix #1566
MSW resolver function has to be always async as Orlval is always adding async "override" function
in case `mock.delay = false` Orval failed to add `async` keyword
I also added extra test case to catch the case
🙏 Please do check if I missed anything for tests
🙏 Please release this fix soon as it's blocking us to use Orval v7 and it has couple fixes we're looking for
=> fix: Always async resolver function

packages/query/src/client.ts
fix #1534
I removed unnecessary `Promise` from error response types when using query client.
Because the `error` variable doesn't need a `Promise` and there is no need to use `await`.
https://tanstack.com/query/latest/docs/framework/react/reference/useQuery
const { data, error} = useCreatePets()
// const error: Ref<null> | Ref<Promise<Error>>
const { data, error} = useCreatePets()
// const error: Ref<null> | Ref<Error>
none
you can check `error` variable type in sample app
```diff
// samples/vue-query/custom-fetch/src/components/HelloWorld.vue
- const { data } = useListPets();
+ const { data, error } = useListPets();
```
=> fix(query): remove `Promise` from error type in query clients

packages/hono/src/index.ts
**READY**
Fix #1573 
The logic to account for the tag in the relative path already existed [during the generation of the handlers](https://github.com/orval-labs/orval/blob/master/packages/hono/src/index.ts#L221). 
I simply reused it when creating the imports for the handlers in the hono routes.
=> fix: relative hono handler imports when using tag mode

packages/query/src/index.ts
**READY**
Currently with the client query if you set the config request options to false the return type is always defined which is wrong.
=> fix(client-query): return type can be undefined when config request options is set to false

docs/src/pages/reference/configuration/output.md
Fix #1586 fix(zod): Docs missing generateEachHttpStatus option
=> fix(zod): Docs missing generateEachHttpStatus option

packages/core/src/types.ts, packages/core/src/writers/single-mode.ts, packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts, packages/orval/src/client.ts, packages/query/src/index.ts, yarn.lock
**READY**
close #1612
Current behavior: When `output.override.mutator` is set (i.e`hasGlobalMutator` is true), the React dependencies (like useCallback) are imported. However, in this issue(#1612), the mutator is set in `output.override.tags.foo`, and this case wasn't covered properly.
Update: I've now made sure that even when the mutator is set in `output.override.tags.foo`, the React dependencies will be imported as expected.
1.Following the steps in this issue, set up the orval.config.ts file and provide api.yaml as the input. Then, check the output to …
=> fix: import react deps when tags have mutator

packages/orval/src/write-specs.ts
**READY**
Setting biome: true and running the `orval` command results in an error asking to change `--apply` to `--write`.
```bash
DEPRECATED  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
! The argument --apply is deprecated, it will be removed in the next major release. Use --write instead.
```
1. You define biome to true in `orval.config.ts` like a bellow, then execute `orval` and make sure biome executes together.
```ts
petstoreFile: {
input: {
},
output: {
client: 'swr',
target: 'src/gen/endpoints',
schemas: 'src/gen/model',
biome: true,
},
},
});
```
=> fix: change --apply to --write in biome check command

packages/zod/src/index.ts
**READY**
close #1594
This PR adds the capability to generate Zod constants when handling oneOf schemas in the OpenAPI specification.
```ts
/**
* Generated by orval v7.1.0 🍺
* Do not edit manually.
* Swagger Petstore
* OpenAPI spec version: 1.0.0
*/
import { z as zod } from "zod";
/**
* @summary Create a pet
*/
export const createPetsBodyPasswordMin = 8;
export const createPetsBody = zod.object({
login: zod
.string()
.min(createPetsBodyLoginMinOne)
.max(createPetsBodyLoginMaxOne)
.or(zod.string().email()),
password: zod.string().min(createPetsBodyPasswordMin),
remember: zod.boolean(),
});
```
```ts
/**
* Generated by orval v7.1.0 🍺
* Do not edit manually.
* Swagger Petstore
* OpenAPI spec version: 1.0.0
*/
import { z as zod } from "zod";
/**
* @summary Create a pet
*/
export const …
```
=> fix: generate zod constants for oneOf schemas

tests/configs/react-query.config.ts
**READY**
As @soartec-lab mentioned in PR #1614, I have added a test for tags.mutator.
This test expects that `useCallback` is imported when a hook mutator is provided.
|fix/import-react-deps-when-tags-have-mutator | [link](https://github.com/orval-labs/orval/pull/1614) |
1. cd tests
2. yarn generate:react-query
3. check if  `🎉 tagHookMutator - Your OpenAPI spec has been converted into ready to use orval!` displays
=> chore(test): add test for case where tags have hook mutator and client is react-query

packages/mock/src/faker/getters/combine.ts, tests/configs/default.config.ts, tests/specifications/all-of.yaml
**READY**
fix #1101 
when i have not implemented `properties` in `OpenAPI` like a bellow, generated `msw` mock will be broken.
```yaml
openapi: 3.0.0
info:
version: 1.0.0
title: AnyOf Schema
license:
name: MIT
paths:
/not-has-properties-with-all-of-pets:
get:
operationId: getNotHasPropertiesWithAllOfPets
tags:
- pets
description: |-
Not has properties with allOf pets.
responses:
'200':
description: User
content:
schema:
allOf:
- $ref: '#/components/schemas/Pet'
- $ref: '#/components/schemas/PetDetail'
- type: object
required:
- category
- type: object
required:
- color
components:
schemas:
Pet:
type: object
required:
- id
- name
properties:
id:
type: integer
format: int64
name:
type: string
PetDetail:
type: object
required:
- tag
properties:
tag:
type: string
```
The …
=> fix(msw): broken mock when `allof` with not has `properties` object

packages/zod/src/index.ts
**READY**
close #1548
- Updated `parseBodyAndResponse` to apply `removeReadOnlyProperties` when parsing the body, ensuring that readOnly fields are excluded before generating the Zod schema.
- This ensures that only non-readOnly fields are considered for the body schema
Set up the following files and verify that the generated body schema does not include any properties that have readOnly set to true.
<details>
<summary>orval.config.js</summary>
```ts
import { defineConfig } from "orval";
petstore: {
input: "./petstore.yaml",
output: {
client: "zod",
target: …
```
=> fix: remove readOnly fields from body schema parsing before Zod generation

packages/fetch/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/react-app-with-swr/fetch-client/src/api/endpoints/swaggerPetstore.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts
**READY**
fix #1622 
The `fetch` client could not override `header` with `options`, so i fixed it.
The `fetch` client could not override `headers` with `options` because `headers` implement after `...options` so `headers` is always fixed.
```
return customFetch<Promise<createPetsResponse>>(getCreatePetsUrl(), {
...options,
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify(createPetsBodyItem),
});
```
`headers` implement contains `...options?.headers` 
```
return customFetch<Promise<createPetsResponse>>(getCreatePetsUrl(), {
...options,
method: 'POST',
headers: { 'Content-Type': 'application/json', ...options?.headers },
body: JSON.stringify(createPetsBodyItem),
});
```
none
You can check by using sample app.
=> fix(fetch): `fetch` client can now override `headers` with `options`

packages/mock/src/faker/resolvers/value.ts, tests/specifications/one-of.yaml
**READY**
Suppose I have a schema `nullable` object in `oneOf` as below.
```yaml
openapi: 3.0.0
info:
version: 1.0.0
title: AnyOf Schema
license:
name: MIT
paths:
/one-of-with-nullable-object:
get:
operationId: getOneOfWithNullableObject
tags:
- pets
description: |-
oneOf with nullable object.
responses:
'200':
description: Pet
content:
schema:
$ref: '#/components/schemas/Pet'
components:
schemas:
Pet:
oneOf:
- $ref: '#/components/schemas/Dog'
- $ref: '#/components/schemas/Cat'
Dog:
type: object
nullable: true
required:
- id
- name
properties:
id:
type: integer
format: int64
name:
type: string
Cat:
type: object
required:
- id
- category
properties:
id:
type: integer
format: int64
category:
type: string
```
In this case, the `mock` defined function cannot be spread and …
=> fix(msw): do not use spread objects if `nullable` object schema in `oneOf`

packages/angular/src/index.ts, samples/angular-app/src/api/endpoints/pets/pets.service.ts
READY
Fixes #1631 
- Updated `generateImplementation` to add function overloads when `isRequestOptions` is `true`.
- This ensures that when supplying `observe` to a request, it's return type will match what is returned by the `HttpClient`.
=> fix(angular): add request overloads based on observe property

packages/mock/src/faker/getters/combine.ts, tests/specifications/any-of.yaml
**READY**
fix #1508 
Previously, an `allOf` object was maked only if `oneOf` contained `allOf`, and `msw` would break when `anyOf` contained `allOf`. Therefore, i have fixed it so that `anyOf` now generates an `Allof` object just like `oneOf`.
`type: faker.word.sample(),name: faker.word.sample()` is not `object` so syntax error.
```ts
export const getGetAnyOfIncludedAllOfPetsResponseMock = (): Pet => (faker.helpers.arrayElement([{color: faker.word.sample()},type: faker.word.sample(),name: faker.word.sample()]))
```
`{type: faker.word.sample(),name: faker.word.sample()}` is `object` so there is no syntax error.
```ts
export const getGetAnyOfIncludedAllOfPetsResponseMock = (): Pet => (faker.helpers.arrayElement([{color: faker.word.sample()},{type: faker.word.sample(),name: …
```
=> fix(msw): fix break `msw` when `anyof` included `allof`

packages/mock/src/faker/getters/combine.ts, tests/specifications/all-of.yaml
fix #1119 
Fixed a syntax error that occurred when using `ref` in an item referenced by `allOf`.
The reference with `ref` is not necessarily an object, but there are few cases where `allOf` refers to an item other than an object, so this covers many cases.
`ref` objects will cause an syntax error.
```ts
export const getGetNestedRefInAllOfPetsResponseMock = (): GetNestedRefInAllOfPets200 => ({{id: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample()},tag: faker.word.sample()})
```
`ref` objects are expanded so no error occurs.
```ts
export const getGetNestedRefInAllOfPetsResponseMock = (): GetNestedRefInAllOfPets200 => ({...{id: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample()},tag: faker.word.sample()})
```
none
i …
=> fix(msw): `ref` in `allOf` expands the object

packages/mock/src/faker/resolvers/value.ts, samples/vue-query/vue-query-basic/petstore.yaml
fix #1620
**WIP** 
Fixes the issue mention in #1620. It now imports like this `import { DomainStatusEnum } from '.././model';` instead of `import { Domain.Status.Enum } from '.././model';`
It is realy difficult to check if I didn't broken anything after the change. When i ran  generate api  on vue-query sample it looked good and only added the  new correct import statments. Thats why i marked it as WIP. If you have tips to test it better please let me know.
=> fix(msw): Incorrect Import Generated for Enum in Mock Files

packages/core/src/getters/scalar.ts, tests/specifications/const.yaml
**READY**
Fixes #1647
I've expanded the `const` specification to include `false` and `0` constants. Before this change, the models were generated as:
```typescript
export interface BooleanConst {
value: true;
valueFalse: boolean;
valueNullable: BooleanConstValueNullable;
}
export interface IntegerConst {
value: 1;
valueNullable: IntegerConstValueNullable;
valueZero: number;
}
```
After this change, the models are generated as:
```typescript
export interface BooleanConst {
value: true;
valueFalse: false;
valueNullable: BooleanConstValueNullable;
}
export interface IntegerConst {
value: 1;
valueNullable: IntegerConstValueNullable;
valueZero: 0;
}
```
[PR that introduced the problem](https://github.com/orval-labs/orval/pull/1512)
```bash
> …
```
=> fix: Correctly set type for false or 0 constants

docs/src/pages/reference/configuration/output.md
**READY**
Small change to fix issue in the markdown format of the URL. 
Converts this
to 
```bash
```
1.
=> Fix small typo in the docs

packages/mock/src/faker/resolvers/value.ts, tests/specifications/any-of.yaml
**READY**
I fixed the syntax error when using `allOf` within `anyOf` and shared schema.
`TS1128: Declaration or statement expected.` occurred.
```ts
export const getGetPetsResponseMock = (
overrideResponse: Partial< Pet > = {}
): Pet => ({
detail: faker.helpers.arrayElement([
{ name: faker.word.sample() },
{ ,url: faker.word.sample()}
]),
...overrideResponse
})
```
It's correct
```ts
export const getGetPetsResponseMock = (
overrideResponse: Partial<Pet> = {},
): Pet => ({
detail: faker.helpers.arrayElement([
{ name: faker.word.sample() },
{ name: faker.word.sample(), url: faker.word.sample() },
]),
...overrideResponse,
});
```
| other_pr_master …
=> fix(msw): fix broken mocks when using 'allOf' within 'anyOf' and using a shared schema

docs/src/pages/guides/custom-client.md
**READY**
Fix the custom fetch client example to include a question mark before any query parameters. 
Closes https://github.com/orval-labs/orval/issues/1666 
Closes  https://github.com/orval-labs/orval/issues/482
=> Fix custom client example to include a question mark before query parameters

packages/mock/src/faker/getters/combine.ts, packages/mock/src/faker/getters/object.ts, packages/mock/src/faker/getters/scalar.ts
**READY**
Fixed bug when faker attempted to create mocked data, the schema had recursive references, where the name of the schema was changed when sanitized to pascal case. The bug was fixed with the change in ```packages\mock\src\faker\getters\scalar.ts:176```, but I found two checks to ```existingReferencedProperties``` in ```packages\mock\src\faker\getters\object.ts``` and ```packages\mock\src\faker\getters\combine.ts```, so I thought I would proactively fix them too
Here is a simplified, obfuscated version of the json that caused the issue. The sanitation changed ```Foo.Bar.MainMenuItemDTO``` to ```FooBarMainMenuItemDTO```, causing it to miss the check in ```existingReferencedProperties```
I ran this json in the react query sample to confirm the bug, and the fix
```json
{
"swagger": …
```
=> fix: faker recursive reference pascal sanitation

packages/mock/src/faker/getters/scalar.ts, tests/configs/mock.config.ts, tests/specifications/format.yaml
**READY**
Fix https://github.com/orval-labs/orval/issues/1472
If orval config uses override useBigInt, faker will be generated with faker.number.bigInt. I also added support for format double/float, to use faker.number.float. if useBigInt is not set, it will default back to faker.number.int
I appended the existing `tests/specifications/format.yaml`, and changed the name in `tests/configs/mock.config.ts` from **useDates**, to **formats**, to better reflect its content with the new test scenarios
Running locally against `tests/configs/mock.config.ts`, the config **formats** tests to generate the new number type/format combinations
=> fix: faker bigint support

packages/mock/src/faker/getters/scalar.ts
**READY**
With faker.string.alpha(20), you get a 20-character string using random letters from the alphabet. The chances of getting an identical string are astronomically low, given the vast number of possible combinations.
On the other hand, faker.word.sample() picks a word from a predefined list of words. The uniqueness of this function is limited to the size of that list. So, while it’s great for generating realistic and coherent words, it doesn’t offer the same level of uniqueness as generating a random string of 20 characters.
In summary:
faker.string.alpha(20): Super unique because of the high number of possible combinations.
faker.word.sample(): Limited uniqueness, depending on the list size. Ideal if you want sensible words rather than random strings.
Resolves …
=> mock strings fields as 20 char strings

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Orval Guru](https://gurubase.io/g/orval) to Gurubase. Orval Guru uses the data from this repo and data from the [docs](https://orval.dev) to answer questions by leveraging the LLM.
In this PR, I showcased the "Orval Guru", which highlights that Orval now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Orval …
=> Introducing Orval Guru on Gurubase.io

docs/src/pages/reference/configuration/input.md, packages/core/src/generators/schema-definition.test.ts, packages/core/src/generators/schema-definition.ts, packages/core/src/generators/verbs-options.test.ts, packages/core/src/generators/verbs-options.ts, packages/core/src/types.ts, packages/orval/src/import-open-api.ts, samples/basic/petstore.yaml, tests/configs/default.config.ts
**READY**
Fix https://github.com/orval-labs/orval/issues/1676
Extend the `filters` input option by introducing a `mode` optional parameter to specify if filtering should `include` or `exclude` tags or schemas.
| [yesyesufcurs:issues/739](https://github.com/yesyesufcurs/orval/tree/issues/739) | [link](https://github.com/anymaniax/orval/pull/810) |
Add a tag that should be filtered out to orval.config:
````js
output: {
mode: :"exclude"
tags: ["pets"]
},
````
Only endpoints that do not contain the tag "pets" will be generated.
=> feat(core): add mode include/exclude to input filters option

docs/src/pages/guides/fetch-client.md, docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/fetch/src/index.ts, packages/orval/src/utils/options.ts, packages/swr/src/client.ts, packages/swr/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/next-app-with-fetch/custom-fetch.ts, samples/react-app-with-swr/fetch-client/orval.config.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts
**READY**
fix #1694 
follow up #1695
#1695
none
=> feat(fetch): add response headers in fetch client

packages/core/src/utils/doc.ts
**READY**
Fix #1703 
if the `pattern` contains `*/` then orval produces TS files which have error due invalid comment parsing, these changes ensure to properly escape all JS doc strings .
=> Sanitize JS Doc strings

docs/src/pages/reference/configuration/output.md, packages/core/package.json, packages/core/src/types.ts, packages/orval/package.json, packages/orval/src/utils/options.ts, packages/orval/src/write-specs.ts, yarn.lock
**READY**
Generate docs from the output using TypeDoc.
Fixes: #773.
```bash
```
1. Open the `orval.config.ts` for an example and add `docs: true,` to the `output` object.
2. Run `yarn generate-api`.
3. The markdown docs should get built alongside the API files.
=> feat: generate API as `TypeDoc` docs

docs/src/pages/reference/configuration/output.md, packages/core/src/getters/route.test.ts, packages/core/src/getters/route.ts, packages/core/src/types.ts, packages/orval/src/api.ts, tests/configs/swr.config.ts, tests/specifications/url-paths.yaml
**READY**
Fix #1689 
This allows the user to specify whether or not they want to use the servers field as specified in the openapi spec.
The user can still use the old way of defining the baseUrl as a string for backwards compatibility. 
If the servers field contains a variable to be substituted, Orval tries to substitute it using the value that the user has defined in the configuration file. If the user has not defined that variable, the default value is used.
1. Define output.baseUrl in your config as 
```ts
baseUrl: {
getBaseUrlFromSpecification: true
}
```
2. Define servers in your specification, e.g.
```yaml
servers:
- url: https://api.example.com
```
3. Generate
4. Notice that the url in the generated getUrl functions (e.g. `getCreatePetUrl`) returns `'https://api.example.com/pets'`
=> feat(core): take servers fields into account

packages/core/src/getters/scalar.ts, tests/specifications/null-type.yaml
**READY**
Fixes #1738
yarn generate:default
check tests/generated/default/null-type/model/nullStringEnum.ts
make sure `| null` is added as expected.
=> fix(core): make sure to add '| null' to enums with null in type array

packages/core/src/generators/schema-definition.test.ts, packages/core/src/generators/schema-definition.ts
READY
Fixes #1736.  Fixes a regression between 7.2.0 and 7.3.0 that prevents  schema generation when `filters` is populated in the config but `filters.schemas` is not.
| [melloware:1736](https://github.com/melloware/orval/tree/1736) | #1740 |
```bash
yarn install
yarn run build
yarn run test
```
Tests will succeed
Undo changes in `schemas-generation.ts` and rebuild
Tests will fail
=> fix(core): generate schemas when filters.schemas undefined

packages/query/src/index.ts
**READY**
Right now we have an opportunity to override the type of `data` that is returned by the generated `useQuery` hooks using `TData` generic. It would be great to have the same opportunity with the `useMutation` hooks.
You can use samples tests
=> feat: TData generic for mutation hooks

packages/core/src/getters/array.ts
**READY**
Fixes #1433 
Apparently the `items` on array properties are no longer required in openapi 3.1
=> fix(core): add unknown[] when items is not defined

packages/core/src/writers/split-tags-mode.ts
fixes: #1547
**READY**
When generating .msw.ts files with npx orval, the import paths for schemas were incorrect. Specifically, the generated files would import schemas from the root index of the schemas directory (e.g., ../../schemas). However, the import paths should have pointed directly to the specific schema files, such as ../../schemas/addressGroups.
=> fix: correct imports in Mock handlers without index

packages/core/src/resolvers/object.ts
**READY**
Fixes #1662 
This was not only a problem in polymorphic schemas, but a problem overall when a object had an enum property and `useNativeEnums` was set to `true`
Follow example in linked issue
=> fix(core): make sure to keyof typeof native enums

docs/src/pages/reference/configuration/output.md, packages/core/src/getters/object.ts, packages/core/src/types.ts, packages/mock/src/faker/getters/object.ts, packages/orval/src/utils/options.ts
**READY/HOLD**
Fixes #1737 
Not sure if this is a good way to go, ordering of properties seems irrelevant in the end (no functionality difference), so I'm not sure if this is what we want. I'll let you Maintainers decide :)
=> feat(core): property sorting

docs/src/pages/guides/react-query.md, docs/src/pages/guides/svelte-query.md, docs/src/pages/guides/vue-query.md
**READY**
There is a typo in the documentation. `useInfinteQuery` -> `useInfiniteQuery`
=> Fix `useInfinteQuery` typo in documentation

packages/mock/src/faker/getters/object.ts
**READY**
During development I renamed an enum, but apparently missed a place where it was used.
Introduced in #1763
=> fix(core): fixed error where a renamed enum was used by old name

packages/fetch/src/index.ts
**READY**
Fixes #1743 
This specific code is only executed when a custom mutator is specified
=> fix(fetch): make sure to not double promise for custom fetch mutator

samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/react-query/form-data-mutator/endpoints.ts, samples/react-query/form-data-mutator/models/pet.ts, samples/react-query/form-data/endpoints.ts, samples/react-query/form-data/models/pet.ts, samples/react-query/form-url-encoded-mutator/endpoints.ts, samples/react-query/form-url-encoded-mutator/models/pet.ts, samples/react-query/form-url-encoded/endpoints.ts, samples/react-query/form-url-encoded/models/pet.ts, samples/react-query/hook-mutator/endpoints.ts, samples/react-query/hook-mutator/models/pet.ts
**READY**
The sample apps were old so I regenerated them with the `orval` latest version.
none
1. `cd samples`
2. `yarn generate-api --no-cache`
=> chore: regenerate sample apps

docs/src/pages/guides/fetch-client.md, packages/fetch/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts
**READY**
fix #1588 
The data type of the fetch response now includes the error type.
When you have multiple response types schema like a below:
```yaml
paths:
/pets:
get:
summary: List all pets
operationId: listPets
responses:
'200':
content:
schema:
$ref: '#/components/schemas/Pets'
'400':
content:
schema:
$ref: '#/components/schemas/BadRequest'
```
So far, orval has only generated success type:
```ts
export type listPetsResponse = {
data: Pets;
status: number;
headers: Headers;
};
```
From now on, it will generate a union that includes the error type
```ts
export type listPetsResponse = {
data: Pets | BadRequest;
status: number;
headers: Headers;
};
```
none
you can check by sample apps
=> feat(fetch): include error types in data type of fetch response

packages/fetch/src/index.ts, tests/configs/fetch.config.ts
**READY**
Passes headers to `fetch` when `headers` option is activated. 
Fixes #1779.
I have not tested the patch since the build system doesn't support the system I am on.
=> fix(fetch): pass headers to `fetch` when `headers` option is activated

docs/src/pages/guides/fetch-client.md, packages/fetch/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/react-app-with-swr/fetch-client/src/api/endpoints/swaggerPetstore.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts
**HOLD**
I'm waiting for more options to gather in #1656 
fix #1656
This avoids an exception that occurs when executing `res.json()` if there is no content in the response body.
```ts
export const listPets = async (
params?: ListPetsParams,
options?: RequestInit,
): Promise<listPetsResponse> => {
const res = await fetch(getListPetsUrl(params), {
...options,
method: 'GET',
});
-  const data: Pets = await res.json();
+  const data: Pets =
[204, 205, 304].includes(res.status) || !res.body ? {} : await res.json();
return { status: res.status, data, headers: res.headers };
};
```
none
you can check by sample apps
=> feat(fetch): avoid exception when the response body has no content

packages/zod/src/index.ts, tests/configs/fetch.config.ts, tests/configs/zod.config.ts, tests/specifications/import-from-subdirectory/petstore.yaml, tests/specifications/import-from-subdirectory/subdirectory/another-file.yaml, tests/specifications/import-from-subdirectory/subdirectory/petstore.yaml, yarn.lock
**READY**
This PR adds a new entry to `tests/configs/zod.config.ts` that shows a bug for `$ref` objects and fixes it
If we reference a schema in subdirectory, it works at least for React Query and Fetch, however it fails for Zod.
**UPD**: The solution to the bug is to get specKey key from resolved schema and use it to resolve its fields
=> fix(zod): pass resolved specKey in context

packages/core/src/generators/models-inline.ts
Fix #1382
**WIP**
Sometimes, when generating Orval schema, some generated types are moved around the file. This PR fixes it.
Related to issue [Types in generated react-query schema have unstable order, causing noisy diffs #1382 ](https://github.com/orval-labs/orval/issues/1382)
No related PRs
```bash
```
1.
=> Fix chaotic shuffle of generated types

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/core/src/writers/split-tags-mode.ts, packages/orval/src/utils/options.ts, tests/configs/default.config.ts
**READY/WIP**
Fixes #512 
Is `index.msw.ts` a good name? Or should it be something like `mocks.ts`?
1. yarn generate:mock
2. check generated/mock/petstore-tags-split and there is a `index.msw.ts` file which exports * from all .msw.ts files
=> feat(msw): create an index file exporting msw for split tags mode

packages/core/src/types.ts, packages/hono/src/index.ts, packages/orval/src/utils/options.ts
**READY**
Until now, `validator.ts` was output to the same directory as other files output to `target`.
In fact, `validator.ts` is only referenced in `handlers`, so I want to output it to the same hierarchy instead of `target`.
So I added an option to give me control over it.
```bash
src/
├── endpoints.context.ts
├── endpoints.ts
├── endpoints.validator.ts  <--- They are grouped under `target`
├── endpoints.zod.ts
└── handlers
```
After:
```bash
src/
├── endpoints.context.ts
├── endpoints.ts
├── endpoints.zod.ts
└── handlers
├── createPets.ts
├── deletePetById.ts
├── healthCheck.ts
├── listPets.ts
├── schemas
├── showPetById.ts
└── validator.ts  <--- By specifying the path, output will be under handlers.
```
None
The `hono` client hasn't yet been tests and docs, so I will add those in a …
=> feat(hono): add `orverride.hono.validatorOutputPath` option

packages/hono/src/index.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts, samples/hono/hono-with-fetch-client/hono-app/src/petstore.schemas.ts, samples/hono/hono-with-fetch-client/hono-app/src/petstore.validator.ts, samples/hono/hono-with-zod/src/petstore.schemas.ts
**READY**
This is to avoid the following lint error:
```
error TS7030: Not all code paths return a value.
```
And update sample apps.
```ts
petstoreSplitHandlers: {
input: '../specifications/petstore.yaml',
output: {
target: '../generated/hono/petstore-split-handlers/endpoints.ts',
schemas: '../generated/hono/petstore-split-handlers/handlers/schemas',
mode: 'split',
client: 'hono',
override: {
hono: {
handlers: '../generated/hono/petstore-split-handlers/handlers',
},
},
},
},
}
=> fix(hono): custom validator always does return value

packages/core/src/getters/combine.ts, tests/specifications/all-of.yaml
**READY**
Fixes #1670 
This allows spec to contain a `required` array either in parent object, or a sibling object inside the allOf:
```yaml
components:
schemas:
ContractPartial:
type: object
properties:
uuid:
type: string
description:
type: string
start_date:
type: string
format: date
end_date:
type: string
format: date
Contract:
type: object
allOf:
- $ref: '#/components/schemas/ContractPartial'
- type: object
properties:
active:
type: boolean
description: If this contract is current active.
required:
- description
- end_date
- start_date
- uuid
```
Would yield the same result as 
```yaml
components:
schemas:
ContractPartial:
type: object
properties:
uuid:
type: string
description:
type: string
start_date:
type: string
format: date
end_date:
type: string
format: date
Contract:
type: …
```
=> fix(core): export type with required properties in all-of object

packages/hono/src/index.ts
**READY**
`verbOption.body` always exists even if the request body does not exist, because it contains the following object:
```ts
verbOption.body {
originalSchema: undefined,
definition: '',
implementation: '',
imports: [],
schemas: [],
isOptional: false,
formData: '',
formUrlEncoded: '',
contentType: ''
}
```
Therefore, when checking whether the request body exists, `true` is always returned, which is not the intended result.
As a result, this resulted in an unnecessary `zValidator` being imported, which caused the following warning:
```
error TS6133: 'zValidator' is declared but its value is never read.
```
The intended behavior is achieved by checking whether `verbOption.body.definition` exists.
None
```ts
petstoreSplitHandlers: {
input: …
```
=> fix(hono): avoid unnecessary `zValidator` imports

packages/mock/package.json, packages/mock/src/faker/getters/route.test.ts, packages/mock/src/faker/getters/scalar.test.ts, packages/mock/src/faker/getters/scalar.ts
**READY**
Fixes https://github.com/orval-labs/orval/issues/1828
Although commit [6850e62](https://github.com/orval-labs/orval/pull/1829/commits/6850e6223b3f7e28621a3d785aba3589e155e2b0) is not directly related to fixing the issue, changes were made to enable tests in the mock package.
=> fix(mock): ensure getMockScalar respects custom overrides for int64 format

packages/hono/src/index.ts
**READY**
　
When i specify `tags` or `tags-split` as the `mode` with `hono` client, all handlers are imported into the split routing definition.
```ts
import {
healthCheckHandlers, // <--- occurred error
listPetsHandlers, 
createPetsHandlers, 
updatePetsHandlers, 
showPetByIdHandlers
} from './pets.handlers';
```
For example, Since `healthCheck` does not have the `pets` tag, an error occurs due to unnecessary import.
So I fixed it.
none
You can check this by using the `petstore` OpenAPI definition.
=> fix(hono): remove unnecessary handler import when `tags` mode

packages/core/src/getters/ref.ts
**READY**
Decode the URL encoded strings in the value of `$ref` to prevent an exception in case a parameter is referenced using ref to another request directly which already has a path parameters and { & } are URL encoded with %7B and %7D respectively.
Fix https://github.com/orval-labs/orval/issues/1834
Use orval to convert the schema present in the linked ticket
=> Decode URL encoded parts in  value

packages/core/src/resolvers/object.ts
**READY**
Fixes #1845 
Fixes the issue that was described in a comment in #1759, and later in issue #1845, where the fix became an issue when the type was an array with native enums
| fix/native-enums | [link](#1759) |
=> fix(core): parenthesize keyof typeof

packages/core/src/types.ts, packages/hono/src/index.ts, packages/orval/src/utils/options.ts
**READY**
When i use the `tags-split` option in the `hono` client to auto-generate, a route definition file is generated for each tag.
Therefore, i had to manually define imports for each tag and configure the `hono` app.
```bash
$ tree hono-app/src/ -L 3
hono-app/src/
└── tags-split
├── health
│   ├── health.context.ts
│   ├── health.handlers.ts
│   ├── health.ts              <--- health route definition file
│   └── health.zod.ts
├── pets
│   ├── pets.context.ts
│   ├── pets.handlers.ts
│   ├── pets.ts                <--- pets route definition file
│   └── pets.zod.ts
├── schemas
│   ├── createPetsBodyItem.ts
│   ├── error.ts
│   ├── index.ts
│   ├── listPetsParams.ts
│   ├── pet.ts
│   └── pets.ts
└── validator.ts
```
So, i added new option `orverride.hono.compositeRoutes`.
This will …
=> feat(hono): added the ability to generate composite routes with the `hono` client

docs/src/pages/reference/configuration/output.md
**READY**
Update docs to specify that param serializer is only valid for axios
=> fix(docs): update docs for param serializer

packages/core/src/generators/mutator.ts
**READY**
Resolves #1862
This PR fixes an issue in the code generation process where a custom instance hook returning a function wrapped in `useCallback` loses its second parameter.
=> fix(core): handle parameters in custom instance returning useCallback

packages/fetch/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/hono/hono-with-zod/src/petstore.validator.ts, samples/next-app-with-fetch/app/gen/pets/pets.msw.ts, samples/react-app-with-swr/fetch-client/src/api/endpoints/swaggerPetstore.ts, samples/react-query/custom-fetch/src/gen/pets/pets.msw.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.msw.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.msw.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.msw.ts
**READY**
fix #1854 
The automatically generated source code has been changed as follows.
```diff
+ const body = [204, 205, 304].includes(res.status) ? null : await res.text();
- const data: Pet = [204, 205, 304].includes(res.status) || !res.body ? {} : await res.json();
+ const data: showPetByIdResponse['data'] = body ? JSON.parse(body) : {};
-  return { status: res.status, data, headers: res.headers };
+  return { data, status: res.status, headers: res.headers } as showPetByIdResponse;
```
```diff
+ const body = [204, 205, 304].includes(res.status) ? null : await res.text();
- const data: Pet = [204, 205, 304].includes(res.status) || !res.body ? {} : await res.json();
+ const data: Pets = body ? JSON.parse(body) : {};
-  return data as Pets
+  return data;
```
- #1773
- #1776
Both …
=> fix(fetch): Improved error handling when body does not exist in `fetch` client

packages/query/src/index.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/react-query/form-data-mutator/endpoints.ts, samples/react-query/form-data/endpoints.ts, samples/react-query/form-url-encoded-mutator/endpoints.ts, samples/react-query/form-url-encoded/endpoints.ts, samples/react-query/hook-mutator/endpoints.ts, samples/svelte-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts, samples/vue-query/vue-query-basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
fix #1820
This is a revert of #1735.
#1805 was also partially reverted, but I did a complete revert with this PR.
In #1735, we tried to improve type safety, but it seems like we made a bug. I'm not expecting this problem, so I'll revert it.
- #1735 
- #1805 
You can check by tests and sample apps
=> fix(query): regression that breaks `TData` type check when using custom mutation

packages/core/src/getters/combine.ts, yarn.lock
**READY**
Fixes #1877 
Previously, `/generated/default/all-of/getNotHasPropertiesWithAllOfPets200.ts` had this generated code:
```ts
export type GetNotHasPropertiesWithAllOfPets200 = Pet &
PetDetail &
GetNotHasPropertiesWithAllOfPets200AllOf &
GetNotHasPropertiesWithAllOfPets200AllOfTwo &
Required<
Pick<
Pet &
PetDetail &
GetNotHasPropertiesWithAllOfPets200AllOf &
GetNotHasPropertiesWithAllOfPets200AllOfTwo,
'category' | 'color'
>
>;
```
The `Required<Pick<..., 'category' | 'color'>>` is unnecessary in this case, as both 'category' and 'color' is already required in `GetNotHasPropertiesWithAllOfPets200AllOf` and `GetNotHasPropertiesWithAllOfPets200AllOfTwo`.
This PR fixes that and only creates this `Required<Pick<` when there are non-required properties in a child object that should be …
=> fix(core): don't union required with already required props

packages/core/src/getters/combine.ts, packages/core/src/getters/object.ts, packages/core/src/resolvers/object.ts, packages/mock/src/faker/getters/scalar.ts, tests/specifications/enums.yaml, yarn.lock
**READY**
Fixes #1880 
This reverts #1860 and instead aims to fix the issue in a better way, by omitting the property in the parent object.
This also fixes issues with faker and native enums.
=> fix: adjustments to native enums

docs/src/components/Highlight.js
**READY**
When you start docs locally, you could see this warning log:
```
Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, className: ..., children: ..., style: ...};
<span {...props} />
React keys must be passed directly to JSX without using spread:
let props = {className: ..., children: ..., style: ...};
<span key={someKey} {...props} />
at Highlight (…/orval/docs/node_modules/prism-react-renderer/dist/index.cjs.js:198:15)
at Code (webpack-internal:///./src/components/Highlight.js:30:17)
at div
at div
at section
at div
at Home (webpack-internal:///./src/pages/index.js:43:13)
at SearchProvider (webpack-internal:///./src/components/useSearch.js:32:27)
at Hydrate (file:///.../orval/docs/node_modules/@tanstack/react-query/build/lib/Hydrate …
```
=> Warning: A props object containing a "key" prop is being spread into JSX

packages/core/package.json, packages/orval/src/write-specs.ts, yarn.lock
**READY**
A CVE from `json-path-plus` has been removed in the latest version of [@ibm-cloud/openapi-ruleset](https://github.com/IBM/openapi-validator/releases/tag/%40ibm-cloud%2Fopenapi-ruleset%401.29.1)
```bash
```
1.
=> chore: bump ibm-cloud dependencies

packages/hono/src/index.ts
**READY**
When using the `hono` client, the schema may not exist for both responses and requests, as shown below:
```yaml
paths:
/health:
get:
summary: health check
operationId: healthCheck
tags:
- health
responses:
'200':
description: A paged array of pets
content:
text/plain:
schema:
type: string
```
This will generate an empty zod file.
That caused an error and defined an unnecessary import.
```health.zod.ts:ts
/**
* Generated by orval v7.5.0 🍺
* Do not edit manually.
* Swagger Petstore
* OpenAPI spec version: 1.0.0
*/
import { z as zod } from 'zod';
```
> error TS6133: 'zod' is declared but its value is never read.
```health.handlers.ts:ts
import { createFactory } from 'hono/factory';
import { HealthCheckContext } from './health.context';
import {  } from './health.zod';
const factory …
```
=> fix(hono): remove unnecessary `zod` file and import

packages/core/src/generators/imports.ts, packages/core/src/generators/verbs-options.ts, packages/mock/src/msw/index.ts, packages/mock/src/msw/mocks.ts, tests/specifications/const.yaml
**READY**
PR in response to 
Fix https://github.com/orval-labs/orval/issues/1893
Fix for 2 bugs:
- shallow-copy during creation of overrides, which resulted in some props missing 
- mocks were not respecting "tags"
Outstanding work:
`````
output: {
override: {
query: {
useQuery: true,
useSuspenseQuery: true,
shouldExportHttpClient: false,
shouldExportQueryKey: false,
mutationOptions: {
path: '../src/integration/codegen-hooks.tsx',
name: 'invalidateAllCaches',
},
},
tags: {
MyCustomTag: {
query: {
useQuery: true,
useSuspenseQuery: true,
shouldExportHttpClient: false,
shouldExportQueryKey: false,
mutationOptions: {
path: '../src/integration/codegen-hooks.tsx',
name: 'invalidate',
}
}
},
`````
Results in incorrect path of "codegen-hooks":
``` …
```
=> fix(core): shallow-copy while creating override (global/tag/identifier)

packages/fetch/src/index.ts
**READY**
Sadly Safari below v17 does not support `URLSearchParams.size` therefore the fetch implementation is currently broken for those users.
This replaces the check for `size` with checking the stringification results length before returning the url.
See also: https://caniuse.com/mdn-api_urlsearchparams_size
- Tests (did not investigate but hopefully there is already one in place to catch regressions here)
- Documentation (probably not needed I guess)
1. create a fetch client
2. try to run a generated request on Safari 16 for exmaple
3. fails due to unsupported size API
If anything is missing just let me know :slightly_smiling_face:
=> fix(fetch): param stringification for Safari < 17.0

docs/src/pages/reference/configuration/input.md, packages/core/src/types.ts, packages/core/src/utils/validator.ts, packages/orval/src/import-open-api.ts
Fixes #1887
**READY**
This feature will give devs the ability to provide their own custom rulesets. Right now we always default to `@ibm-cloud/openapi-ruleset` with no way of modifying it
```ts
import { oas } from '@stoplight/spectral-rulesets';
export default {
extends: [oas],
rules: {
'operation-operationId': 'error',
},
};
```
```ts
import validation from './validate';
api: {
input: {
target: '../docs/swagger.json',
validation,
},
...
});
```
=> feat(core): ability to provide custom validation ruleset

packages/zod/src/index.ts, packages/zod/src/zod.test.ts, samples/hono/hono-with-zod/src/petstore.zod.ts
**READY**
Fix https://github.com/orval-labs/orval/pull/1907#issuecomment-2674233805 where strict() did not work correctly with discrinimatedUnions in zod due to how schemas were being merged
| other_pr_master     | [link](https://github.com/orval-labs/orval/pull/1907) |
Before:
Run from the samples/hono/hono-with-zod
```bash
npm run generate-api
```
1. See invalid typescript code
After
1. Repeat the same
2. See the new unit test for this case
=> fix(zod): strict true when using a discriminator

packages/core/package.json, packages/orval/package.json, packages/orval/src/write-specs.ts, yarn.lock
READY
Fix #1806
Bumped Typedoc version latest (0.27.6) to get its updated peer dependency for typescript 5.7.x . I reran all tests and update-sample to validate.
=> chore: Bump Typedoc version to 0.27.6

packages/hono/src/index.ts
**READY**
When the `hono` client uses `tags` or `tags-split` mode, an  error will occurs in handler file:
```bash
error TS2307: Cannot find module './pets.validator' or its corresponding type declarations.
2 import { zValidator } from './pets.validator';
~~~~~~~~~~~~~~~~~~
```
This is because the import source of `zValidator` is the name of the `tag`.
`validator` is a single commonly used file so i fixed it by changing the path to be calculated from `output.target`.
```bash
```
You can check by using …
=> fix(hono): `zValidate` path when using `tags` mode uses `output.target` based path

docs/src/components/playground/Playground.js
**READY**
Dropdown overlapped by editor sub-components
Need to go to playground section (https://orval.dev/ or https://orval.dev/playground) and try to scroll so scrolling header appears, and open "Choose Live Example" dropdown
=> fix(docs): dropdown overlap

tests/configs/hono.config.ts
Some bug fixes made it possible to add a standard test that didn't work before, so I added it
none
=> chore(hono): add tests for `hono` client

packages/core/src/getters/combine.ts, packages/core/src/getters/object.ts, packages/core/src/resolvers/object.ts, packages/mock/src/faker/getters/scalar.ts, tests/specifications/enums.yaml
Reverts orval-labs/orval#1882
Becouse, it seems that RangeError: Maximum call stack size exceeded has started to occur in my complex OpenAPI since this PR merged.
```
petstoreFile - RangeError: Maximum call stack size exceeded
at /app/packages/mock/dist/index.js:183:16
at Array.map (<anonymous>)
at getMockObject (/app/packages/mock/dist/index.js:159:36)
at getMockScalar (/app/packages/mock/dist/index.js:419:14)
at resolveMockValue (/app/packages/mock/dist/index.js:543:21)
at /app/packages/mock/dist/index.js:665:29
at Array.reduce (<anonymous>)
at combineSchemasMock (/app/packages/mock/dist/index.js:647:60)
at getMockObject (/app/packages/mock/dist/index.js:119:12)
at getMockScalar (/app/packages/mock/dist/index.js:419:14)
```
=> Revert "fix(core): adjustments to native enums"

packages/orval/src/generate.ts
READY
Orval was not exiting with status code `1` when there was an error. #1497 is similar (although that specific case is fixed now and can be closed)
Fix https://github.com/orval-labs/orval/issues/1497
(See exit codes at bottom of screenshots)
Before:
After:
=> fix: await asyncReduce in generateSpecs

packages/core/src/writers/schemas.ts
**READY**
Duplicate schema names were showing one less than the actual number of schemas (e.g. showing `1x` instead of `2x` when there were 2 schemas with the same name)
Another thought is that we should probably detect duplicate schemas even if `indexFiles` is set to `false`, but that breaks the (unsafe) workaround mentioned in #1733 
1. Edit `petstore.yaml`:
```diff
email:
type: string
format: email
+       calling_code:
+         type: number
+         enum: [1, 2, 3]
callingCode:
type: string
enum: ['+33', '+420', '+33'] # intentional duplicated value
```
2. generate orval with config that has indexFiles: true
3. Notice error
=> fix: display correct amount of duplicate schemas

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
**READY**
Fix https://github.com/orval-labs/orval/issues/1715
Adds parameter descriptions to generated zod definitions, using the `zod.describe("<string>")` function.
Example output:
```ts
export const addListQueryLimitRegExp = new RegExp('^\\+\\d{10, 15}');
export const addListQueryParams = zod.object({
"limit": zod.string().regex(addListQueryLimitRegExp).optional().describe('How many items to return at one time (max 100)'),
"birthdate": zod.string().date().optional().describe('birth date')
})
```
Reference docs: https://zod.dev/?id=describe
Found this before doing the work:
- https://github.com/orval-labs/orval/issues/1715
=> feat: Add descriptions for zod

docs/src/pages/reference/configuration/output.md, packages/query/src/index.ts, tests/configs/react-query.config.ts, tests/mutators/custom-mutation.ts
**READY**
* Correctly check `hasSecondArg` instead of `hasThirdArg` for `{ url: route }`.
* Replace `/${` with `/{`, since we don't actually have the actual parameters to replace in the path, which caused a syntax error
* Add third arg which includes properties about the operation
* Add docs highlighting how the mutator should look
=> fix(query): bugfix for custom mutator options

docs/src/pages/reference/configuration/output.md, packages/core/src/types.ts, packages/mock/src/faker/getters/scalar.ts, packages/orval/src/utils/options.ts, packages/zod/src/index.ts, tests/configs/zod.config.ts
**READY**
fix #1669 
i wanna use to `{offset: true}` in `datetime` function like this:
```ts
zod.object({
"id": zod.number().optional(),
"createdAt": zod.string().datetime({"offset":true}),
})
```
It still works as it is now and would be a breaking change, so we've made it optional.
none
You can check by the test case i added.
=> feat(zod): add `output.orverride.zod.datetimeOptions` option

packages/zod/src/index.ts
**READY**
Currently, `optional` is always define in generated `zod` schema when defined `default` in `OpenAPI`.
However, there are fields that I want to make required even though they have default values, so these do not need to be synced.
In the future, `required` definitions should always be prioritized to determine whether to apply `optional()`.
none
Here are some examples.
```yaml
Pet:
type: object
required:
- id
properties:
id:
type: integer
format: bigint
default: 0
```
```diff
export const listPetsResponseItem = zod.object({
- id: zod.number().optional(),
+ id: zod.number(),
});
```
```yaml
Pet:
type: object
required:
- name
properties:
id:
type: integer
format: bigint
default: 0
```
defined `optional()`
```ts
export const listPetsResponseItem = zod.object({
id: …
```
=> fix(zod): always prioritize `required` definitions to determine `optional()`

packages/query/src/index.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
Ready
Fix #1278
In Version 5 of TanStack Query, the API for providing a custom queryClient within hooks was changed so that it could be framework agnostic: https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5#removed-custom-context-prop-in-favor-of-custom-queryclient-instance.
https://tanstack.com/query/v5/docs/framework/svelte/reference/functions/createquery
https://tanstack.com/query/v5/docs/framework/react/reference/useQuery
This is a critical feature that allows for the use of the generated hooks outside of the component context.
This PR attempts to update the generated functions to account for this optional argument when v5 is detected.
| …
=> feat(query): add optional queryClient argument when using TanStack Query v5

packages/query/src/index.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
Ready
Expansion on https://github.com/orval-labs/orval/pull/1992 to add similar argument injection for mutation functions.
```bash
```
1.
=> feat(query): add optional queryClient argument to mutations when using TanStack v5

docs/src/pages/guides/custom-client.md
The usage is incorrect and according to docs the first element should be the url
https://github.com/PWNDAO/pwn-sdks/commit/6a2809cc4448bae2f39a637efe85def3debe4d54#diff-0fea3ac51887bbd80168c7716f7886d140606eeda3fe575f32f4f69020ba0296R29
Later I also adjusted parameters to remove data propery and rely on body because encoding happens before calling custom-client
=> docs(custom-client): update example to match the generated api

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
READY
Fix #1995 
Generate enum schema properly for various types (including `any`).
N/A
See #1995
=> fix(zod): enum schema generation for various types

packages/zod/src/index.ts, tests/specifications/typed-arrays-tuples-v3-1.yaml
READY
fix an issue where Zod code generation from `prefixItems` is not working correctly. https://github.com/orval-labs/orval/issues/1961
=> fix(zod): Correct zod code generation from prefixItems

packages/mock/src/faker/getters/scalar.ts, packages/zod/src/index.ts, packages/zod/src/zod.test.ts, tests/configs/zod.config.ts, tests/specifications/enums.yaml, yarn.lock
READY
This PR fixes two issues:
1. Corrects a mistake in #1996 I previously submitted. I had mistakenly used `zod.enum` with non-string values, which is not supported. This resulted in generated TypeScript code that fails to build. Apologies for the oversight.
2. A bug in the mock data generation when enums contained a mix of string and number values.
The latter was found when I added a test case for enums.yaml.
N/A
1. When the schema has an enum with non-string values, the generated Zod schema was incorrect:
```yaml
schema:
enum:
- 1
- 2
- 3
```
Generated (incorrectly)
```typescript
z.enum([1,2,3])
```
2. When the schema has an enum containing both strings and numbers, incorrect mock code was generated.
See enums.yaml for the specific case.
=> Fix enum generation

CONTRIBUTING.md
CONTRIBUTING.md states that PRs should target `main` branch, but there is no `main`. I think this should be `master`?
=> docs: fix branch name in CONTRIBUTING.md

packages/query/src/client.ts
**READY**
Fix #1872 
| N/A| N/A |
※ I did tests with husky and generating samples made from my project
1. make files to set override: mutator, formData and query.
2. make orval.config.ts with property below:
````
client: 'vue-query',
override: {
mutator: {
path: "./mutator/use-custom-instance.ts",
name: "useCustomInstance",
},
formData: {
path: "./mutator/custom-form-data.ts",
name: "customFormData",
},
query: {
queryOptions: {
path: "./mutator/custom-query-options.ts",
name: "customQueryOptions",
},
}
````
3. generate.
Before fix, it will generate file using method "useCallback" on all client.
After fix, it will generate file without useCallback on vue-query client while the …
=> fix(query): vue-query generates undefined function "useCallback"

samples/next-app-with-fetch/custom-fetch.ts
Described a bug in the NextJs examples where tag revalidation wasn't working
Fix https://github.com/orval-labs/orval/issues/2011
This single line change fixes the issue
=> Fix next js example for tag revalidation

docs/src/pages/reference/configuration/output.md
**READY**
Fix: https://github.com/orval-labs/orval/issues/2014
This pull request updates a small inconsistency in the documentation examples — replacing `'.//gen/endpoints'` with `'./gen/endpoints'.`
While both technically work, ./ is the standard and clearer notation, improving readability and avoiding confusion for new users.
For reference, the configuration options being updated are part of the [Output Configuration](https://orval.dev/reference/configuration/output#fileextension) and [Naming Convention](https://orval.dev/reference/configuration/output#namingconvention) sections.
N/A
N/A
=> docs: fix incorrect path example from './/' to './'

packages/core/src/types.ts, packages/mcp/README.md, packages/mcp/package.json, packages/mcp/src/index.ts, packages/mcp/tsconfig.json, packages/orval/package.json, packages/orval/src/client.ts, yarn.lock
**READY**
fix #1997
Add a new client that runs only in `single` mode as an `mcp` server.
```ts
mcpDev: {
input: {
},
output: {
mode: 'single',
client: 'mcp',
baseUrl: 'http://localhost:3000',
target: 'src/gen/handlers.ts',
schemas: 'src/gen/http-schemas',
},
}
})
```
The following files will be generated:
```
src/gen/
├── handlers.ts                    // Calls the fetch client and returns the value. Handler referenced from MCP tools
├── http-client.ts                 // fetch clients
├── http-schemas                   // Schema referenced by the fetch client
│   ├── createPetsBodyItem.ts
│   ├── error.ts
│   ├── index.ts
│   ├── listPetsParams.ts
│   ├── pet.ts
│   ├── pets.ts
│   └── …
```
=> feat: support new client `mcp` server 

packages/query/src/client.ts
**READY**
Fixes https://github.com/orval-labs/orval/issues/2013
This PR ensures that the default axios client is no longer exported when `output.override.query.shouldExportHttpClient` is set to `false`.
Previously, the default axios function was always exported unless a custom mutator was defined.  
This change fixes that inconsistency, allowing generated code to omit the axios export as intended — especially useful in environments like TanStack Query hooks where internal axios usage should be encapsulated.
To test this behavior, modify `samples/react-query/orval.config.ts` **without specifying `override.mutator`**:
```ts
override: {
query: {
shouldExportHttpClient: false,
},
// ❌ No mutator is defined
},
```
Then run:
```bash
> yarn dev
```
The generated function should **not be …
=> prevent default axios client from being exported when `shouldExportHttpClient` is false

packages/mcp/src/index.ts
**READY**
follow #1997.
I fix to only import necessary schemas.
For example:
```ts
import {
Pet,   // unnecessary
Pets, // unnecessary
ListPetsParams,
CreatePetsParams,
CreatePetsBody
} from './http-schemas';
```
```ts
import {
ListPetsParams,
CreatePetsParams,
CreatePetsBody
} from './http-schemas';
```
I'll add test in another PR.
=> fix: fix to import only the necessary schema

docs/src/pages/reference/configuration/output.md, packages/query/src/index.ts
**READY**
Fix #2025
Ensures that only one of the queries or mutations are generated, giving priority to queries.
Run on the test repo that shows the bug in action
https://github.com/Edward-Upton/orval-duplicate-hook-bug
=> fix(query): prioritize query over mutation for non-GET operations in generateQueryHook

packages/orval/src/utils/options.ts
**READY**
When you try to pass a custom mock generator into options (`output.mock` property), it is removed by the `normalizeOptions` function. 
You can find the difference by looking at the `tests/generated/mock/petstore-custom-mock-builder/endpoints.ts`, there are missing lines:
```ts
const listPetsMockHandler = () => { return { data: { id: 1, name: "myName" } } }
const createPetsMockHandler = () => { return { data: { id: 1, name: "myName" } } }
const showPetByIdMockHandler = () => { return { data: { id: 1, name: "myName" } } }
const deletePetByIdMockHandler = () => { return { data: { id: 1, name: "myName" } } }
const healthCheckMockHandler = () => { return { data: { id: 1, name: "myName" } } }
export const getSwaggerPetstoreMock = () => [
listPetsMockHandler(),
createPetsMockHandler(), …
```
=> fix(mock): allow to pass custom mock generator to options

packages/core/src/generators/verbs-options.ts
**READY**
Fix #552 
The current behaviour is really strange when overriding `operationName` in `output`, see this related issue: https://github.com/orval-labs/orval/issues/552
Maybe I should add in documentation that  when overriding, you need to sanitize on your side
```bash
```
1.
=> fix(core): no not sanitize operationName when overridden

packages/mcp/src/index.ts
**READY**
fix #1997 
I fixed a bug in `mcp` where the `baseUrl` and `servers` settings were not included in the route path.
When i setting `baseUrl` in config:
route is `pet/findByStatus`.
route is `https://petstore3.swagger.io/api/v3/pet/findByStatus`
You can check this by using the following config:
```
mcp: {
input: {
},
output: {
mode: 'single',
client: 'mcp',
baseUrl: 'https://petstore3.swagger.io/api/v3',
target: 'src/handlers.ts',
schemas: 'src/http-schemas',
clean: true,
},
},
});
```
=> fix(mcp): include `baseUrl` and `servers` settings in the route path

docs/public/sitemap.xml, docs/src/manifests/manifest.json, docs/src/pages/guides/hono.md, docs/src/pages/guides/mcp.md, samples/mcp/petstore/README.md
**READY**
fix #1997 
I've added the `mcp` guide and made some small modifications to the sample app `mcp-petstore`.
none
none
=> docs(mcp): add `mcp` guide

packages/query/src/index.ts
READY
Fix #1377 
Current code generates invalid JavaScript when using dot-notation in useInfiniteQueryParam:
```javascript
const queryFn = ({ signal, pageParam }) => 
exampleEndpoint(
{ ...params, pagination.page: pageParam || params?.['pagination.page']}, // ❌ syntax error
{ signal, ...axiosOptions }
);
```
This syntax is invalid as dot-notation property names must be quoted or wrapped in brackets in object literals.
The fix quotes the property name:
```javascript
const queryFn = ({ signal, pageParam }) => 
exampleEndpoint(
{ ...params, 'pagination.page': pageParam || params?.['pagination.page']}, // ✅ quoted key prevents syntax error
{ signal, ...axiosOptions }
);
```
Possible fix for https://github.com/orval-labs/orval/issues/1377
Auto‑closing keywords were intentionally omitted …
=> fix(query): properly handle dot-notation property names in useInfiniteQueryParam generation

packages/query/src/index.ts
READY
Fixes https://github.com/orval-labs/orval/issues/2051
This PR improves the prefetch generation behavior for `suspenseQuery` and `suspenseInfiniteQuery`.
Previously, prefetch hooks were only generated when `useQuery` or `useInfiniteQuery` was used. 
Now, prefetch hooks are also generated when only `useSuspenseQuery` or `useSuspenseInfiniteQuery` is enabled.
In addition, to avoid generating duplicate prefetch hooks when both `useQuery` and `useSuspenseQuery` (or both `useInfiniteQuery` and `useSuspenseInfiniteQuery`) are used, the hook is generated only once.
1. In `samples/react-query/orval.config.ts`, add the following override:
```ts
override: {
query: {
usePrefetch,
},
},
```
2. Confirm that:
- One prefetch function is generated for each `query` and `infiniteQuery`.
- Prefetch …
=> Support prefetch for suspenseQuery and suspenseInfiniteQuery

packages/zod/src/compatibleV4.test.ts, packages/zod/src/compatibleV4.ts, packages/zod/src/index.ts
**READY**
fix #2042 
I added an implementation to maintain compatibility between v3 and v4.
The implementation is modeled after the query package.
https://github.com/orval-labs/orval/blob/master/packages/query/src/index.ts#L337-L350
Because, the way string format is defined will change in zod v4.
https://v4.zod.dev/v4/changelog#zstring-updates
```ts
z.string().email(); // ❌ deprecated
z.email(); // ✅ 
```
none
You can check this in the unit test I added.
=> feat(zod): implemented string format compatible with zod v3 and v4

packages/orval/src/utils/package-json.ts
READY
Fix https://github.com/orval-labs/orval/pull/1989
It's currently reading the "keys" of dependencies rather than values.
| feat/pnpm-catalog | https://github.com/orval-labs/orval/pull/1989 |
=> fix(core): fix pnpm catalog detection

packages/zod/src/compatibleV4.test.ts, packages/zod/src/compatibleV4.ts, packages/zod/src/index.ts
**READY**
fix #2042 
I've implemented v4 compatibility for `date` and `datetime`
```ts
// v3
z.string().date()
z.string().datetime()
// v4
z.iso.date()
z.iso.datetime()
```
Ref: https://v4.zod.dev/v4/changelog#zstring-updates
none
You can check this in the unit test I added.
=> feat(zod): v4 compatible format `date` and `datetime`

packages/zod/src/compatibleV4.test.ts, packages/zod/src/compatibleV4.ts, packages/zod/src/index.ts
**READY**
I added support for string format `time` of `zod`
none
You can check this by defining `format: time` in `openapi`
=> feat(zod): support for string format `time`

packages/query/src/index.ts
**READY**
Solve conflict when bot useMutation and useQuery are set when override by operation
=> fix(query): override operation mutation and query conflict

packages/zod/src/compatibleV4.test.ts, packages/zod/src/compatibleV4.ts, packages/zod/src/index.ts, packages/zod/src/zod.test.ts
**HOLD**
fix #2042 
In zod v4, `object().strict()` is deprecated, use `strictObject()` instead.
https://v4.zod.dev/v4/changelog#deprecates-strict
```
// Zod 3
z.object({ name: z.string() }).strict();
// Zod 4
z.strictObject({ name: z.string() });
```
none
You can check this in the unit test I added.
=> feat(zod): In v4, `object().strict()` is deprecated, use `strictObject()` instead.

packages/core/src/getters/props.ts, yarn.lock
**READY**
`allParamsOptional` was not being considered when creating `queryParamsProp` in `props.ts`
fixes #2087
=>  fix(core): Updated queryParamsProp with allParamsOptional check 

packages/query/src/index.ts
Previously, when `useQuery` was explicitly set to `false` in a per-operation override, `useInfinite` (and other query-related flags) were ignored, and no hooks were generated.
This fix ensures that any query-related flag (e.g., `useInfinite`, `useSuspenseQuery`, etc.) correctly contributes to `isQuery`, even when `useQuery` is false.
Fixes: [#2088](https://github.com/orval-labs/orval/issues/2088)
---
**READY**
This PR updates the `isQuery` logic to accumulate all query-related flags when the HTTP verb is `GET`, instead of allowing `useQuery: false` to inadvertently disable hook generation entirely.
_None._
1. Set a per-operation override like:
```ts
operations: {
listPets: {
query: {
useQuery: false,
useInfinite: true,
useInfiniteQueryParam: "nextCursor"
}
}
}
```
2. Run Orval generator …
=> fix(query): allow useInfinite without useQuery in operation overrides

packages/mock/src/faker/getters/scalar.test.ts, packages/mock/src/faker/getters/scalar.ts
**READY**
Properties with falsy examples (like a boolean with `false` or a nullable prop with `null`) didn't generate the mock with those examples and put a faker boolean call instead. This PR take into account those values.
None
Test were added. Anyway, just a property like this reproduces the error:
```
"isEnabled": {
"type": "boolean",
"example": false
},
=> fix(mock): falsy examples were ignored

packages/core/src/generators/interface.test.ts, packages/core/src/generators/interface.ts
**READY**
In a regular object, members cannot be declared as optional. This is incorrect:
```ts
const a = { b?: 42 }
```
Optionals can be used only in types. This is causing a TS error number 1162 since `7.6.0` an issue when generating the schema files.
Fixes #2078
None
Try with an schema like this:
```
"UserValidation": {
"properties": {
"type": {
"type": "string",
"const": "valid",
"title": "Type",
"default": "valid"
}
},
"type": "object",
"title": "UserValidation",
"description": "This object is provided if the user has been validated."
},
```
=> fix(core): an object member cannot be declared optional

packages/mock/src/faker/getters/scalar.ts, packages/mock/src/msw/mocks.ts, packages/orval/src/utils/options.ts, samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
**READY**
Fixes #2129
Use minItems and maxItems properties when mocking arrays. arrayMin and arrayMax options can still be used to override these. Removed default arrayMin and arrayMax values from normalizedOptions so we can detect when they are not set. Fallback values are handled when values are actually used further down the code.
--
Build repo and use minItems and maxItems in yaml for array types.
=> fix: use minItems and maxItems when mocking arrays

packages/core/src/getters/object.ts, packages/core/src/getters/res-req-types.test.ts, packages/core/src/getters/res-req-types.ts
fix: avoid to include read only properties to request with multipart/form-data (
Fix #2089
**READY**
Fixes read only fields being incorrectly included into the params of requests with multipart/form-data.
=> fix: avoid to include read only properties to request with multipart/form-data

packages/query/src/index.ts
**READY**
Fixes https://github.com/orval-labs/orval/issues/2145
Starting from TanStack Query v5.80.0, [PR #9224](https://github.com/TanStack/query/pull/9224) removed the unnecessary TQueryData generic from InfiniteQueryObserverOptions, reducing the number of type parameters from 6 to 5. This change causes type errors in Orval-generated code.
This fix adds version detection to conditionally generate the correct number of type arguments:
- For v5.80.0 and later: generates 5 arguments (excluding the redundant funcReturnType)
- For earlier versions: retains 6 arguments for backward compatibility
1. Set the @tanstack/react-query (or vue-query, svelte-query) package version to below 5.80.0 (e.g., 5.79.0)
2. Run Orval – generated code should use 6 type arguments in UseInfiniteQueryOptions
3. Set …
=> fix(query): resolve UseInfiniteQueryOptions type error with TanStack Query v5.80.0+

packages/core/src/types.ts, packages/orval/src/client.ts, packages/query/src/index.ts
**READY**
Current behavior: Even with override.query.version being set to `3`, it's generating react-query code with `@tanstack/react-query` imports.
Update: I've now made sure to use the overridden version to determine the query version
1. Following the steps in this issue, set up the orval.config.ts file and provide an overridden react-query version set to 3. Notice `@tanstack/react-query` being imported in the generated code
=> fix: assert query version takes overriden as priority

packages/mock/src/faker/getters/combine.ts, tests/configs/default.config.ts, tests/specifications/one-of-nested.yaml
**READY**
Fixes https://github.com/orval-labs/orval/issues/2184
Generated code before supported by this PR:
```javascript
export const getExampleResponseExample2Mock = (overrideResponse: Partial<Example2> = {}): Example2 => ({...{kind: faker.helpers.arrayElement(['example2'] as const), expiry: {...{faker.helpers.arrayElement([{...getExampleResponsePointInFutureAbsoluteMock()},{...getExampleResponsePointInFutureRelativeMock()},])},}}, ...overrideResponse});
```
After this PR (You can see at `one-of-nested` test)
```javascript
export const getExampleResponseExample2Mock = (overrideResponse: Partial<Example2> = …
```
=> fix oneOf faker generation (#2184)

docs/src/styles/index.css
**READY**
This PR fixes a visual issue where the search results and recent searches in the DocSearch component appear transparent or difficult to read when hovered or selected.
During investigation, I noticed that no explicit `:hover` or `[aria-selected="true"]` styles were defined locally. However, in the browser DevTools, the visual effect was reproducible and likely caused by internal styles from Algolia’s DocSearch library — specifically, a transparent `--hover-overlay` variable or similar styling.
To address this, I applied a scoped CSS override to ensure that both `:hover` and `aria-selected="true"` states have a solid, readable background color with full opacity.
---
| N/A                 | N/A      |
---
--- …
=> fix: remove transparency from search results and recents on hover

packages/query/src/index.ts
Fix #2227 
This is a fix for #2227 where compilation changes the intentional code. By adding the correct code it should not be mangled anymore and stay exactly as intended.
I noticed i had to add to main package.json a resolution that ansi-styles stays on v4 since v5 is ESM. Not sure if thats only for me?
Also the naming `override` in the Orval config, and the naming override in `GeneratorVerbOptions` in the @orval/query library is **very confusing** since its not that override :) that actual override is in the second argument, which are the `GeneratorOptions`, which is the actual operational override you set in your config :exploding_head:.
_Will try this version in our own codebase first (_pnpm way it is correct for my apps now_), maybe we can also get an alpha since not easy to rewire …
=> Fix for #2227 - correctly using the operations override

packages/fetch/src/index.ts, samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.ts, samples/next-app-with-fetch/app/gen/pets/pets.ts, samples/react-app-with-swr/fetch-client/src/api/endpoints/swaggerPetstore.ts, samples/react-query/custom-fetch/src/gen/pets/pets.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.ts
**HOLD**
fix #2266
I added a condition to the fetch client to check if the schema is an array type when determining if it is an `explode` query parameter.
Because, in #1604, the fetch client added support for `explode` for array-type query parameters.
The default behavior for query parameters that didn't specify `explode` was the same as `false`, but since #2143, `explode` is now treated the same as `true`.
As a result, query parameters that were not of type Array were also treated as `explode`, which caused an issue where query parameters did not work.
- #1604 
- #2143 
It will be automatically generated using the sample definition below:
The …
=> fix(fetch):  `explode` params only target `Array` schema

docs/src/pages/reference/configuration/output.md, packages/fetch/src/index.ts, packages/orval/src/utils/options.ts
**READY**
Starting with #2143, the fetch client has changed so that array query parameters without the explode option behave the same as when explode is true. 
The previous behavior was the same as when explode is false, so we've added the `override.fetch.explode` option to maintain compatibility.
The default for `override.fetch.explode` is `false`.
When `override.fetch.explode` is `false`, array query parameters without explode specified behave the same as when explode is `true`.
It would be confusing to have the same behavior as if explode was `true` even though it was set to `false`, so I changed the default value from `false` to `true` to change the meaning.
- `override.fetch.explode` defaults to `false`
- When `override.fetch.explode` is `false`, array query parameters without the …
=> feat(fetch): changed default value of `override.fetch.explode` from `false` to `true` to clarify its meaning

docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/output.md, packages/core/src/generators/interface.ts, packages/core/src/getters/params.ts, packages/core/src/types.ts, packages/core/src/utils/logger.ts, packages/orval/src/bin/orval.ts, packages/orval/src/utils/options.ts, tests/configs/default.config.ts
**READY**
As discussed in #2246 I've removed tslint. 
This is a breaking change. But don't think at lot of people use tslint anymore.
=> feat: remove tslint

packages/core/src/writers/generate-imports-for-builder.ts
This PR fixes an issue where the file name casing in generated import statements did not match the actual file casing on disk. This resolves problems on case-sensitive file systems.
Fix #2312
- Removed the automatic `camelCase` transformation from `generateImportsForBuilder` in `packages/core/src/writers/generate-imports-for-builder.ts`.
---
Please review and let me know if any changes are required!
=> fix: case-senstive for generated imports

packages/core/package.json, packages/core/src/types.ts, packages/orval/package.json, packages/orval/src/import-open-api.ts, yarn.lock
Fixes #2349
**READY**
Fixes a potential hang during schema validation by updating to v12.0.0 of `@apidevtools/swagger-parser`.
=> Update orval to Swagger Parser v12.0.0

packages/axios/src/index.ts
**READY**
When a mutator has a second parameter, the generated `options` was typed as `SecondParameter<typeof mutator>`, which drops the mutator's generic and widens the options type. That prevents strongly-typed per-endpoint config.
Instantiate the mutator with the endpoint success type when extracting the second parameter:
```ts
SecondParameter<typeof mutator<SuccessType>>
```
This preserves the correct, strongly-typed options.
Closes #2351.
=> fix(axios): provide type parameter when inferring mutator `options` type

packages/mock/src/faker/getters/scalar.test.ts, packages/mock/src/faker/getters/scalar.ts
Fixes #2353
**READY**
This PR fixes an issue where MSW mock generation produces `multipleOf: undefined` for integer types when using Faker.js v9+. This causes TypeScript compilation errors when `exactOptionalPropertyTypes: true` is enabled in tsconfig. The fix adds a conditional check to only include the `multipleOf` parameter when it has a defined value.
| N/A                 | N/A      |
1. Create an OpenAPI schema with an integer field without a `multipleOf` property
2. Generate MSW mocks using Orval v7.10.0+ with Faker.js v9+
3. Enable `exactOptionalPropertyTypes: true` in your tsconfig.json
4. Before this fix: TypeScript …
=> fix(mock): prevent multipleOf undefined in MSW mock generation for integer types

.github/workflows/deploy-doc.yaml, .github/workflows/tests.yaml
**READY**
Updates to setup-node@5 which comes with caching on my default
https://github.com/actions/setup-node/releases/tag/v5.0.0
However this completely breaks when using yarn
- https://github.com/actions/setup-node/issues/1357
So more workarounds needs to be applied
- #2357
=> chore(ci): update to setup-node@5

.vscode/settings.json, packages/orval/package.json, tsconfig.base.json
**READY**
The orval package was still using the old tsup path to index.d.ts
=> fix(orval): corrected path to d.ts types

package.json, turbo.json
**READY**
Use yarn to run the clean/nuke scripts as turbo would fail to delete itself and other issues preventing the succesful rimraf-ing
Had to remove the root `nuke` script as it would remove the root node_modules folder first causing it to fail.
`nuke:all` will still nuke the root workspace
=> chore: use yarn to run clean/nuke scripts

package.json
Removes yarn restriction from devEngines as release-it uses npm which caused the release flow to fail.
Upstream issue filed: https://github.com/release-it/release-it/issues/1249
=> chore: removes yarn restriction as release-it uses npm

.yarnrc.yml
when publishing `@scoped` packages, like `@orval/...`, they default to restricted and must be manually set to public
https://yarnpkg.com/configuration/yarnrc#npmPublishAccess
=> chore: set published packages to access=public
