src/bin/orval-import.ts, src/bin/orval.ts, src/core/validators/ibm-openapi-validator.ts, src/core/writers/writeSpecs.ts, src/utils/messages/inline.ts, src/utils/messages/logs.ts, src/utils/packages.ts
Centralizes all system logs #8
=> feat(logs): centralizes all system logs

src/constants/index.ts, src/core/generators/generateAxios.ts, src/core/generators/generateVerbsOptions.ts, src/types/generator.ts, src/types/index.ts
=> fix(generator): better handling body

README.md, examples/orval.config.js, package.json, src/constants/index.ts, src/core/generators/generateApi.ts, src/core/generators/generateMocks.ts, src/core/generators/generateVerbsOptions.ts, src/core/getters/getMockScalar.ts, src/core/importers/importOpenApi.ts, src/core/importers/importSpecs.ts, src/core/writers/writeSpecs.ts, src/types/index.ts, src/utils/extension.ts
**READY**
refactor orval config to add an input and output configuration
=> refactor(orval-config): add an input and output gesture by project

README.md, examples/orval.config.js, src/core/generators/client.ts, src/core/generators/imports.ts, src/core/writers/specs.ts, src/types/index.ts
**READY**
add a split mode that split the definition, implementation, schemas and mocks in differents files
#5
=> feat(output): split mode

src/core/generators/interface.ts
**READY**
Filter out imports that refer to the type defined in current file (OpenAPI recursive schema definitions)
=> Filter out imports that refer to the type defined in current file

src/core/generators/interface.ts, src/core/generators/schemaDefinition.ts, src/core/getters/array.ts, src/core/getters/combine.ts, src/core/getters/object.ts, src/core/getters/params.ts, src/core/getters/queryParams.ts, src/core/getters/resReqTypes.ts, src/core/getters/scalar.ts, src/core/resolvers/object.ts, src/core/resolvers/value.ts
**READY**
Refactor to create a new enum if you need to combine multiple enums with allOf, oneOf and anyOf
=> feat(generator-schema): handle combined enums

docs/src/pages/reference/configuration.md
I think the mutator config only on output, not input
=> fix mutator example

src/core/getters/object.ts
**READY**
fixed missed {} when properties attribute is an empty object
#125
=> fixed missed {} when properties attribute is an empty object

src/core/generators/client.ts, src/types/generator.ts, src/types/index.ts
**READY**
add the ability to provide your own client
=> feat(generator): add ability to provide your own client

src/core/importers/specs.ts
**READY**
fixes imports bug, #132
https://github.com/anymaniax/orval/issues/132#issuecomment-846616351
=> fixing slashes bug in specs.ts

docs/src/components/Toc.js
**READY**
Official doc app crashes on React-query page
[Issue #148](https://github.com/anymaniax/orval/issues/148)
=> fix(docs): url of null

src/core/generators/query.ts
=> Support custom queryKeys

src/core/generators/query.ts
=> fix: remove P extends unknown check from SecondParameter

docs/src/pages/reference/configuration/overview.md
**READY**
Fixes a typo in docs. you
=> doc: fix typo

src/index.ts
**READY**
I wanted to create my own implementation of a ClientGenerator, but any types are hidden and never exported, with this PR I want just want to export more types.
(not sure if I need any of the todos)
=> feat: export generator types

README.md, docs/src/pages/guides/angular.md, docs/src/pages/guides/basics.md, docs/src/pages/guides/react-query.md, docs/src/pages/guides/svelte-query.md, docs/src/pages/index.js, docs/src/pages/installation.md, docs/src/pages/overview.md, docs/src/pages/quick-start.md, docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/input.md, docs/src/pages/reference/configuration/output.md, docs/src/pages/reference/configuration/overview.md, docs/src/pages/reference/integration.md
WIP
Improve the documentation
n/a
```bash
```
=> Improve documentation

src/core/generators/formData.ts
Really sorry for the mistake
branch | PR
```bash
```
1.
=> Fix formData non-required fields

docs/src/pages/guides/react-query.md, docs/src/pages/guides/svelte-query.md, docs/src/pages/guides/vue-query.md, docs/src/pages/reference/configuration/output.md
=> fix typo (prefered -> preferred)

docs/src/pages/guides/set-base-url.md
**READY**
Fix a minor typo in the docs
=> Docs set base url: Fix minor typo

docs/src/pages/overview.md
Fix for a broken link to swagger editor in the docs
=> Fix broken link to swagger editor

docs/src/pages/guides/basics.md, docs/src/pages/overview.md
This fixes the link to input configuration. The current link leads to a 404 page.
=> Fix the link to input configuration

src/core/getters/ref.ts, src/core/importers/specs.ts, src/utils/options.ts, src/utils/path.ts
following the tip below to validate `localhost` URLs properly
https://github.com/validatorjs/validator.js/issues/1609#issuecomment-780685689
**READY**
improve URL validation
branch | PR
https://github.com/davidsonsns/orval/tree/url-validation-improvement | #219
=> improve url validation

src/core/getters/queryParams.ts
**READY**
Fix issue #247 
check issue #247
=> fix(query): check content for query schema

src/core/getters/ref.ts
=> fix: better error message when using unsupported ref component

docs/src/pages/reference/cli.md
**READY**
> A few sentences describing the overall goals of the pull request's commits.
In clean section ([this](https://orval.dev/reference/cli#clean)), change `watch` to `clean`
branch | PR
```bash
```
=> fix(docs): Fix wrong word

src/core/getters/enum.ts, src/core/getters/scalar.ts
=> fix(enum): better nullable enum generation

.github/dependabot.yml
**READY**
Fix #306 Add dependabot
=> fix(build): dependabot

src/core/generators/schemaDefinition.ts
**READY**
Schema anyof generation correctly checked and handle
=> fix(generator): schema anyof correctly checked

src/core/getters/combine.ts, src/core/getters/object.ts, src/core/getters/scalar.ts
**READY**
correctly handling object allof enums nullable generation
=> fix(generator): scalar object allof enum nullable

.github/workflows/tests.yaml, .husky/pre-commit, package.json, src/core/getters/params.ts, src/core/getters/route.test.ts, src/core/getters/route.ts, yarn.lock
**READY**
Allow to use `_` and `-` in path params name.
```yaml
paths:
/api/demo/{id}/index
...
/api/demo/users/{user_id}/index
...
```
Before:
```ts
export const getApiDemoIdIndex = (id: string) => {
return client<GetApiDemoIdIndex200>({
url: `/api/demo/${id}/index`,
method: "get",
})
}
// Won't work at all, but the function naming is also breaking:
export const getApiDemoUseridIndex = ...
```
After:
```ts
export const getApiDemoIdIndex = (id: string) => {
return client<GetApiDemoIdIndex200>({
url: `/api/demo/${id}/index`,
method: "get",
})
}
export const getApiDemoUsersUserIdIndex = (userId: string) => {
return client<GetApiDemoUsersUserIdIndex200>({
url: `/api/demo/users/${userId}/index`,
method: "get",
})
}
```
=> feat(params): allow [_-] in url params

samples/react-query/basic/petstore.yaml, src/core/generators/schemaDefinition.ts, src/core/getters/discriminators.ts, tests/specifications/petstore.yaml
=> Add type discriminator to subtypes

docs/src/components/Toc.js, docs/src/components/Toc.module.css
=> fix(docs): add scrollbar to toc

packages/core/src/generators/schema-definition.ts, packages/core/src/getters/ref.ts, packages/core/src/resolvers/ref.ts, tests/configs/multi-file.config.ts, tests/package.json, tests/specifications/multi-files/api.yaml, tests/specifications/multi-files/schemas/pet.yaml
**READY**
A ref cannot be resolved when the ref is pointing to another ref. This is commonly used with components schema (see api.yaml changes in multi-file spec)
This PR solves issue https://github.com/anymaniax/orval/issues/874
Repro: https://codesandbox.io/p/sandbox/blissful-keller-v2biyv
I've added also the multi file config example as `generate:multi-file` npm script in `tests/`
=> fix(core): recursively handle nested refs

packages/core/src/utils/string.ts, packages/zod/src/index.ts
=> fix(zod): regex string escaping

packages/orval/src/generate.ts
=> feat(core): throw on errors

docs/src/pages/guides/custom-axios.md
=> docs(custom-axios.md): fix BodyType docs

package.json, samples/angular-app/package.json, samples/basic/package.json, samples/nx-fastify-react/package.json, samples/react-app/package.json, samples/react-query/form-data-mutator/package.json, samples/react-query/form-data/package.json, samples/react-query/form-url-encoded-mutator/package.json, samples/react-query/form-url-encoded/package.json, samples/react-query/hook-mutator/package.json, samples/svelte-query/package.json, yarn.lock
**READY**
faker was updated in f1b8ff8542a972bd1881fbeaa4f003f599eadabd but some places remain on the old version. This was causing `tests` to fail
```bash
```
1.
=> chore(faker): use `8.0.2` everywhere

packages/core/src/types.ts, packages/core/src/writers/schemas.ts, packages/orval/src/utils/options.ts, packages/orval/src/write-specs.ts
**READY**
Adds an option to disable creating `index.ts` files. 
Set option:
```ts
{
output: {
indexFiles: false
}
}
```
=> feat(core): option to disable creating index files

packages/zod/src/index.ts
**WIP**
Adds support for `minItems` and `maxItems` for array fields.
NA
Will add tests.
=> feat(zod): support array min/max items

packages/core/src/resolvers/ref.ts, packages/core/src/utils/assertion.ts
**READY**
Fix ref import from file, without hash "#"
=> fix(core): fix ref import file

CONTRIBUTING.md
**READY**
Added the initial CONTRIBUTING.md file draft to get it going.
=> feat: initial CONTRIBUTING.md draft

packages/msw/src/mocks.ts
**READY**
Some warning messages are displayed.
So update deprecated methods. (like [this commit](https://github.com/anymaniax/orval/commit/f1b8ff8542a972bd1881fbeaa4f003f599eadabd))
=> feat(faker): update deprecated faker methods

docs/src/pages/guides/custom-client.md, docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/output.md
This pull request fixes typos of docs folder . I request repository maintainers to review and merge it.
prefered -> preferred 
carefull -> careful 
differents -> different 
carefull -> careful 
completly -> completely 
```bash
```
1.
=> docs: fixed typos

CODE_OF_CONDUCT.md, README.md
Fixed #1001 
Added Contributors section to the Readme.md
@melloware  View it and merged the PR! Thank You!!
=> Fixed: Added Contributors section to README.md

docs/src/pages/reference/configuration/output.md
=> docs(config): mutationOptions

README.md
Adds a  badge that leads to: https://snyk.io/advisor/npm-package/orval
=> Snyk Package Health Badge

packages/core/src/getters/query-params.ts, packages/core/src/resolvers/ref.ts, packages/core/src/types.ts, packages/orval/src/generate.ts, packages/query/src/index.ts
**READY**
Fixes some typos in the codebase
N/A
=> style: fix some typos

packages/core/src/getters/body.ts
**READY**
Correctly sanitize request body param name
Fix #1041
=> fix(core): getters body sanitize implementation

packages/zod/src/index.ts, tests/specifications/circular.yaml
**READY**
Fix #889 
Fix #971
Added test to prove we are doing the correct thing and added date instead of REGEXP
=> fix(zod): proper date handling

.github/dependabot.yml
switch to monthly dependabot checks from weekly
=> Dependabot switch to monthly

packages/core/src/getters/res-req-types.ts, tests/configs/react-query.config.ts, tests/mutators/custom-form-data.ts, tests/specifications/form-data.yaml
**WIP**
Handling formdata generation with allof and oneof
For the oneof, we still have an issue of type when we try to add a property to the formdata otherwise everything seems to work well.
=> fix(generators): formdata handling oneof and allof

packages/zod/src/index.ts
=> fix(zod): allow blank value for non-required enums

packages/zod/src/index.ts
Reverts anymaniax/orval#1113
Fixes #1114
I'll work out the proper fix for optional enums in a follow up PR.
=> Revert "fix(zod): allow blank value for non-required enums"

docs/src/pages/reference/configuration/output.md
**READY**
The explanation for `output.indexFiles` was not present in the documentation so I added it
none
PR is just document updates.
=> docs: Add document for `output.indexFiles`

docs/src/pages/guides/set-base-url.md
**READY**
Fix broken link to custom-axios page.
n/a
n/a
=> docs: fix broken link to custom-axios page

packages/query/package.json
**READY**
Reduce the install size.
```bash
```
1.
=> chore: move vitest to devDependencies

packages/core/src/getters/enum.ts
Fix #1153: Fix native TS enums
=> Fix #1153: Fix native TS enums

packages/angular/package.json, packages/axios/package.json, packages/core/package.json, packages/mock/package.json, packages/orval/package.json, packages/query/package.json, packages/swr/package.json, packages/zod/package.json, tsconfig.base.json
=> build: enable sourcemaps

packages/core/src/getters/combine.ts, packages/core/src/getters/object.ts
=> fix: openapi 3.1 schemas with multiple types

packages/angular/src/index.ts, packages/axios/src/index.ts, packages/core/src/generators/interface.ts, packages/core/src/generators/schema-definition.ts, packages/core/src/generators/verbs-options.ts, packages/core/src/getters/array.ts, packages/core/src/getters/body.ts, packages/core/src/getters/combine.ts, packages/core/src/getters/props.ts, packages/core/src/getters/query-params.test.ts, packages/core/src/getters/query-params.ts, packages/core/src/getters/ref.ts, packages/core/src/getters/scalar.ts, packages/core/src/resolvers/object.ts, packages/core/src/types.ts, packages/mock/src/faker/getters/scalar.ts, packages/mock/src/msw/mocks.ts, packages/orval/src/import-open-api.ts, packages/orval/src/utils/options.ts, packages/query/src/index.ts, packages/swr/src/index.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/basic/src/api/model/dog.ts, samples/react-query/basic/src/api/model/pet.ts
=> fix: add option for adding missing props to union types, fix duplicate props

packages/core/src/generators/interface.ts, packages/core/src/getters/object.ts, tests/specifications/example-v3-1.yaml
**READY**
Fix #1108
https://json-schema.org/understanding-json-schema/reference/const
=> feat: support for const types

packages/query/src/index.ts
fix #1162 useMutation still appears even if false
=> fix: useMutation still appears even if false

packages/core/src/utils/validator.ts
fix #1139 fix(core): NPE check in validator
=> fix(core): NPE check in validator

packages/core/src/generators/interface.ts, packages/mock/src/faker/getters/object.ts, packages/orval/src/bin/orval.ts, packages/orval/src/generate.ts, packages/orval/src/utils/watcher.ts
**READY**
removing unused imports
none
none
=> chore: remove unused imports

packages/core/src/types.ts
READY
Fix https://github.com/anymaniax/orval/issues/1282
n/a
?
=> fix(core/src/types.ts): operations option mock data now supports array

packages/core/src/getters/discriminators.ts
**READY**
I fixed a formatting error that had been occurring ever since https://github.com/anymaniax/orval/pull/1305 was merged.
https://github.com/anymaniax/orval/pull/1305
check to no errors occur in CI
=> chore: fix format

docs/src/manifests/manifest.json, docs/src/pages/guides/zod.md, packages/core/src/getters/discriminators.ts
**READY**
I added guide for `zod` 
none
I'll check on document page after merged.
=> docs(zod): add guide for `zod`

packages/zod/src/index.ts
=> fix(zod): handle schema type array correctly

packages/swr/src/index.ts
**READY**
This adds the actual body type to the mutation fetcher instead of using the SWR type Arguments.
Fixes #1323 1323
yarn generate:swr
check petstore/endpoints.ts
notice that `getCreatePetsMutationFetcher` returns a function that has `arg` typed as `CreatePetsBody`, while `getDeletePetByIdMutationFetcher` still has the `Arguments` type, since `deletePetById` does not have a body argument
=> fix(swr): strongly type args in swr mutation fetchers

tests/configs/mock.config.ts, tests/package.json
**READY**
I feel like the options for `mock` have increased.
That's very good. At the same time, I think regression testing is necessary, so I added that.
none
That all the tests I added pass
=> chore: add `mock` tests

docs/src/pages/guides/msw.md
just fixed typo (orverride -> override)
| master | [link](https://github.com/anymaniax/orval/pull/1250) |
```bash
```
1.
=> docs: fix typo

docs/src/pages/reference/configuration/input.md, packages/core/src/types.ts, packages/orval/src/import-specs.ts
=> fix: correct type of filters.tags, add regexp to docs

packages/core/src/getters/combine.ts, tests/specifications/any-of.yaml
**READY**
Fixes #1183
Changed any-of specification to accommodate for this edge case
1. Use the specification in the linked issue
2. Generate
3. Notice error as given in issue, unused imports are given and those imports are instead missing from the file where the errors are.
4. Use new code with the same specification
5. Generate
6. Notice import is correct and there are no errors
=> fix: correct import for anyof enums

packages/core/src/utils/dynamic-import.ts
**READY**
Fixes #1332 
According to the Node docs this should work on linux and macos as well, but I only have a Windows machine, so I cannot verify it myself.
`yarn generate`
transformers should be working
=> fix: path to file url

docs/src/pages/guides/zod.md
**READY**
i fixed sample code in `zod` guide.
https://github.com/anymaniax/orval/pull/1308
None
=> docs(zod): fix sample code in `zod` guide

docs/src/pages/reference/cli.md
**READY*
I added `biome` option to `cli` reference. 
https://github.com/anymaniax/orval/pull/1321
none
=> docs(cli): add `biome` option to `cli` reference

docs/src/pages/reference/configuration/output.md
**READY**
I added `suppressReadonlyModifier` option to guide
https://github.com/anymaniax/orval/pull/1354
none
=> docs: add `suppressReadonlyModifier` option to guide

packages/zod/src/index.ts
**READY**
Fix #1380 and all of the http responses can now be generated.
=> fix(zod): all http responses can now be generated

packages/mock/src/faker/resolvers/value.ts
**READY**
Fix #1441 
| [AffeJonsson:feat/split-poly-mocks](https://github.com/AffeJonsson/orval/tree/feat/split-poly-mocks)| [link](https://github.com/anymaniax/orval/pull/1365) |
=> fix(msw): also split allof objects

packages/orval/src/utils/options.ts, yarn.lock
**READY**
Since "CI" was failing, I formatted.
since merged https://github.com/anymaniax/orval/pull/1445 
none
=> fix: format for `orval` package options

samples/vue-query/public/mockServiceWorker.js
**READY**
After running the command below, the "MSW" setup file of the "vue" sample app has been updated
```
yarn update-samples
yarn test:ci
```
none
```
yarn update-samples
yarn test:ci
```
=> chore: update `MSW` setup file in by regenerate in `vue` sample app

docs/src/pages/reference/configuration/output.md
fix #1322
Also after this merged, I'll close #1361 
After discussing #1361, we agreed to update only the document, so i updated it.
https://github.com/anymaniax/orval/pull/1361
none
=> docs: update `output.allParamsOptional` description

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
**READY**
Properly handling top level rules for array like min or max
=> fix(zod): properly handling top level rules for array

README.md
**READY**
I added a small update in README
none
none
=> docs: add `next-app-with-fetch` reference to `README`

tests/configs/react-query.config.ts, tests/configs/svelte-query.config.ts, tests/configs/vue-query.config.ts
**READY**
I add tests for each query that uses fetch as an http client
none
you can check by execute `yarn test:ci` or seeing if CI is successful.
=> chore: add tests for each query that uses fetch as an http client

docs/src/pages/reference/configuration/output.md
**READY**
I updated `httpClient` option guide to support queries.
none
none
=> docs: updated `httpClient` option guide to support queries

docs/src/pages/guides/fetch-client.md
**READY**
Minor typo but in config key so good to have corrected
N/A / see docs
=> chore: update fetch-client.md (typo)

README.md
=> Add download/month badge

packages/core/src/utils/logger.ts, packages/core/src/utils/validator.ts
=> fix:  detect spec errors and prevent generation of invalid TypeScript code when input.validation is true

docs/src/manifests/manifest.json, docs/src/pages/guides/hono.md
**READY**
I added guide for `Hono`
none
none
=> docs: add `hono` guide

packages/angular/src/index.ts, packages/axios/src/index.ts, packages/core/src/generators/options.ts, packages/core/src/utils/index.ts, packages/core/src/utils/is-body-verb.ts, packages/query/src/client.ts, packages/query/src/index.ts, packages/query/src/utils.ts, packages/swr/src/client.ts
**READY**
Fix https://github.com/orval-labs/orval/issues/1434
Fix https://github.com/orval-labs/orval/issues/1447
https://github.com/orval-labs/orval/pull/1621
=> (fix) support abort signal param for POST requests

samples/hono/hono-with-fetch-client/next-app/app/gen/pets/pets.msw.ts, samples/next-app-with-fetch/app/gen/pets/pets.msw.ts, samples/react-app-with-swr/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts, samples/react-app-with-swr/fetch-client/src/api/endpoints/swaggerPetstore.msw.ts, samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/react-query/custom-fetch/src/gen/pets/pets.msw.ts, samples/react-query/form-data-mutator/endpoints.ts, samples/react-query/form-data/endpoints.ts, samples/react-query/form-url-encoded-mutator/endpoints.ts, samples/react-query/form-url-encoded/endpoints.ts, samples/react-query/hook-mutator/endpoints.ts, samples/svelte-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts, samples/svelte-query/custom-fetch/src/gen/pets/pets.msw.ts, samples/swr-with-zod/src/gen/endpoints/pets/pets.msw.ts, samples/vue-query/custom-fetch/src/gen/pets/pets.msw.ts, samples/vue-query/vue-query-basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
**READY**
I forgot to update the sample app when #1686 was merged so I updated sample apps with master branch.
https://github.com/orval-labs/orval/pull/1686
none
=> chore: update sample apps

packages/core/package.json, yarn.lock
=> fix: snyk jsonpath plus issue

packages/query/src/client.ts, tests/configs/vue-query.config.ts
=> fix(query): vue query unref form data

packages/core/src/getters/res-req-types.ts, tests/specifications/all-of.yaml
**READY**
Fixes #1719 
Follow guide in linked issue.
Pull this change and rebuild.
Try repeating the steps, see that the expected behavior is now applied
=> fix(core): undefined type is sometimes allowed for formdata

docs/src/pages/guides/set-base-url.md
**READY**
Adds info about the new settings available for baseUrl in the set-base-url.md guide.
=> chore(docs): add info about new settings for baseurl in guide

packages/mock/src/faker/getters/combine.ts, packages/mock/src/faker/getters/object.ts
=> fix(msw): fix errornous comma at start of object

packages/core/src/getters/params.ts
=> fix(query): make sure to make definition have optional typing if allParamsOptional is true

packages/mock/src/faker/getters/scalar.ts, tests/specifications/enums.yaml
=> fix(msw): handle integer enums correctly

packages/fetch/src/index.ts
=> fix(fetch): make sure responseDataType is not empty

docs/src/pages/guides/msw.md
**READY**
I added a guide for specifying a function as the `handlers` argument of `msw` and update codes to latest.
```bash
```
1.
=> docs(msw): added a guide for specifying a function as the `handlers` argument of `msw`

packages/core/src/getters/object.ts
**READY**
Fixes #1857 
Previous:
```ts
export interface Pet {
type: PetType;
}
```
New:
```ts
export interface Pet {
type: keyof typeof PetType;
}
```
=> fix(core): keyof typeof on native enum property

packages/core/src/getters/operation.test.ts
Fix broken test due to missing imports. Tests are passing for me locally now.
**READY**
Just adding a missing import to fix a unit test.
```bash
cd packages/core && yarn test
```
=> fix(core): broken test in operation.test.ts

packages/core/src/getters/scalar.ts
**READY**
Fixes #1817 as it was not properly fixed in #1739
| fix/null-type | #1739 |
=> fix(core): corrctly combine schemas if type is array

packages/orval/src/write-specs.ts, yarn.lock
**READY**
Fixed workspace setting does not append a newline to the end of a line in an existing index file.
I don't know the details of the code, so if you think another way is better or whatever, you can close this PR.
- Fix #1875
Please follow the steps in the following Issue
- https://github.com/orval-labs/orval/issues/1875
=> fix(core): Fixed workspace setting does not append a newline to the end of a line in an existing index file #1875

docs/src/pages/reference/configuration/output.md, packages/core/src/generators/imports.ts, packages/core/src/types.ts, packages/core/src/utils/case.ts, packages/core/src/writers/schemas.ts, packages/orval/src/utils/options.ts, packages/orval/src/write-specs.ts, tests/configs/default.config.ts
**READY**
fix #428
Adding naming convention option to output.
1. specify `namingConvention: 'kebab-case'` in the `output` property of `orval.config.js`
3. check the name of the files generated
=> feat(core): ✏️ add naming convention option to output

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
=> feat(zod): add default support

packages/query/src/index.ts
=> fix(query): check for v5 flag

packages/axios/src/index.ts, packages/query/src/index.ts, packages/swr/src/index.ts
**READY**
Fixes #1838 
Solved by following this answer on SA: https://stackoverflow.com/a/75645622
=> fix(core): remove any from type definition

packages/mock/src/faker/getters/combine.ts, packages/mock/src/faker/resolvers/value.ts, tests/configs/default.config.ts, tests/specifications/all-of-all-of.yaml
**READY**
Fix #1895 
@soartec-lab Please verify with your various specs :)
| simplify-combine | #1815  |
=> fix(msw): adjust combine to handle nested allof

packages/zod/src/index.ts
=> feat(zod): generate min max values of array items when using allOf

packages/zod/src/index.ts, tests/configs/zod.config.ts
**READY*
Properly apply the preprocess option everywhere
=> fix(zod): add preprocess properly everywhere

packages/core/src/writers/target-tags.ts, tests/specifications/multiple-tags.yaml
=> fix(core): make sure to only handle first tag when grouping

packages/core/src/getters/ref.ts, tests/configs/react-query.config.ts, tests/specifications/models-with-special-char.yaml
**READY**
Properly handle models starting with underscore and adding a test for special chars in a model name
=> fix(core): model starting with underscore properly handle

packages/core/src/generators/interface.test.ts, packages/core/src/generators/interface.ts, yarn.lock
**READY**
Fix https://github.com/orval-labs/orval/issues/1948
```bash
```
1.
=> fix: generate type for empty property

docs/src/pages/guides/hono.md, docs/src/pages/reference/configuration/output.md
**READY/**
I updated guide and config for hono client
none
none
=> docs(hono): add docs for `hono` orverride setting and update `hono` guide

docs/src/pages/guides/fetch-client.md
READY
Docs fix to avoid copy and paste hassle.
=> docs(fetch): Fix config snippet comma typo

packages/core/src/generators/imports.ts, tests/yarn.lock
=> fix(core): correctly import custom error and body types

packages/core/package.json, yarn.lock
=> chore(deps): @ibm-cloud/openapi-ruleset 1.29.3

packages/fetch/src/index.ts, packages/orval/package.json, packages/orval/src/write-specs.ts, tests/configs/fetch.config.ts, tests/specifications/empty-response.yaml, yarn.lock
=> fix(fetch): add default response if none provided

packages/mock/src/faker/resolvers/value.ts
=> fix(msw): nested ref fixes

packages/core/package.json, yarn.lock
chore(deps): @ibm-cloud/openapi-ruleset": "^1.29.4
=> chore(deps): @ibm-cloud/openapi-ruleset": "^1.29.4

samples/hono/hono-with-fetch-client/next-app/package.json, samples/next-app-with-fetch/package.json, samples/yarn.lock
chore(deps) fix Next.js critical vulnerability
=> chore(deps) fix Next.js critical vulnerability

packages/zod/src/index.ts, packages/zod/src/zod.test.ts
=> fix(zod): handle $ref property names in schemas correctly

docs/src/pages/reference/configuration/output.md, packages/core/src/generators/schema-definition.ts, packages/core/src/getters/enum.ts, packages/core/src/getters/query-params.ts, packages/core/src/resolvers/object.ts, packages/core/src/types.ts, packages/mock/src/faker/getters/scalar.ts, packages/orval/src/utils/options.ts, tests/configs/default.config.ts, tests/configs/swr.config.ts, tests/specifications/enums.yaml
=> feat(core): add union enum generation

samples/yarn.lock, tests/configs/mcp.config.ts, tests/package.json, tests/yarn.lock
**READY**
follow up #1997 
I add a test
you can check in ci
=> chore: add a test for `mcp`

packages/query/src/index.ts
**READY**
Hopefully fixes the issue introduced in #2027
| Edward-Upton:fix/prioritise-query-over-mutations-react-query | #2027 |
=> fix(query): make sure to not generate query and mutation

docs/package.json, docs/yarn.lock, yarn.lock
Update the docs site to use the latest Orval
=> chore(deps): Update docs to Orval 7.9.0

packages/core/src/generators/schema-definition.ts, packages/core/src/getters/combine.ts, packages/core/src/getters/enum.ts, packages/core/src/getters/query-params.ts, packages/core/src/resolvers/object.ts, tests/specifications/enums.yaml
**READY**
Fix #2071
I hope I didn't break anything.
=> feat(core): add x-enum-descriptions support

packages/mock/src/msw/index.ts, tests/configs/react-query.config.ts, tests/specifications/no-content-with-default.yaml
=> chore(test): for no content responses with a default response

docs/src/pages/installation.md
**READY**
adds package install instruction for [pnpm](https://pnpm.io/)
=> add pnpm instructions to docs

packages/core/src/getters/object.ts, samples/mcp/petstore/src/http-client.ts
- Updates URL parameter handling to use Array.isArray()
- Fixes TypeScript error with string | boolean union types
- Improves type checking in array detection
Fix #2187
```bash
```
1.
=> fix: replace instanceof Array with Array.isArray() for type safety #2187

packages/angular/src/index.ts, samples/angular-app/src/api/endpoints/pets/pets.service.ts
=> feat(angular): use inject function over constructor injection

packages/angular/src/index.ts, samples/angular-app/src/api/endpoints/pets/pets.service.ts, tests/package.json, tests/tsconfig.json, tests/yarn.lock
=> feat(angular): added missing HttpClient options

packages/zod/src/index.ts
close #2249 
close #2216 
**READY**
This PR enable to generate correct schema with any string format on zod v4.
Detail is mentioned on #2249 
- Where should I add test? 
- Should I my change move from `packages/zod/src/index.ts` to `packages/zod/src/compatibleV4.ts` and should I write test on `packages/zod/src/compatibleV4.test.ts`?
- No needed
- What is this? Should I work something?
See #2249
=> fix: generate no value zod schema on zod v4. #2249

packages/angular/src/index.ts, samples/angular-app/src/api/endpoints/pets/pets.service.ts, yarn.lock
**READY**
Fix https://github.com/orval-labs/orval/issues/2264
=> fix(angular): incorrect return type, closes #2264

docs/src/pages/reference/cli.md, docs/src/pages/reference/configuration/output.md, packages/orval/src/write-specs.ts, samples/next-app-with-fetch/package.json, samples/react-app-with-swr/basic/package.json, samples/react-app/package.json, samples/react-query/basic/package.json, samples/react-query/custom-client/package.json, samples/react-query/custom-fetch/package.json, samples/react-query/form-data-mutator/package.json, samples/react-query/form-data/package.json, samples/react-query/form-url-encoded-mutator/package.json, samples/react-query/form-url-encoded/package.json, samples/react-query/hook-mutator/package.json, samples/svelte-query/basic/package.json, samples/svelte-query/custom-fetch/package.json, samples/vue-query/custom-fetch/package.json, samples/vue-query/vue-query-basic/package.json, samples/yarn.lock
**READY**
As discussed in #2246 I've updated the docs to say that a global prettier is needed
=> docs: needs globally installed prettier

packages/angular/src/index.ts, packages/core/src/utils/index.ts, samples/angular-app/src/api/endpoints/pets/pets.service.ts
**READY**
fixes #2279
This should be released ASAP as angular client generation is broken since v7.11.0
=> fix(core): export DeepNonNullable for use in clients, fixes #2279

.gitattributes, .github/workflows/tests.yaml
**READY**
Setup git so it checkout and commit LF
https://github.com/orval-labs/orval/pull/2303
=> chore: configured eol=LF

package.json, turbo.json, yarn.lock
**READY**
Updated and migrated turbo to 2.5.6
- https://github.com/orval-labs/orval/pull/2303
=> chore: updated and migrated turbo to 2.5.6

packages/angular/package.json, packages/angular/tsup.config.ts, packages/axios/package.json, packages/axios/tsup.config.ts, packages/core/package.json, packages/core/tsup.config.ts, packages/fetch/package.json, packages/fetch/tsup.config.ts, packages/hono/package.json, packages/hono/tsup.config.ts, packages/mcp/package.json, packages/mcp/tsup.config.ts, packages/mock/package.json, packages/mock/tsup.config.ts, packages/orval/package.json, packages/orval/tsup.config.ts, packages/query/package.json, packages/query/tsup.config.ts, packages/swr/package.json, packages/swr/tsup.config.ts, packages/tsup.base.ts, packages/zod/package.json, packages/zod/tsup.config.ts
**READY**
Simplify and reuse tsup config
- https://github.com/orval-labs/orval/pull/2303
=> chore: simplify and reuse tsup config

package.json, packages/core/package.json, packages/core/vitest.config.ts, packages/mock/package.json, packages/mock/vitest.config.ts, packages/orval/package.json, packages/orval/vitest.config.ts, packages/query/package.json, packages/query/src/index.test.ts, packages/query/vitest.config.ts, packages/zod/package.json, packages/zod/vitest.config.ts, samples/angular-app/package.json, vitest.config.ts, yarn.lock
**READY**
Updates vitest and enables running tests from the IDE.
Tested with VS Code + https://marketplace.visualstudio.com/items?itemName=vitest.explorer
- #2303
=> chore: update and configure vitest

.vscode/settings.json, packages/core/src/generators/mutator.ts, packages/core/src/resolvers/ref.ts, packages/core/src/types.ts, packages/core/src/utils/dynamic-import.ts, packages/core/src/utils/file.ts, packages/core/src/utils/open-api-converter.ts, packages/core/src/utils/validator.ts, packages/core/src/writers/schemas.ts, packages/core/src/writers/single-mode.ts, packages/core/src/writers/split-mode.ts, packages/core/src/writers/split-tags-mode.ts, packages/core/src/writers/tags-mode.ts, packages/orval/src/api.ts, packages/orval/src/bin/orval.ts, packages/orval/src/client.ts, packages/orval/src/generate.ts, packages/orval/src/import-specs.ts, packages/orval/src/utils/github.ts, packages/orval/src/utils/options.ts, packages/orval/src/write-specs.ts, packages/query/src/utils.ts
**READY**
Abide by these rules
- https://typescript-eslint.io/rules/only-throw-error/
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v61.0.2/docs/rules/no-process-exit.md
=> chore: only throw Error and only use exit() in shebang files

samples/basic/package.json, samples/hono/hono-with-fetch-client/hono-app/package.json, tests/package.json
=> chore: fixes some packages being public

packages/zod/src/index.ts
=> feat: allow tree-shaking using wildcard import

packages/query/src/index.ts
Add compatibility to @tanstack/svelte-query v6.
https://tanstack.com/query/latest/docs/framework/svelte/migrate-from-v5-to-v6
> @tanstack/svelte-query v6 adapter fully migrates to the runes syntax.
> Like the Angular and Solid adapters, most functions for the Svelte adapter now require options to be provided as a "thunk" (() => options) to provide reactivity.
This change will check if you have the newer v6 package and use the thunk options. See examples below of output of v5 vs v6.
```ts
// Mutation
return createMutation(mutationOptions, queryClient);
// Query
const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> 
& { queryKey: DataTag<QueryKey, TData, TError>; };
```
```ts
// Mutation
return createMutation(() => ({ ...mutationOptions, queryClient })); …
```
=> feat: add support for Svelte Query v6 compatibility 
